### ISSUE TITLE
Missing runbook_url annotation in alerts

### ISSUE THREAD

**Issue by paulfantom** [prometheus-operator/kube-prometheus#1001]
**What happened?**

After code refactoring post `release-0.7` `runbook_url` is not appended to alerts.

**Did you expect to see some different?**

I expect to have `runbook_url` in alerts which points to kube-prometheus wiki

**How to reproduce it (as minimally and precisely as possible)**:

Take a look at any alert in rendered manifests

**Environment**

* Prometheus Operator version: doesn't matter

* Kubernetes version information: doesn't matter

* Kubernetes cluster kind: doesn't matter

* Manifests:

```
all prometheusRule objects with alerts
```

* Prometheus Operator Logs: doesn't matter

* Prometheus Logs: doesn't matter

**Anything else we need to know?**:

I think this should be a common config applied to all mixins and passed from `$.values.common.runbook_url`

**Comment by paulfantom** [comment]
Seems like some alerts have `runbook_url` annotation but not all of them. We should standardize and have all alerts with `runbook_url`.

**Comment by ArthurSens** [comment]
After a deeper look at kube-prometheus manifests I've noticed that Kubernetes alerts are the only ones with runbook_urls.

The alerts come from upstream:
https://github.com/prometheus-operator/kube-prometheus/blob/ebd4b28b9141f9e79aa979ef00b00048d55a47ba/jsonnet/kube-prometheus/components/k8s-control-plane.libsonnet#L31-L48

The same thing happens to all other libraries, but the difference is that other libraries don't have the `runbook_url` annotation.
