### ISSUE TITLE
Update configuration section with new default values

### ISSUE THREAD

**Issue by lentzi90** [prometheus-operator/kube-prometheus#1020]
**What happened?**
I was reading through the README.md to learn and try out kube-prometheus when I noticed that the [Configuration section](https://github.com/prometheus-operator/kube-prometheus/tree/main#configuration) seem to describe the old configuration (release-0.7 and earlier). It has the old `_config` instead of `values` for example.

**Did you expect to see some different?**
I was expecting the new configuration defaults (which I'm not sure how they really look like) as hinted in the [migration guide](https://github.com/prometheus-operator/kube-prometheus/blob/main/docs/migration-guide.md).

**How to reproduce it (as minimally and precisely as possible)**:
Check the [configuration section of the README.md](https://github.com/prometheus-operator/kube-prometheus/tree/main#configuration).

**Environment**

* Prometheus Operator version:

    `v0.46.0`
    

* Kubernetes version information:

    ```
    Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-21T01:11:42Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
    ```
    

* Kubernetes cluster kind:

    Kubernetes in docker: `kind create cluster`

**Comment by paulfantom** [comment]
New defaults are in https://github.com/prometheus-operator/kube-prometheus/blob/main/jsonnet/kube-prometheus/main.libsonnet#L14-L108. Could you create a PR with an update to our README?

**Comment by lentzi90** [comment]
Thanks for the link! I'll try to update the README and create a PR. :slightly_smiling_face:
