### ISSUE TITLE
metrics 401

### ISSUE THREAD

**Issue by jeffaryhe** [prometheus-operator/kube-prometheus#1026]
kubectl describe apiservice v1beta1.metrics.k8s.io
           Conditions:
            Last Transition Time:  2021-03-12T05:07:23Z
            Message:               failing or missing response from https://10.97.149.143:443/apis/metrics.k8s.io/v1beta1: bad status from https://10.97.149.143:443/apis/metrics.k8s.io/v1beta1: 401
            Reason:                FailedDiscoveryCheck
            Status:                False
            Type:                  Available
        Events:                    <none>

env
kubernetes 1.20   binary  install 。
kube-prometheus   0.7

[root@master1 manifests]# kubectl get pods -n monitoring 
NAME                                   READY   STATUS    RESTARTS   AGE
alertmanager-main-0                    2/2     Running   0          46h
alertmanager-main-1                    2/2     Running   0          46h
alertmanager-main-2                    2/2     Running   0          46h
grafana-5887949688-gjl4b               1/1     Running   0          45h
kube-state-metrics-587bfd4f97-n55mn    3/3     Running   0          46h
node-exporter-kcthp                    2/2     Running   0          46h
node-exporter-lqmhl                    2/2     Running   0          46h
node-exporter-sgnjq                    2/2     Running   0          46h
node-exporter-wjzxb                    2/2     Running   0          46h
node-exporter-xgzc5                    2/2     Running   0          46h
node-exporter-zmzvx                    2/2     Running   0          46h
prometheus-adapter-69b8496df6-ffzvq    1/1     Running   0          21m
prometheus-k8s-0                       2/2     Running   1          46h
prometheus-k8s-1                       2/2     Running   1          46h
prometheus-operator-57c5bbcbb6-945cn   2/2     Running   0          46h

I0312 07:58:10.009137       1 adapter.go:98] successfully using in-cluster auth
I0312 07:58:13.732061       1 serving.go:325] Generated self-signed cert (/var/run/serving-cert/apiserver.crt, /var/run/serving-cert/apiserver.key)
I0312 07:58:15.738310       1 secure_serving.go:197] Serving securely on [::]:6443
I0312 07:58:15.739717       1 requestheader_controller.go:169] Starting RequestHeaderAuthRequestController
I0312 07:58:15.739760       1 shared_informer.go:240] Waiting for caches to sync for RequestHeaderAuthRequestController
I0312 07:58:15.739887       1 dynamic_serving_content.go:130] Starting serving-cert::/var/run/serving-cert/apiserver.crt::/var/run/serving-cert/apiserver.key
I0312 07:58:15.739975       1 tlsconfig.go:240] Starting DynamicServingCertificateController
I0312 07:58:15.740400       1 configmap_cafile_content.go:202] Starting client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0312 07:58:15.740445       1 shared_informer.go:240] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0312 07:58:15.740681       1 configmap_cafile_content.go:202] Starting client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0312 07:58:15.740713       1 shared_informer.go:240] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0312 07:58:15.845289       1 shared_informer.go:247] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::client-ca-file 
I0312 07:58:15.848973       1 shared_informer.go:247] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file 
I0312 07:58:15.850818       1 shared_informer.go:247] Caches are synced for RequestHeaderAuthRequestController 
E0312 07:58:15.866650       1 authentication.go:53] Unable to authenticate the request due to an error: [x509: subject with cn=front-proxy-client is not in the allowed list, x509: certificate signed by unknown authority]
E0312 07:58:15.868147       1 authentication.go:53] Unable to authenticate the request due to an error: [x509: subject with cn=front-proxy-client is not in the allowed list, x509: certificate signed by unknown authority]
E0312 07:58:15.870225       1 authentication.go:53] Unable to authenticate the request due to an error: [x509: subject with cn=front-proxy-client is not in the allowed list, x509: certificate signed by unknown authority]

**Comment by 281889448** [comment]
[root@master1 manifests]# kubectl get pods -n monitoring 
NAME                                   READY   STATUS    RESTARTS   AGE
alertmanager-main-0                    2/2     Running   0          46h
alertmanager-main-1                    2/2     Running   0          46h
alertmanager-main-2                    2/2     Running   0          46h
grafana-5887949688-gjl4b               1/1     Running   0          45h
kube-state-metrics-587bfd4f97-n55mn    3/3     Running   0          46h
node-exporter-kcthp                    2/2     Running   0          46h
node-exporter-lqmhl                    2/2     Running   0          46h
node-exporter-sgnjq                    2/2     Running   0          46h
node-exporter-wjzxb                    2/2     Running   0          46h
node-exporter-xgzc5                    2/2     Running   0          46h
node-exporter-zmzvx                    2/2     Running   0          46h
prometheus-adapter-69b8496df6-ffzvq    1/1     Running   0          21m
prometheus-k8s-0                       2/2     Running   1          46h
prometheus-k8s-1                       2/2     Running   1          46h
prometheus-operator-57c5bbcbb6-945cn   2/2     Running   0          46h

**Comment by Daydreamer-zz** [comment]
I also met this error this days, you need to Specify the prometheus-adapter-deployment add extra arg --requestheader-client-ca-file,this cert path same as kube-apiserver ,I add an hostpath volume to mont this cert file
here is my yaml 
```yaml
...
    spec:
      containers:
      - args:
        - --cert-dir=/var/run/serving-cert
        - --config=/etc/adapter/config.yaml
        - --logtostderr=true
        - --metrics-relist-interval=1m
        - --prometheus-url=http://prometheus-k8s.monitoring.svc.cluster.local:9090/
        - --secure-port=6443
        # add this extra arg here
        - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.pem
...
        volumeMounts:
.....
        - mountPath: /etc/kubernetes/pki
          name: ca-ssl
....
      - hostPath:
          path: /etc/kubernetes/pki
        name: ca-ssl
....
```
