### ISSUE TITLE
Allow configuring the platform used directly instead of having to use a patch

### ISSUE THREAD

**Issue by brancz** [prometheus-operator/kube-prometheus#1029]
**What is missing?**

I was chatting with @paulfantom and we were thinking of having a first-class field in our top level configuration called `platform` that applies the respective platform specific patch automatically, instead of people having to understand how to use it in jsonnet.

**Why do we need it?**

Easier usage, to drive further adoption of kube-prometheus.

---

This should be relatively straight forward to implement. Anyone would like to give this a try?

**Comment by dgrisonnet** [comment]
I can give it a shot.

**Comment by paulfantom** [comment]
Few pointers:
- It might be easiest to introduce this field either in `$.values.common` or in `$.values.kubePrometheus`. The latter sounds like the best place to put it.
- Current code design requires us to join one of addons to enable usage in a platform. Probably the best course of action, for now, would be to implement the logic in a separate file (in `addons`?) and join this in `main.libsonnet` like:
```
{
  values:
  ...
} + (import 'the_file.libsonnet')
```
- By default `platform` should be `null` and in such a scenario included file shouldn't produce any additional content.
