### ISSUE TITLE
no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"

### ISSUE THREAD

**Issue by jambojet-rus** [prometheus-operator/kube-prometheus#1055]
**What did you do?**
pwd
~/kube-prometheus/manifests
kubectl create -f manifests/setup
until kubectl get servicemonitors --all-namespaces ; do date; sleep 1; echo ""; done
kubectl create -f manifests/
**Did you expect to see some different?**
Expected to see all manifests get applied
**Environment**
master branch of this project
* Prometheus Operator version:
quay.io/prometheus-operator/prometheus-operator:v0.46.0
    
* Kubernetes version information:

    Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
    

* Kubernetes cluster kind:

    Cluster created by kubespray from master branch, version 1.20.5

* Manifests:

kube-prometheus/manifests/setup/*

* Prometheus Operator Logs:
level=info ts=2021-03-22T13:48:26.385131073Z caller=main.go:233 msg="Starting Prometheus Operator" version="(version=0.46.0, branch=refs/tags/pkg/client/v0.46.0, revision=7f94a06b86d41c20176f0d5b53aa0100fdc361e6)"
level=info ts=2021-03-22T13:48:26.385208019Z caller=main.go:234 build_context="(go=go1.15.8, user=s-urbaniak, date=20210224-17:30:02)"
level=info ts=2021-03-22T13:48:26.478637117Z caller=main.go:108 msg="Starting insecure server on [::]:8080"
level=info ts=2021-03-22T13:48:26.487582544Z caller=operator.go:300 component=thanosoperator msg="connection established" cluster-version=v1.20.5
level=info ts=2021-03-22T13:48:26.487624155Z caller=operator.go:309 component=thanosoperator msg="CRD API endpoints ready"
level=info ts=2021-03-22T13:48:26.487741507Z caller=operator.go:416 component=prometheusoperator msg="connection established" cluster-version=v1.20.5
level=info ts=2021-03-22T13:48:26.487780556Z caller=operator.go:425 component=prometheusoperator msg="CRD API endpoints ready"
level=info ts=2021-03-22T13:48:26.487754505Z caller=operator.go:438 component=alertmanageroperator msg="connection established" cluster-version=v1.20.5
level=info ts=2021-03-22T13:48:26.487800217Z caller=operator.go:447 component=alertmanageroperator msg="CRD API endpoints ready"
level=info ts=2021-03-22T13:48:27.274319641Z caller=operator.go:279 component=alertmanageroperator msg="successfully synced all caches"
level=info ts=2021-03-22T13:48:27.374850765Z caller=operator.go:261 component=thanosoperator msg="successfully synced all caches"
level=info ts=2021-03-22T13:48:27.388380725Z caller=operator.go:355 component=prometheusoperator msg="successfully synced all caches"
```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:
I have a problem with deployment prometheus-operator.
1. Execute: kubectl create -f manifests/setup
Result: namespace/monitoring created
customresourcedefinition.apiextensions.k8s.io/alertmanagerconfigs.monitoring.coreos.com created
customresourcedefinition.apiextensions.k8s.io/alertmanagers.monitoring.coreos.com created
customresourcedefinition.apiextensions.k8s.io/podmonitors.monitoring.coreos.com created
customresourcedefinition.apiextensions.k8s.io/probes.monitoring.coreos.com created
customresourcedefinition.apiextensions.k8s.io/prometheuses.monitoring.coreos.com created
customresourcedefinition.apiextensions.k8s.io/prometheusrules.monitoring.coreos.com created
customresourcedefinition.apiextensions.k8s.io/servicemonitors.monitoring.coreos.com created
customresourcedefinition.apiextensions.k8s.io/thanosrulers.monitoring.coreos.com created
clusterrole.rbac.authorization.k8s.io/prometheus-operator created
clusterrolebinding.rbac.authorization.k8s.io/prometheus-operator created
deployment.apps/prometheus-operator created
service/prometheus-operator created
serviceaccount/prometheus-operator created
2. Execute in other window: until kubectl get servicemonitors --all-namespaces ; do date; sleep 1; echo ""; done
Result: error: the server doesn't have a resource type "servicemonitors"
Tue Mar 23 11:24:06 MSK 2021

error: the server doesn't have a resource type "servicemonitors"
Tue Mar 23 11:24:07 MSK 2021

error: the server doesn't have a resource type "servicemonitors"
Tue Mar 23 11:24:08 MSK 2021

error: the server doesn't have a resource type "servicemonitors"
Tue Mar 23 11:24:09 MSK 2021

error: the server doesn't have a resource type "servicemonitors"
Tue Mar 23 11:24:10 MSK 2021
3. Execute: kubectl create -f manifests/
Result: poddisruptionbudget.policy/alertmanager-main created
secret/alertmanager-main created
service/alertmanager-main created
serviceaccount/alertmanager-main created
clusterrole.rbac.authorization.k8s.io/blackbox-exporter created
clusterrolebinding.rbac.authorization.k8s.io/blackbox-exporter created
configmap/blackbox-exporter-configuration created
deployment.apps/blackbox-exporter created
service/blackbox-exporter created
serviceaccount/blackbox-exporter created
secret/grafana-datasources created
configmap/grafana-dashboard-apiserver created
configmap/grafana-dashboard-cluster-total created
configmap/grafana-dashboard-controller-manager created
configmap/grafana-dashboard-k8s-resources-cluster created
configmap/grafana-dashboard-k8s-resources-namespace created
configmap/grafana-dashboard-k8s-resources-node created
configmap/grafana-dashboard-k8s-resources-pod created
configmap/grafana-dashboard-k8s-resources-workload created
configmap/grafana-dashboard-k8s-resources-workloads-namespace created
configmap/grafana-dashboard-kubelet created
configmap/grafana-dashboard-namespace-by-pod created
configmap/grafana-dashboard-namespace-by-workload created
configmap/grafana-dashboard-node-cluster-rsrc-use created
configmap/grafana-dashboard-node-rsrc-use created
configmap/grafana-dashboard-nodes created
configmap/grafana-dashboard-persistentvolumesusage created
configmap/grafana-dashboard-pod-total created
configmap/grafana-dashboard-prometheus-remote-write created
configmap/grafana-dashboard-prometheus created
configmap/grafana-dashboard-proxy created
configmap/grafana-dashboard-scheduler created
configmap/grafana-dashboard-statefulset created
configmap/grafana-dashboard-workload-total created
configmap/grafana-dashboards created
deployment.apps/grafana created
service/grafana created
serviceaccount/grafana created
clusterrole.rbac.authorization.k8s.io/kube-state-metrics created
clusterrolebinding.rbac.authorization.k8s.io/kube-state-metrics created
deployment.apps/kube-state-metrics created
service/kube-state-metrics created
serviceaccount/kube-state-metrics created
clusterrole.rbac.authorization.k8s.io/node-exporter created
clusterrolebinding.rbac.authorization.k8s.io/node-exporter created
daemonset.apps/node-exporter created
service/node-exporter created
serviceaccount/node-exporter created
apiservice.apiregistration.k8s.io/v1beta1.metrics.k8s.io created
clusterrole.rbac.authorization.k8s.io/prometheus-adapter created
clusterrole.rbac.authorization.k8s.io/system:aggregated-metrics-reader created
clusterrolebinding.rbac.authorization.k8s.io/prometheus-adapter created
clusterrolebinding.rbac.authorization.k8s.io/resource-metrics:system:auth-delegator created
clusterrole.rbac.authorization.k8s.io/resource-metrics-server-resources created
configmap/adapter-config created
deployment.apps/prometheus-adapter created
rolebinding.rbac.authorization.k8s.io/resource-metrics-auth-reader created
service/prometheus-adapter created
serviceaccount/prometheus-adapter created
clusterrole.rbac.authorization.k8s.io/prometheus-k8s created
clusterrolebinding.rbac.authorization.k8s.io/prometheus-k8s created
poddisruptionbudget.policy/prometheus-k8s created
rolebinding.rbac.authorization.k8s.io/prometheus-k8s-config created
rolebinding.rbac.authorization.k8s.io/prometheus-k8s created
rolebinding.rbac.authorization.k8s.io/prometheus-k8s created
rolebinding.rbac.authorization.k8s.io/prometheus-k8s created
role.rbac.authorization.k8s.io/prometheus-k8s-config created
role.rbac.authorization.k8s.io/prometheus-k8s created
role.rbac.authorization.k8s.io/prometheus-k8s created
role.rbac.authorization.k8s.io/prometheus-k8s created
service/prometheus-k8s created
serviceaccount/prometheus-k8s created
unable to recognize "alertmanager-alertmanager.yaml": no matches for kind "Alertmanager" in version "monitoring.coreos.com/v1"
unable to recognize "alertmanager-prometheusRule.yaml": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1"
unable to recognize "alertmanager-serviceMonitor.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize "blackbox-exporter-serviceMonitor.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize "grafana-serviceMonitor.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize "kube-prometheus-prometheusRule.yaml": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1"
unable to recognize "kube-state-metrics-prometheusRule.yaml": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1"
unable to recognize "kube-state-metrics-serviceMonitor.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize "kubernetes-prometheusRule.yaml": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1"
unable to recognize "kubernetes-serviceMonitorApiserver.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize "kubernetes-serviceMonitorCoreDNS.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize "kubernetes-serviceMonitorKubeControllerManager.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize "kubernetes-serviceMonitorKubeScheduler.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize "kubernetes-serviceMonitorKubelet.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize "node-exporter-prometheusRule.yaml": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1"
unable to recognize "node-exporter-serviceMonitor.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize "prometheus-adapter-serviceMonitor.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize "prometheus-operator-prometheusRule.yaml": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1"
unable to recognize "prometheus-operator-serviceMonitor.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize "prometheus-prometheus.yaml": no matches for kind "Prometheus" in version "monitoring.coreos.com/v1"
unable to recognize "prometheus-prometheusRule.yaml": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1"
unable to recognize "prometheus-serviceMonitor.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"

I need help!

**Comment by jambojet-rus** [comment]
My problem was in kubectl, i have reinstalled kubectl - it has helped to resolve my problem.

**Comment by hikaruxxo** [comment]
how to resolve?
