### ISSUE TITLE
images pull error  k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.0.0-rc.0

### ISSUE THREAD

**Issue by gzwxh** [prometheus-operator/kube-prometheus#1061]
This repository now has the new GitHub Discussions enabled: 
https://github.com/coreos/kube-prometheus/discussions
通过 manifests/kube-state-metrics-deployment.yaml 文件进行安装，报错镜像无法下载，使用中国大陆境内的服务器都无法下载，是否可以将镜像上传到 hub.docker.com 仓库中呢

**Comment by lilic** [comment]
Hello @gzwxh I am not having any issues with it

```
➜  perf-tests git:(refactor) ✗ docker run -it k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.0.0-rc.0 --version
version.Version{GitCommit:"", BuildDate:"2021-03-04T13:28:24Z", Release:"v2.0.0-rc.0", GoVersion:"go1.15.3", Compiler:"gc", Platform:"linux/amd64"}
```

Can you maybe explain what kind of errors you have?

**Comment by paulfantom** [comment]
@gzwxh If you environments are behind The Great Firewall of China then it is possible that Google Container Registry hosting kube-state-metrics is not available to you. Kube-state-metrics project provide alternative image hosted on quay which should be available at [quay.io/coreos/kube-state-metrics](https://quay.io/repository/coreos/kube-state-metrics).

**Comment by lilic** [comment]
@paulfantom we have deprecated the building of the quay images as per the latest release notes.

@gzwxh you can always build your own images and override them in jsonnet. We have a make target for this in kube-state-metrics. `REGISTRY=<YOUR-REGISTRY-HERE> make container`

**Comment by gzwxh** [comment]
谢谢
