### ISSUE TITLE
why no "pushgateway" yaml files exists in manifests folder?

### ISSUE THREAD

**Issue by ZhiqiangTao** [prometheus-operator/kube-prometheus#1077]
I use branch "release-0.7"
![image](https://user-images.githubusercontent.com/16182251/114030105-cad9cb80-98ac-11eb-8b78-a2bc1cb97c57.png)

but why no  any "pushgateway" yaml files exists? Are they removed by default?

**Comment by paulfantom** [comment]
Pushgateway was never included in kube-prometheus.
