### ISSUE TITLE
Upgrade to grafana 7.5

### ISSUE THREAD

**Issue by daurnimator** [prometheus-operator/kube-prometheus#1082]
**What is missing?**

Grafana 7.5: https://grafana.com/blog/2021/03/25/grafana-7.5-released-loki-alerting-and-label-browser-for-logs-next-generation-pie-chart-and-more/

**Comment by xpepermint** [comment]
PR waiting: https://github.com/prometheus-operator/kube-prometheus/pull/1092

**Comment by paulfantom** [comment]
#1092 was merged
