### ISSUE TITLE
Some of panels in node dashboard doesn't work

### ISSUE THREAD

**Issue by xadereq** [prometheus-operator/kube-prometheus#1104]
**What happened?**

After fresh installation of kube-prometheus with default grafana dashboards (and configuration), some of panels with new `$__rate_interval` feature doesn't work.
After entering Nodes dashboard it looks like this:

![image](https://user-images.githubusercontent.com/5068093/115861474-1e165700-a433-11eb-85cd-500870d7e5fe.png)

And few errors appearing in dev console:

![image](https://user-images.githubusercontent.com/5068093/115861720-6c2b5a80-a433-11eb-9d35-58fb2a9d4145.png)

after manual live-change of min step from `$__rate_interval` to `$__interval`, graph is showing up properly (but with errors from dev console in query window)

```
PanelQueryRunner Error Error: Invalid interval string, has to be either unit-less or end with one of the following units: "y, M, w, d, h, m, s, ms"
```

**Did you expect to see some different?**

Every panel in dashboard should work properly.

**How to reproduce it (as minimally and precisely as possible)**:

as above

**Environment**

* Prometheus Operator version:

latest from HEAD in kube-prometheus

* Kubernetes version information:

1.20.5

* Kubernetes cluster kind:

kubeadm

**Comment by ArthurSens** [comment]
I can see the same problems, I think it was introduced by this PR: https://github.com/prometheus/node_exporter/pull/1995
