### ISSUE TITLE
Add support for sigv4

### ISSUE THREAD

**Issue by falmada** [prometheus-operator/kube-prometheus#1108]
**What is missing?**

Prometheus 2.26 brings support for [AWS's Signature Verification 4 signing process](https://aws.amazon.com/es/blogs/opensource/prometheus-2-26-0-adds-aws-signature-version-4-support/), which removes the need to rely on a side-car for the same. This is also described on the [prometheus doc](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write) (check for "sigv4") for version 2.26.

**Why do we need it?**

It would be nice to have schemas updated to support this on next release, as this is a must to support AMP service from Amazon, and guess that many companies will eventually move to that if they want to ingest and store metrics on that service ([currently in preview](https://docs.aws.amazon.com/prometheus/latest/userguide/what-is-Amazon-Managed-Service-Prometheus.html)).

**Environment**

* kube-prometheus version:

    752d1a7fdc7a34d11cb93716e2f0939f16393248

**Anything else we need to know?**:
    Amazon [describes the process](https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-onboard-ingest-metrics-existing-Prometheus.html) using prometheus release from prometheus-community on Helm

**Comment by paulfantom** [comment]
sigv4 is part of prometheus remote-write spec and it needs to be supported in prometheus-operator first (there is PR in https://github.com/prometheus-operator/prometheus-operator/pull/3994). When this support is complete, there is no action for kube-prometheus apart from updating CRDs from prometheus-operator. Which we will do as soon as there is a new version of prometheus-operator.

For helm-related schemas, please open an issue in https://github.com/prometheus-community/helm-charts as we do not maintain those charts.

I am closing this as the main issue is in https://github.com/prometheus-operator/prometheus-operator/issues/3987 and this is no-op for kube-prometheus.
