### ISSUE TITLE
Replace deprecated arguments for prometheus-config-reloader

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/kube-prometheus#1139]
**What happened?**

Starting with Prometheus operator v0.47.0, `--config-reloader-cpu` and `--config-reloader-memory` are deprecated and replaced respectively by `--config-reloader-cpu-limit`/`--config-reloader-cpu-request` and `--config-reloader-memory-limit`/`--config-reloader-memory-request`.

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

N/A

* Kubernetes cluster kind:

N/A

* Manifests:

N/A

* Prometheus Operator Logs:

```
level=warn ts=2021-05-06T16:19:17.411650351Z caller=main.go:282 msg="The '--config-reloader-cpu' flag has been deprecated! Please use '--config-reloader-cpu-limit' and '--config-reloader-cpu-request' according to your use-case."
level=warn ts=2021-05-06T16:19:17.411892155Z caller=main.go:285 msg="The '--config-reloader-memory' flag has been deprecated! Please use '--config-reloader-memory-limit' and '--config-reloader-memory-request' according to your use-case."
```

* Prometheus Logs:

N/A

**Anything else we need to know?**:

AFAICT the only place where kube-prometheus pokes at the arguments is here (not sure why it only removes CPU limits though):

https://github.com/prometheus-operator/kube-prometheus/blob/a1210f1efff79560b2a85417049a1b656364f001/jsonnet/kube-prometheus/addons/strip-limits.libsonnet#L33-L47

**Comment by paulfantom** [comment]
It looks like this add-on isn't used very often. Maybe we should consider removing it?

@prometheus-operator/kube-prometheus-reviewers wdyt?

**Comment by ArthurSens** [comment]
I do use it 😅, but no strong feelings for it... I can recreate the addon downstream

**Comment by paulfantom** [comment]
> I do use it

Then let's fix it here! :) I would prefer to have more such addons in kube-prometheus than forcing everyone to create them by themselves.

**Comment by ArthurSens** [comment]
What needs to be fixed here? Looks like the deprecated flag was already replaced in #1140

**Comment by paulfantom** [comment]
Indeed! Seems like the best solution - no need to code :smile:
