### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by Azbesciak** [prometheus-operator/kube-prometheus#1141]
Hello, I wonder if it is possible to use these templates in docker for windows.
I ask because when applying code from [quick start](https://github.com/prometheus-operator/kube-prometheus#quickstart).
I added a comment in [helm-charts](https://github.com/prometheus-community/helm-charts/issues/467#issuecomment-834157912) because I have found a similar error there - but not sure if it is the right place.

The error I receive is right below
![image](https://user-images.githubusercontent.com/17334466/117567341-2f5e9500-b0bc-11eb-8526-9a93b6a9a722.png)

I suppose the issue is in [node-exporter-deamonset](https://github.com/prometheus-operator/kube-prometheus/blob/3b1f268d519455165418ab047decbab1cdd92684/manifests/node-exporter-daemonset.yaml#L92). Maybe there should be a replacement for this exported, [a special one for windows](https://github.com/prometheus-community/windows_exporter), or paths just should be changed?

Any help appreciated, I spent some time to find this issue - unfortunately, it 'kills'(these are working but not really) all my services.
Thanks!

**Comment by paulfantom** [comment]
node_exporter shouldn't be deployed to windows nodes as it has (nodeSelector set to linux boxes)only[https://github.com/prometheus-operator/kube-prometheus/blob/main/jsonnet/kube-prometheus/components/node-exporter.libsonnet#L228].

We do have an addon for windows machines available in [addons/windows.libsonnet](https://github.com/prometheus-operator/kube-prometheus/blob/main/jsonnet/kube-prometheus/addons/windows.libsonnet) with short docs in https://github.com/prometheus-operator/kube-prometheus/blob/main/docs/windows.md.

> I added a comment in helm-charts because I have found a similar error there

We do not maintain helm charts.

**Comment by Azbesciak** [comment]
Thanks. To sum up, I rather have no chance to test metrics on windows - I need to set up a Linux-based machine?

**Comment by paulfantom** [comment]
At least one machine in a cluster needs to be linux one as most of the components run only on linux.
