### ISSUE TITLE
How to use  environment variables ?

### ISSUE THREAD

**Issue by x5575358** [prometheus-operator/kube-prometheus#1152]
I  want to modify alertmanager environment variables ,but i can't 
My k8s is not in public network .
I want to  sent alert to my wechat

error: error validating "alertmanager/alertmanager-alertmanager.yaml": error validating data: ValidationError(Alertmanager.spec): unknown field "env" in com.coreos.monitoring.v1.Alertmanager.spec; if you choose to ignore these errors, turn validation off with --validate=false

My config：
- env:
  - name: https_proxy
    value: http://x.x.x.x:8080
  - name: no_proxy
    value: "127.0.0.1,10.0.0.0/8"

**Comment by paulfantom** [comment]
Ignoring those validation issues doesn't make any sense as those won't be picked up by the prometheus-operator and won't be included in alertmanager statefulset. On top of that alertmanager itself won't pick up such environment variables even if you set them. For this to work, you need to specify `proxy_url` in alertmanager configuration. More on the topic:
- https://prometheus.io/docs/alerting/latest/configuration/#http_config
- https://github.com/prometheus-operator/prometheus-operator/issues/399
