### ISSUE TITLE
Deploy a second Prometheus alongside kube-prometheus

### ISSUE THREAD

**Issue by jamessewell** [prometheus-operator/kube-prometheus#1159]
Firstly this project is great - big fan!

I have a bunch of application metrics I want to store in a Prom as well as all the k8s stuff. 

As per Prometheus best practice I want these in [different Prometheus instances](https://github.com/prometheus/prometheus/issues/3200)  because I need them to have different retention periods (esp give how much info this project provides).

I would love to have one jsonnet monitoring deployment which deploys the following:

- full kube-prometheus stack
- an extra Prometheus which will be used for application metrics, which does not automatically scrape the k8s metrics

The alertmanagers would (hopefully) be shared, as would the Grafana.

Is this something which is workable?

**Comment by paulfantom** [comment]
This is entirely possible and you have 2 ways of doing this.
1) Install separate prometheus-operator only for that prometheus (example of this is cluster-monitoring-operator with jsonnet in [here](https://github.com/openshift/cluster-monitoring-operator/tree/master/jsonnet) and generated assets in [here](https://github.com/openshift/cluster-monitoring-operator/tree/master/assets)
2) Use one prometheus-operator and just add another `Prometheus` object. For this you need to ensure correct selectors are set, so you don't end up with the same metrics in both tenants (unless you want it ofc)

In essence the second approach would look something like this:
```jsonnet
local prometheus = import 'kube-prometheus/components/prometheus.libsonnet';
local kp = (import 'kube-prometheus/main.libsonnet') + {
  values+:: {
    prometheusAdditional: {
    // Put here settings similar to https://github.com/prometheus-operator/kube-prometheus/blob/main/jsonnet/kube-prometheus/main.libsonnet#L87-L92
    }
  },
  { 
    prometheusAdditional: prometheus($.values.prometheusAdditional),
  },
};

# Manifestation

{ 'setup/0namespace-namespace': kp.kubePrometheus.namespace } +
{
  ['setup/prometheus-operator-' + name]: kp.prometheusOperator[name]
  for name in std.filter((function(name) name != 'serviceMonitor' && name != 'prometheusRule'), std.objectFields(kp.prometheusOperator))
} +
// serviceMonitor and prometheusRule are separated so that they can be created after the CRDs are ready
{ 'prometheus-operator-serviceMonitor': kp.prometheusOperator.serviceMonitor } +
{ 'prometheus-operator-prometheusRule': kp.prometheusOperator.prometheusRule } +
{ 'kube-prometheus-prometheusRule': kp.kubePrometheus.prometheusRule } +
{ ['alertmanager-' + name]: kp.alertmanager[name] for name in std.objectFields(kp.alertmanager) } +
{ ['blackbox-exporter-' + name]: kp.blackboxExporter[name] for name in std.objectFields(kp.blackboxExporter) } +
{ ['grafana-' + name]: kp.grafana[name] for name in std.objectFields(kp.grafana) } +
{ ['kube-state-metrics-' + name]: kp.kubeStateMetrics[name] for name in std.objectFields(kp.kubeStateMetrics) } +
{ ['kubernetes-' + name]: kp.kubernetesControlPlane[name] for name in std.objectFields(kp.kubernetesControlPlane) }
{ ['node-exporter-' + name]: kp.nodeExporter[name] for name in std.objectFields(kp.nodeExporter) } +
{ ['prometheus-' + name]: kp.prometheus[name] for name in std.objectFields(kp.prometheus) } +
{ ['prometheusAdditional-' + name]: kp.prometheusAdditional[name] for name in std.objectFields(kp.prometheusAdditional) } +
{ ['prometheus-adapter-' + name]: kp.prometheusAdapter[name] for name in std.objectFields(kp.prometheusAdapter) }

```

The manifestation part could be also simplified with sth like:
```jsonnet
{
  [component + '/' + resource + '.yaml']: std.manifestYamlDoc(kp[component][resource])
  for component in std.objectFields(kp)
  for resource in std.objectFields(kp[component])
}
```

**Comment by jamessewell** [comment]
How would I make sure that they weren't both scraping the same metrics (ie: are looking at different ServiceMonitor and Pod Monitor?)

**Comment by paulfantom** [comment]
You can use different sets of `serviceMonitorSelector`, `podMonitorSelector`, `ruleSelector`, etc. in respective `Prometheus` object and/or [you can limit prometheus access to specific namespaces](https://github.com/prometheus-operator/kube-prometheus#adding-additional-namespaces-to-monitor).

**Comment by Danny5487401** [comment]
is there any full example for additional prometheus?
