### ISSUE TITLE
kops platform issue with k8s service selectors 

### ISSUE THREAD

**Issue by a8j8i8t8** [prometheus-operator/kube-prometheus#1163]
**What happened?**
There is a bug in release `release-0.8` in kops platform.

**Did you expect to see some different?**
Selectors for scheduler, controllerManager and kube-dns are wrong.

**How to reproduce it (as minimally and precisely as possible)**:
Use release-0.8 to create manifests for `kube-prometheus/platforms/kops.libsonnet`.

**Environment**

* Prometheus Operator version:

    `0.47.0`
    

* Kubernetes version information:

    `1.20.7`
    

* Kubernetes cluster kind:

    `kops`

**Anything else we need to know?**:
Label key should be `k8s-app` instead of `app.kubernetes.io/name`.

**Comment by dmcnaught** [comment]
@paulfantom I see this fixed in main, can we also fix in release-0.8?

**Comment by paulfantom** [comment]
@dmcnaught feel free to create a backport PR :)

**Comment by dmcnaught** [comment]
https://github.com/prometheus-operator/kube-prometheus/pull/1189
