### ISSUE TITLE
Can I set the time zone to CST or other time zones, because utc is too unfriendly to us. I've tried changing the container's time zone. it's no good.

### ISSUE THREAD

**Issue by li-sen** [prometheus-operator/kube-prometheus#1185]
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* Prometheus Operator version:

	insert image tag or Git SHA here

* Kubernetes version information:

	insert output of `kubectl version` here

* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by paulfantom** [comment]
Closing the issues as this is doable now with:
```
values+: {
  kubernetesControlPlane+: {
    mixin+: {
      _config+: {
        grafanaK8s+: {
          grafanaTimezone: "YOUR_TIMEZONE",
        },
      },
    },
  },
},
```
