### ISSUE TITLE
node-exporter TargetDown

### ISSUE THREAD

**Issue by hpio** [prometheus-operator/kube-prometheus#1187]
**What did you do?**

Installed `prometheus-operator` using Helm chart found here: https://github.com/helm/charts/tree/master/stable/prometheus-operator . My GKE test cluster uses preemptible nodes and after nodes are preemptied I start getting alerts from Prometheus that *node-exporter* targets are down even though all node-exporters are up and running (I see metrics when port-forwarding to them)

```
Labels | State | Active Since | Value
-- | -- | -- | --
alertname="TargetDown"   job="node-exporter"  severity="warning" | firing | 2018-11-21 10:46:39.941756819 +0000 UTC | 66.66666666666666
```

```
❯ kubectl get po -n monitoring
NAME                                                     READY   STATUS    RESTARTS   AGE
alertmanager-monitoring-prometheus-oper-alertmanager-0   2/2     Running   0          3h
monitoring-grafana-679df6bd5-vn2wz                       3/3     Running   4          1d
monitoring-kube-state-metrics-764d6d59df-k7829           1/1     Running   0          3h
monitoring-prometheus-node-exporter-4nnjq                1/1     Running   0          1d
monitoring-prometheus-node-exporter-ggvrs                1/1     Running   0          21h
monitoring-prometheus-node-exporter-hggzv                1/1     Running   0          21h
monitoring-prometheus-node-exporter-jwxcn                1/1     Running   0          1d
monitoring-prometheus-oper-operator-55564b6cbb-rdzqm     1/1     Running   0          2h
prometheus-monitoring-prometheus-oper-prometheus-0       3/3     Running   0          2h
```

**What did you expect to see?**

After nodes are removed/preemptied and new nodes are added node-exporter targets are refreshed and always pick up new nodes

**What did you see instead? Under which circumstances?**
At the moment I have 4 nodes in my cluster but metrics in Prometheus are only available for 2 of them

**Environment**

* Prometheus Operator version:

	quay.io/coreos/prometheus-operator:v0.25.0

* Kubernetes version information:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.7-gke.11", GitCommit:"fa90543563c9cfafca69128ce8cd9ecd5941940f", GitTreeState:"clean", BuildDate:"2018-11-08T20:22:21Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	GKE cluster created with terraform

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
haven't found any specific errors 
```

**Comment by frouzbeh** [comment]
@brancz Hi,  has this issue been fixed?

**Comment by trotro** [comment]
I think the issue is on the expression used: `100  * (count by(job) (up == 0) / count by(job) (up)) > 10`.

When my exporter-nodes comes back up the expression `count by(job) (up == 0)` returns "no data".
Imho, we should have a 0 instead. Then the expression become `100  * (0 / count by(job) (up)) > 10`.
But again, the result returns "no data", because the expression `0 > 10` returns "no data".
It appears that when a correct expression gets 0 results the default answer is "no data".

I may be wrong, but I think a mathematical expression should return 0 instead of "no data" in that case.
