### ISSUE TITLE
Kubectl apply-f Prometheus - Prometheus. YAML error

### ISSUE THREAD

**Issue by guapiguai** [prometheus-operator/kube-prometheus#1195]
error: error validating "prometheus-prometheus.yaml": error validating data: [ValidationError(Prometheus.spec): unknown field "enableFeatures" in com.coreos.monitoring.v1.Prometheus.spec, ValidationError(Prometheus.spec): unknown field "probeNamespaceSelector" in com.coreos.monitoring.v1.Prometheus.spec, ValidationError(Prometheus.spec): unknown field "probeSelector" in com.coreos.monitoring.v1.Prometheus.spec]; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by paulfantom** [comment]
For people who find it later, this is usually a case with too old version of installed CRDs.
