### ISSUE TITLE
How to remove/disable alert manager

### ISSUE THREAD

**Issue by sunilthemaster** [prometheus-operator/kube-prometheus#1251]
We are using 3rd party alert manager and we dont want to use the one which comes shipped with prometheus. 

I removed service and all but then prometheus-operator is continuously throwing below error

> caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="pkg/mod/k8s.io/client-go@v0.21.0/tools/cache/reflector.go:167: Failed to watch *v1alpha1.AlertmanagerConfig: failed to list *v1alpha1.AlertmanagerConfig: the server could not find the requested resource (get alertmanagerconfigs.monitoring.coreos.com)"

Am on version 0.8.0 and 1.20.x K8 version

**Comment by ArthurSens** [comment]
You can modify your jsonnet file to not output the alertmanager manifests. There are several ways to do that, but using the [example.jsonnet](https://github.com/prometheus-operator/kube-prometheus/blob/main/example.jsonnet) file we have in this repository. Alertmanager can be removed by deleting line 27.


I'm not sure if that is what you are asking, please let me know if you need extra guidance

**Comment by sunilthemaster** [comment]
@ArthurSens : Thanks for the response.

I actually did that but then my prometheus is continuously throwing errors for unable to connect to alert manager.

**Comment by paulfantom** [comment]
For that you need to remove `values.prometheus.prometheus.spec.alerting: {}`

**Comment by sunilthemaster** [comment]
Ok. Will give it a try and confirm

**Comment by sunilthemaster** [comment]
Able to get it work. Alertmanager config are still coming but that's easy to remove.
Thanks
