### ISSUE TITLE
KubeMemoryOvercommit always return empty sets at prometheus /graph

### ISSUE THREAD

**Issue by teochenglim** [prometheus-operator/kube-prometheus#1254]
**What happened?**

is the memory overcommited (KubeMemoryOvercommit) a bug?

This always return a empty result

```yaml
(sum(namespace:kube_pod_container_resource_requests_memory_bytes:sum)
        /
      sum(kube_node_status_allocatable_memory_bytes)) >  ((count(kube_node_status_allocatable_memory_bytes)-1)
        /
      count(kube_node_status_allocatable_memory_bytes))

```

This will return a %

```yaml
(sum(namespace:kube_pod_container_resource_requests_memory_bytes:sum)
        /
      sum(kube_node_status_allocatable_memory_bytes))
```

This will also return a %

```yaml
 ((count(kube_node_status_allocatable_memory_bytes)-1)
        /
      count(kube_node_status_allocatable_memory_bytes))
```

**Did you expect to see some different?**
Should return true/false?

**How to reproduce it (as minimally and precisely as possible)**:
just helm install it

**Environment**
EKS (helm install kube-prometheus-stack-13.5.1)

**Anything else we need to know?**:

**Comment by paulfantom** [comment]
This repository is not shipping helm charts, in the future please provide kube-prometheus branch that was used to deploy the stack.

---

The current version of the alert is using different expressions to match metric names change in kube-state-metrics v2. Plus it is using suggestions from this bug report. Here is a new expression: https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/kubernetes-prometheusRule.yaml#L263-L278

I am closing this as the alert works correctly when a stack is deployed from code in the repository.
