### ISSUE TITLE
How to remove the prefix of the prometheus pod name on kube-prometheus-stack of helm chart?

### ISSUE THREAD

**Issue by duanrex** [prometheus-operator/kube-prometheus#1258]
When deploying prometheus, the pod name after the deployment is always automatically prefixed with "prometheus". 

How can I remove this prefix? 

such as : 
fullnameOverride: "test-prometheus"

pod name: prometheus-test-prometheus.

Thanks

**Comment by paulfantom** [comment]
You cannot. Pods are managed by StatefulSet which in turn is managed by prometheus-operator and the prefix value is embedded in operator code - https://github.com/prometheus-operator/prometheus-operator/blob/a343487a14ddaff9666cd7c2e30ac16fa3a6d3fe/pkg/prometheus/statefulset.go#L919-L921
