### ISSUE TITLE
when I open the UI of grafana,it works,while I init one of dashboard,for example node,every module has no data and bad gateway

### ISSUE THREAD

**Issue by only21tender** [prometheus-operator/kube-prometheus#1263]
when I open the UI of grafana,it works,while I init one of dashboard,for example node,every module has no data and bad gateway

_Originally posted by @only21tender in https://github.com/prometheus-operator/kube-prometheus/discussions/1262_

**Comment by only21tender** [comment]
![QQ截图20210719213709](https://user-images.githubusercontent.com/76042941/126168884-efa8b57b-feb2-4787-9e26-8952b4cd4ce4.png)
![QQ图片20210719213636](https://user-images.githubusercontent.com/76042941/126168889-93fb2b3f-a3b8-439c-b825-af99840e58ce.png)

**Comment by Planck0591** [comment]
did you find any solution for this problem?
