### ISSUE TITLE
How to add provisioned notifiation channel for grafana in kube-prometheus-stack

### ISSUE THREAD

**Issue by Eljah** [prometheus-operator/kube-prometheus#1269]
Hi!

I'm in stuck with any examples how to set up the grafana notification channel via yaml files on the manner it is done for the custom provisioned dashboards. Currently the dashboard just mention the notification channels ids, so we need the way to set up the notification channels explicitly.  Grafana documentation refers this

https://grafana.com/docs/grafana/latest/administration/provisioning/#alert-notification-channels

but it is not clear how to use this for kube-prometheus-stack chart files structure

**Comment by paulfantom** [comment]
Please do create discussions and issues at the same time. It only creates unnecessary spam.

Closing as there is discussion in https://github.com/prometheus-operator/kube-prometheus/discussions/1271
