### ISSUE TITLE
Port-forward requests mess up API success rate

### ISSUE THREAD

**Issue by gmaiztegi** [prometheus-operator/kube-prometheus#1302]
**What happened?**

We are currently having KubeAPIErrorBudgetBurn alerts in our cluster, and our Grafana chart show pretty clearly that there are many read requests targeting pods that run for exactly 60 seconds.

![Screenshot 2021-08-02 at 15 51 14](https://user-images.githubusercontent.com/753673/127872510-1e904b75-2d53-4f26-95f8-e3108d95999f.png)

After some digging and running this query `cluster_quantile:apiserver_request_duration_seconds:histogram_quantile{resource="pods", cluster=""}` we see that it is the portforward request that takes longer than what the SLO specifies.

![Screenshot 2021-08-02 at 15 39 40](https://user-images.githubusercontent.com/753673/127871527-a38d7e05-309f-4eae-9202-18fd87aefdb2.png)

But it seems to me that port-forwards should be long running operations by definition.

**Did you expect to see some different?**

As port-forwards are long running operations, it seems to me that it makes sense to take them out when calculating the aggregated success rate for the API resources.

**How to reproduce it (as minimally and precisely as possible)**:

Run a bunch of port-forwards in a non-busy cluster. In our case, our developers connect to the development environment and many use [Kube Forwarder](https://kube-forwarder.pixelpoint.io/).

**Environment**

* Prometheus Operator version:

    `v0.49.0`

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:58:09Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-eks-6b7464", GitCommit:"6b746440c04cb81db4426842b4ae65c3f7035e53", GitTreeState:"clean", BuildDate:"2021-03-19T19:33:03Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

AWS EKS

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
Insert Prometheus Operator logs relevant to the issue here
```

* Prometheus Logs:

```
Insert Prometheus logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by paulfantom** [comment]
The alert comes as-is from [kubernetes-mixin project](https://github.com/kubernetes-monitoring/kubernetes-mixin), please open an issue there.

**Comment by gmaiztegi** [comment]
Thanks @paulfantom and sorry for bothering you here. I opened an issue there: https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/652.
