### ISSUE TITLE
Grafana dashboard manifests partially missing uid fields

### ISSUE THREAD

**Issue by clux** [prometheus-operator/kube-prometheus#1333]
The manifest file [grafana-dashboardDefinitions](https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/grafana-dashboardDefinitions.yaml) used by [`kube-prometheus-stack`](https://github.com/prometheus-community/helm-charts/blob/698ff948e24d5da788ac23ea54a258bad276984b/charts/kube-prometheus-stack/hack/sync_grafana_dashboards.py#L29) pins raw `uid` fields for upstream.

**Problem**

The following 3 dashboards set `"uid": ""` instead:

- `node-cluster-rsrc-use`
- `node-rsrc-use`
- `prometheus`

**Did you expect to see some different?**

It would be good for consistency that we have the unique identifier in there. Currently it's hard to use these dashboards [in a HA grafana setup because they get different uids per pod](https://grafana.com/docs/grafana/latest/http_api/dashboard/#identifier-id-vs-unique-identifier-uid) and refreshes might suddenly return 404s. It's also impossible to link to these dashboards from other dashboards while the `uid` is unset.

Relevant upstream bug: https://github.com/prometheus-community/helm-charts/issues/1042

**Comment by ArthurSens** [comment]
Kube-prometheus imports dashboards from mixins developed in other projects.

`node-cluster-rsrc-use` and `node-rsrc-use` come from [node-exporter mixin](https://github.com/prometheus/node_exporter/tree/master/docs/node-mixin/dashboards) and `prometheus` comes from [prometheus-mixin](https://github.com/prometheus/prometheus/blob/main/documentation/prometheus-mixin/dashboards.libsonnet).

Do you mind opening an issue or a PR regarding this problem in their respective repository?

**Comment by clux** [comment]
Ah, right. I didn't realise they weren't from here. Thank you.
I will open issues on the more relevant repos!

**Comment by joelsdc** [comment]
Hi @clux, I've run into this same problem, do you mind sharing if/how you solved it?

**Comment by clux** [comment]
hah, sure, but you probably wont like the method 😅 

```sh
  nodeclusterfile="promstack/charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/node-cluster-rsrc-use.yaml"
  NODECLUSTER="$(cat ${nodeclusterfile} | yq '.data["node-cluster-rsrc-use.json"]' -r | jq '.uid = "mixin-cluster-use"' -c)"
  sed -i '$ d' "${nodeclusterfile}"
  echo "    ${NODECLUSTER}" >> ${nodeclusterfile}
```

which uses `yq` (python-yq or whyq) + `jq` to modify the inline json and set a consistent `uid` property, and then `sed` to replace that one line in the same file..

**Comment by joelsdc** [comment]
My case:

- I install using Terraform + Helm. 
- The result is: I have a configmap with the dashboard which I later use as provisioning source for grafana. 

One thing I tried was to set the uid in the configmap directly (similar to what you are doing), but instead of that fixing it, it later gave me a different kind of error. 

I'm going to test with your solution and compare to mine. 

Thank you for sharing!
