### ISSUE TITLE
serviceMonitor/monitoring/node-exporter/0 (0/3 up) fail

### ISSUE THREAD

**Issue by wawe123** [prometheus-operator/kube-prometheus#1335]
Prometheus   serviceMonitor/monitoring/node-exporter/0 (0/3 up)   fail

Error  Get "https://192.168.xx.xx:9100/metrics": context deadline exceeded

**Comment by wawe123** [comment]
![image](https://user-images.githubusercontent.com/45084760/129777992-63918092-2bd2-44cb-9ae3-1cfba5464686.png)

**Comment by ArthurSens** [comment]
If you exec into your prometheus container, are you able to communicate with the node-exporter containers? e.g, by trying to hit their /metrics endpoint.

**Comment by jovalle** [comment]
*bump*

Still an issue. Can reach from host itself (e.g. `curl -vvk https://localhost:9100/metrics`) but not from any other host. Restarting the node-exporter pod a few times (and waiting 10-15min) can fix the issue but of course this is not a permanent fix.

![image](https://user-images.githubusercontent.com/47045210/174901102-6242c1a0-99fb-42cd-8465-3119ff532e4d.png)

Can confirm ports are listening via `netstat tulpn` and expect 401s when reaching the `/metrics` but requests instead hang. 
```
# netstat -tulpn | grep 9100
tcp        0      0 192.168.1.21:9100       0.0.0.0:*               LISTEN      2541136/kube-rbac-p
tcp        0      0 127.0.0.1:9100          0.0.0.0:*               LISTEN      2541078/node_export
```

Using Cilium as the CNI, network policies disabled.
