### ISSUE TITLE
The Prometheus-Adapter cannot run properly in the Kubernetes binary environment. You need to add the hostNetwork parameter

### ISSUE THREAD

**Issue by XzBuleSky** [prometheus-operator/kube-prometheus#1336]
Hello ! The Prometheus-Adapter cannot run properly in the Kubernetes binary environment. You need to add the hostNetwork parameter

**What happened?**
When `kube-prometheus` is installed in the Kubernetes binary environment, the `Prometheus-adapter` fails to run properly.
```
# kubectl get apiService v1beta1.metrics.k8s.io
v1beta1.metrics.k8s.io                  monitoring/prometheus-adapter   False (FailedDiscoveryCheck)   44m
```
```
# kubectl get  --raw "/apis/metrics.k8s.io/v1beta1"
Error from server (ServiceUnavailable): the server is currently unable to handle the request
```
```
# kubectl top nodes
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get nodes.metrics.k8s.io)
```

**Proposal**
I'm looking for an answer that might be: `kube-apiserver`(master) must normally access `Prometheus-Adapter Pod IP`.
But since my Kubernetes is a binary environment, the master will not be able to access the `Prometheus-Adapter POD IP` unless the `master` installs the network plug-in.
I don't want the master to install network plug-ins. I tried another approach by adding the hostNetwork parameter in Deployment so that the Master can access the `POD  #IP`.

I modify `main.libsonnet` and `Components/Prometheus -adapter.libsonnet`  . 
> Please see the [add hostNetwork](https://github.com/prometheus-operator/kube-prometheus/commit/e9f87727701d4a0eb631d886b3ac637dee114f2a?branch=e9f87727701d4a0eb631d886b3ac637dee114f2a&diff=unified)

> example.jsonnet
```
local kp =
    (import 'kube-prometheus/main.libsonnet') +
    {
        values+:: {
            prometheusAdapter+{
                hostNetwork: true,
            },
        };
    }

```

> Re-apply `Prometheus-Adapter` YAML to check whether the test is normal:
```
# kubectl get apiService v1beta1.metrics.k8s.io
v1beta1.metrics.k8s.io   monitoring/prometheus-adapter   True   12h
```
```
# kubectl get  --raw "/apis/metrics.k8s.io/v1beta1"
{"kind":"APIResourceList","apiVersion":"v1","groupVersion":"metrics.k8s.io/v1beta1","resources":[{"name":"nodes","singularName":"","namespaced":false,"kind":"NodeMetrics","verbs":["get","list"]},{"name":"pods","singularName":"","namespaced":true,"kind":"PodMetrics","verbs":["get","list"]}]}
```
```
# kubectl top nodes
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get nodes.metrics.k8s.io)
```

`apiService v1beta1.metrics.k8s.io` is working properly, but why is the service still not working properly?

> View the logs of `Prometheus-Adapter`
```
.....
dial tcp: lookup prometheus-k8s.monitoring.svc.cluster.local on 100.100.2.136:53: no such host
```
That ` Prometheus-Adapter ` need access to `prometheus-k8s.monitoring.svc.cluster.local`, unable to properly use `coredns` access inside the cluster node node.

I came up with a temporary solution, Add `coredns` IP to `/etc/resolv.conf `
```
# cat /etc/resolv.conf
nameserver 10.254.0.2
```

```
# kubectl top nodes
NAME                      CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
node02.xxxx   154m         7%     1532Mi          42%       
node03.xxxx   259m         12%    2121Mi          58%      
```

**Environment**
* kube-prometheus:    main ( Releasess 0.9???)
* kubernetes  :  Kubernetes v1.20.8 Binary environment

**Comment by paulfantom** [comment]
What's a `Kubernetes binary environment`?
