### ISSUE TITLE
Adding additional scrape config for a target outside the kubernets cluster

### ISSUE THREAD

**Issue by CSRaghunandan** [prometheus-operator/kube-prometheus#1358]
I deployed kube-prometheus in a cluster. Would it be possible to monitor, say an IoT device which is running 'fluent-bit' with node-exporter plugin (which should be scrap-able by prometheus) ?

This IoT device will be running inside the same LAN as the kuberentes cluster where kube-prometheus is deployed.

I know that we can configure `prometheus-operator` with additional scrape configs as shown here: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/additional-scrape-config.md

But how can we do that with kube-prometheus?

**Comment by paulfantom** [comment]
@mac-chaffee I am a bit surprised that this works :D Personally I used a Service object without selectors and created Endpoints object for it manually ([like here](https://github.com/thaum-xyz/ankhmorpork/tree/master/apps/homeassistant/manifests/esphomedevices)). But it seems that your solution would be much easier to manage! Kudos to you. 

It seems to me that with your tip, we should rewrite how we handle adding windows hosts as Service with ExternalName should be easier to implement than [what we have right now](https://github.com/prometheus-operator/kube-prometheus/blob/main/jsonnet/kube-prometheus/addons/windows.libsonnet#L58-L68).
