### ISSUE TITLE
How can I update node-exporter configuration(args)?

### ISSUE THREAD

**Issue by rajaSahil** [prometheus-operator/kube-prometheus#1374]
I want to update node-exporter configuration i.e `--collector.filesystem.ignored-mount-points` which is being passed through args.

node-exporter-daemonset.yaml
```
spec:
      containers:
      - args:
        . . .
        - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/pods/.+)($|/)
        . . .
```

### Issue:
This configuration is being formed using a local variable and I am not able to update it. Is there a way to update this configuration?
https://github.com/prometheus-operator/kube-prometheus/blob/eeb7c7125d6a01b60375cab4f66289acdac213eb/jsonnet/kube-prometheus/components/node-exporter.libsonnet#L174

```
daemonset:
    local nodeExporter = {
      name: ne._config.name,
      image: ne._config.image,
      args: [
        '--web.listen-address=' + std.join(':', [ne._config.listenAddress, std.toString(ne._config.port)]),
        '--path.sysfs=/host/sys',
        '--path.rootfs=/host/root',
        '--no-collector.wifi',
        '--no-collector.hwmon',
        '--collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/pods/.+)($|/)',
        // NOTE: ignore veth network interface associated with containers.
        // OVN renames veth.* to <rand-hex>@if<X> where X is /sys/class/net/<if>/ifindex
        // thus [a-z0-9] regex below
        '--collector.netclass.ignored-devices=^(veth.*|[a-f0-9]{15})$',
        '--collector.netdev.device-exclude=^(veth.*|[a-f0-9]{15})$',
      ],
      volumeMounts: [
        { name: 'sys', mountPath: '/host/sys', mountPropagation: 'HostToContainer', readOnly: true },
        { name: 'root', mountPath: '/host/root', mountPropagation: 'HostToContainer', readOnly: true },
      ],
      resources: ne._config.resources,
    };
```

**Comment by ArthurSens** [comment]
You can customize your deployment by modifying the jsonnet file that consumes the kube-prometheus library. One example would be:

```jsonnet
local kp =
  (import 'kube-prometheus/main.libsonnet') +
  {
    values+:: {
      nodeExporter+: {
        args+: ['--collector.filesystem.ignored-mount-points=/tmp'],
      },
    },
  };
{ ['node-exporter-' + name]: kp.nodeExporter[name] for name in std.objectFields(kp.nodeExporter) } 
```

**Comment by ArthurSens** [comment]
One approach is to override all args completely. That would mean that you'd need to pass all args that are there but didn't mean to change. You'd need to Map the container spec inside the deamonset and change args `if container.name == 'node-exporter'`

I completely agree that this is not the best experience, but I'm curious why would you need to change this. Looking that you linked this issue to an issue in OpenEBS... Does monitoring nodes running OpenEBS require some modifications? (I'm am a complete newbie with OpenEBS)

**Comment by rajaSahil** [comment]
> One approach is to override all args completely. That would mean that you'd need to pass all args that are there but didn't mean to change. You'd need to Map the container spec inside the deamonset and change args `if container.name == 'node-exporter'`
> 
This approach looks great but I think it's a bit complex. Can't we make this argument configurable?
> I completely agree that this is not the best experience, but I'm curious why would you need to change this. Looking that you linked this issue to an issue in OpenEBS... Does monitoring nodes running OpenEBS require some modifications? (I'm am a complete newbie with OpenEBS)

OpenEBS is an open-source storage solution for Kubernetes. It is an Open Source Container Attached Storage, built using Cloud Native Architecture, simplifies running Stateful Applications on Kubernetes. 
To learn more about OpenEBS, please refer to the [official document](https://openebs.io/docs/).

Yes, there is a use case in OpenEBS, where we want to monitor filesystem stats for which we have updated the configuration of node-exporter to enable metrics collection related to the filesystem mounted at `/var/lib/kubelet/...`. 

Kubelet by-default mount volumes at path `/var/lib/kubelet/...` and to get metrics of filesystem mounted at this path, we need to update the configuration of node-exporter. 
Metrics used: [Dashboard](https://github.com/openebs/monitoring/blob/915a6b2507cd9757aa12ab6e6d145759aa3efa2a/jsonnet/openebs-mixin/dashboards/openebs/localpv-workload.json#L1841)

**Comment by paulfantom** [comment]
Closing as support for this was implemented in https://github.com/prometheus-operator/kube-prometheus/pull/1376
