### ISSUE TITLE
How to change the flags and config?

### ISSUE THREAD

**Issue by grjiq** [prometheus-operator/kube-prometheus#138]
**What did you do?**
Now i want to backup the data of prometheus in 2 ways.

1. snapshot. In this way i must start prometheus with the flag ```--web.enable-admin-api```, I dont know where to add the flag in manifests/*.yaml。
2. remote storage. In this way i have to add ```remote_write/remote_read``` in prometheus.yml, what should i do?

**Did you expect to see some different?**
NO
**Environment**
ubuntu
* Prometheus Operator version:
prometheus-operator:v0.29.0

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.5-tke.4", GitCommit:"dfd21a56c282a100bf92bddc04fddc7dee6beb0d", GitTreeState:"clean", BuildDate:"2019-03-21T02:41:07Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:

  kubectl

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
Nothing
```

* Prometheus Logs:

```
Nothing
```

**Anything else we need to know?**:
No

**Comment by brancz** [comment]
Both of these cases can be found in the API docs :) https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md

**Comment by grjiq** [comment]
I am new to k8s & prometheus, if i want to add the config `remote_read`, am i just edit the configuration file ```0prometheus-operator-0prometheusCustomResourceDefinition.yaml``` like this?
`                  remoteTimeout:
                    description: Timeout for requests to the remote read endpoint.
                    type: string
                  requiredMatchers:
                    description: An optional list of equality matchers which have 
                      to be present in a selector to query the remote read endpoint.
                    type: object
                  tlsConfig:
                    description: TLSConfig specifies TLS configuration parameters.
                    properties:
                      caFile:
                        description: The CA cert to use for the targets.
                        type: string
                      certFile:
                        description: The client cert file for the targets.
                        type: string
                      insecureSkipVerify:
                        description: Disable target certificate validation.
                        type: boolean
                      keyFile:
                        description: The client key file for the targets.
                        type: string
                      serverName:
                        description: Used to verify the hostname for the targets.
                        type: string
                  url: 
                    description: The URL of the endpoint to send samples to.
                    type: string
                    **value: "http://192.168.89.41:9201/read"**                                                                                                                                                       
                required:
                - url
              type: array
`

**Comment by brancz** [comment]
That's the customresourcedefinition, you want to change this file https://github.com/coreos/kube-prometheus/blob/master/manifests/prometheus-prometheus.yaml

**Comment by paulfantom** [comment]
Closing due to staleness. Please reopen if you think this is still relevant.
