### ISSUE TITLE
grafana can't connect prometheus svc

### ISSUE THREAD

**Issue by sanger89** [prometheus-operator/kube-prometheus#142]
![image](https://user-images.githubusercontent.com/35362585/60865236-3ade9c00-a258-11e9-9648-1fcfb53d7f9c.png)
![image](https://user-images.githubusercontent.com/35362585/60865149-fce17800-a257-11e9-8d8c-6420de698777.png)
![image](https://user-images.githubusercontent.com/35362585/60865566-dbcd5700-a258-11e9-9092-bf42abf5dbf8.png)
anyone know why?

**Comment by metalmatze** [comment]
What's the full URL you have in your Grafana datasource? 
However, this mostly looks like a problem with your cluster and not Grafana / Prometheus.

**Comment by sanger89** [comment]
> What's the full URL you have in your Grafana datasource?
> However, this mostly looks like a problem with your cluster and not Grafana / Prometheus.

The full URL is "http://prometheus-k8s.monitoring.svc:9090"
This URL is automatically generated by the configuration file and cannot be modified

But my Prometheus UI is normal and accessible

**Comment by Quicksy** [comment]
@sanger89 I am having the same problem. Did you managed to fix this?

**Comment by nemodev** [comment]
I had a same issue. My case was because the actual prometheus pods weren't created, but only the service. Look at your pod list and make sure the prometheus-k8s-x pods are created. 

The reason why those pods were not created for me, was that I skipped below line for the installation.
`kubectl create -f manifests/setup`

**Comment by druanoor** [comment]
I'm having the same problem.

I've managed to connect it by proxying both services and then adding a new datasource that points to my localhost with access configured as "Browser" but thats a workaround.

Did anyone found a solution?

**Comment by jvanmalder** [comment]
I was having the same issue, and changing the URL to "http://prometheus-operated.monitoring.svc:9090" fixed it.
