### ISSUE TITLE
How to setup dynamic Alert manager in prometheus ??

### ISSUE THREAD

**Issue by desinenisuresh** [prometheus-operator/kube-prometheus#1434]
Hi Team,
I have installed kube-prometheus-stack for monitoring k8s . But In the Alert manager I configured smtp for sending mails its working fine and sending emails also . But I am unable to send alerts in dynamic way in alert manager.

Dynamic alert means
reference: https://www.robustperception.io/using-labels-to-direct-email-notifications

I'm going to presume you already have a working email notification setup, such as was shown previously with Gmail.

We start at Prometheus. We'll need to get the target email address into an alert label. Let's say you have constructed time series looking like:

```
mymetric{job="myjob",email_to="foo@example.org",instance="host1"}
mymetric{job="myjob",email_to="bar@example.org",instance="host2"}
```

Then you can write an alert which propagates this email_to label such as:
```
groups:

name: test.rules
rules:
alert: MyAlert
expr: mymetric > 1
================================
route:
group_by: [email_to]
receiver: email_router

receivers:

name: email_router
email_configs:
to: "{{ .GroupLabels.email_to }}"
from: XXXXXXX
```
Add whatever other settings you need to talk to your SMTP server
```
headers:
subject: "You have {{ .Alerts.Firing | len }} firing alerts"
html: |
Hi {{ .GroupLabels.email_to }},

You have the following firing alerts:

{{ range .Alerts }}
{{.Labels.alertname}} on {{ .Labels.instance }}
{{ end }}
```

### 
**_please suggest me how can I achieve this in kube-prometheus-stack ??_**

**Comment by yeya24** [comment]
This seems a configuration question about alertmanager. Does it relate to kube-prometheus?
