### ISSUE TITLE
How to do Metrics Archival from prometheus ??

### ISSUE THREAD

**Issue by desinenisuresh** [prometheus-operator/kube-prometheus#1435]
prometheus  collect metrics form all scrape configs but I want to do **### Metrics Archival** here .Is  It possible here ??

Please assist on this , if any possible is there means.
provide the links

**Comment by desinenisuresh** [comment]
Yes, I agree but I am using ebs storage form there how to archival storage
and reuse the data?? How its happen ..

**Comment by nikhil-nomula** [comment]
Where do we configure the remote_write option

**Comment by desinenisuresh** [comment]
I didn't configure anything  can you guide on this.. where I want to add
this things... Please help on this..

**Comment by PhilipGough** [comment]
Remote Write can be configured in the `Prometheus` resource as per https://github.com/prometheus-operator/prometheus-operator/blob/c0baa01acd516ffc26fe8cd5763c0eaa0cd93c88/Documentation/api.md#remotewritespec

As @paulfantom mentioned, kube-prometheus does not provide a pre-configured option for this.

**Comment by jgehrcke** [comment]
> Where do we configure the remote_write option

Related: https://github.com/prometheus-operator/kube-prometheus/issues/1998
