### ISSUE TITLE
grafanaImage change breaks when repository on custom port

### ISSUE THREAD

**Issue by vanveele** [prometheus-operator/kube-prometheus#1439]
**What happened?**

Change introduced in [PR](https://github.com/prometheus-operator/kube-prometheus/pull/1125) breaks when parsing image repositories which are using custom ports.
Images of the form `dockerrepo.example.com:5000/grafana/grafana:8.1.1` are incorrectly parsed and result in a deployment manifest with `image: dockerrepo.example.com:8.1.1`
The change is splitting on all ':' characters (line 46) and selecting the first field. Correct parsing would split on the right-most ':' and then select the first field.

**Did you expect to see some different?**

A properly parsed image value would result in a deployment with `image: dockerrepo.example.com:5000/grafana/grafana:8.1.1` 

**How to reproduce it (as minimally and precisely as possible)**:

```
local kp = 
  (import 'kube-prometheus/main.libsonnet') +
  {
    values+:: {
      common+: {
        images+:: {
          grafana: 'dockerrepo.example.com:5000/grafana/grafana:8.1.1',
        },
      },
    },
  }

kp.grafana['deployment']
```

**Environment**

* Prometheus Operator version:

    release-0.9
    

* Kubernetes version information:

    v0.49.0
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
local kp =
  (import 'kube-prometheus/main.libsonnet') +
  {
    values+:: {
      common+: {
        images+:: {
          grafana: 'dockerrepo.example.com/grafana/grafana:8.1.1',
        },
      },
    },
  };

kp.grafana["deployment"]
```

* Prometheus Operator Logs:

N/A

* Prometheus Logs:

N/A

**Anything else we need to know?**:

**Comment by vanveele** [comment]
An inelegant but functional fix:

```
      imageRepos+:: {
        grafana: std.join(":", (std.reverse(std.reverse(std.split(g._config.image, ':'))[1:]))),
      },
```

**Comment by PhilipGough** [comment]
Closing since #1450 has merged
