### ISSUE TITLE
cannot get cluster in "Kubernetes / USE Method / Node" Dashboard with "label_values(kube_node_info, cluster)"

### ISSUE THREAD

**Issue by kooyear** [prometheus-operator/kube-prometheus#145]
**What happened?**
I try to use grafana to display data from Prometheus to monitor Kubernetes cluster in "Kubernetes / USE Method / Node" Dashboard. But when I found I cannot get the cluster variable with "label_values(kube_node_info, cluster)"

**Did you expect to see some different?**

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
Insert Prometheus Operator logs relevant to the issue here
```

* Prometheus Logs:

```
Insert Prometheus logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by brancz** [comment]
Could you give us more information on what you did, what you expected to see, and what you saw instead?

**Comment by paulfantom** [comment]
Closing due to staleness. Please reopen if you think this is still relevant.
