### ISSUE TITLE
jsonnet-bundler used is dead?

### ISSUE THREAD

**Issue by KlavsKlavsen** [prometheus-operator/kube-prometheus#1512]
To compile my own prometheus - I need to install jb.
However - the jb projects documented way to install - no longer works as of GO 1.17 - and project is obviously inactive/dead :(

issue about this problem in jb: https://github.com/jsonnet-bundler/jsonnet-bundler/issues/148

Are there alternatives - that perhaps are more active, or ?

I'll install jb from master and compile instead.. but :(

**Comment by paulfantom** [comment]
The project is not dead. The installation method is just not updated to be compliant with go 1.17. Try `go install -a github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb@latest`

**Comment by KlavsKlavsen** [comment]
Here's to hoping my PR to fix this gets merged then :)

**Comment by paulfantom** [comment]
I left this issue open as we are also referencing how to install `jb` in our docs (https://github.com/prometheus-operator/kube-prometheus#update-jb).

**Comment by KlavsKlavsen** [comment]
@paulfantom fixed docs - I changed to defaulting to 'main' instead of release-0.9 as I understood you felt was the correct one to default to.
