### ISSUE TITLE
prometheus 2.30.3 failing with prometheus-operator v0.52.1 

### ISSUE THREAD

**Issue by pr0PM** [prometheus-operator/kube-prometheus#1529]
**What is missing?**
Support for latest prometheus-operator v0.52.1

**Why do we need it?**
To setup AWS Prometheus we need the prometheus-operator >= v0.52 for sigv4 to work properly as discussed [here](https://github.com/prometheus-operator/prometheus-operator/discussions/4339)

**Environment**
EKS 1.21.x

* kube-prometheus version: 0.52.1
* Chart version: 20.0.1
* Prometheus version: v2.30.3

    `Insert Git SHA here`

**Anything else we need to know?**:
We are using the latest *kube-prometheus-stack* charts (as of now) to deploy Prometheus and tools on our k8s cluster.
To use AWS Managed Prometheus we need the latest version of prometheus-operator.
So we updated the prometheus-operator image from v0.48.1 (in current charts) to 0.52.1 (the latest we have)

This broke prometheus with error message as shown below (even the debug logs didn't reveal anything more here):
```
prometheus level=info ts=2021-11-29T15:11:01.317Z caller=main.go:906 msg="Notifier manager stopped"                                                                                                      
prometheus level=error ts=2021-11-29T15:11:01.317Z caller=main.go:915 err="error loading config from \"/etc/prometheus/config_out/prometheus.env.yaml\": one or more errors occurred while applying the  
new configuration (--config.file=\"/etc/prometheus/config_out/prometheus.env.yaml\")"                                                                                                                    
```

**Comment by paulfantom** [comment]
Did you update CRDs?

**Comment by pr0PM** [comment]
Yes, just verified once again, all CRDs are the ones that we have with the latest charts. `controller-gen.kubebuilder.io/version: v0.6.2`

**Comment by paulfantom** [comment]
`controller-gen.kubebuilder.io/version: v0.6.2` label is not identifying which CRDs are provisioned.

kubePrometheusStack v20 does not ship the latest CRDs (afaik it ships ones that are related to prometheus-operator 0.50) and field for handling sig v4 is missing there.

**Comment by pr0PM** [comment]
After updating kubePrometheusStack Charts to v21 it's working fine so closing this, thanks everyone.
