### ISSUE TITLE
Prometheus operator always raising KubeControllerManagerDown or KubeSchedulerDown

### ISSUE THREAD

**Issue by woody3549** [prometheus-operator/kube-prometheus#1531]
Hello,

I currently have two alerts raising because of a "Target disappeared from Prometheus target discovery".
Alertnames are KubeControllerManagerDown and KubeSchedulerDown.

My current configuration is GKE v1.19.16-gke.1500 and kube-prometheus-stack 20.0.1.
Can you please let me know what could be the reason ?
Is anyway I could mute these alerts ?

Thanks

**Comment by paulfantom** [comment]
Consider using `platform: gke` as described in https://github.com/prometheus-operator/kube-prometheus/blob/main/docs/customizations/platform-specific.md. This will apply all necessary configurations needed for the stack to be running on GKE, including handling of alerts you mentioned.

**Comment by woody3549** [comment]
Hello Pawel,

Currently, I am using an helm chart as follows:
```
- name: prometheus-operator # see: https://github.com/coreos/prometheus-operator
    chart: prometheus-community/kube-prometheus-stack
    version: 20.0.1
    namespace: monitoring
    waiting: true
```

Do you mean adding a `platform: gke` parameter be sufficient, please ?

Thanks

**Comment by paulfantom** [comment]
We don't ship helm chart. I think you meant this project: https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack

**Comment by woody3549** [comment]
Yes, exactly.
Where do I need to put such parameter ?

Thanks

**Comment by paulfantom** [comment]
I don't think helm charts allow such parameter. It would be best to ask folks maintaining helm charts.

**Comment by tangjizhou** [comment]
After I changed `port: https-metrics` to  in `port: http-metrics` prometheus-serviceMonitorKubeControllerManager.yaml , all targets appeared.
