### ISSUE TITLE
Error message "field matchers not found in type alertmanager.route"

### ISSUE THREAD

**Issue by trestea** [prometheus-operator/kube-prometheus#1532]
Kubernetes：v1.20.12
kube-prometheus: 0.8
alertmanager: v0.23.0
Use the kube-prometheus-0.8 branch, update the alertmanager version to 0.23.0 and modify the alertmanager configuration file to add matchers, the error message is as follows:

level=error ts=2021-12-01T11:34:47.626780871Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="Sync \"monitoring/main\" failed: provision alertmanager configuration: base config from Secret could not be parsed: yaml: unmarshal errors:\n  line 33: field matchers not found in type alertmanager.route"

**Comment by paulfantom** [comment]
Looks like your alertmanager configuration is incorrect, can you share alertmanager Secret and jsonnet configuration?

**Comment by trestea** [comment]
apiVersion: v1
kind: Secret
metadata:
  labels:
    alertmanager: main
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.22.2
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m
    inhibit_rules:
    - equal:
      - namespace
      - alertname
      source_match:
        severity: critical
      target_match_re:
        severity: warning|info
    - equal:
      - namespace
      - alertname
      source_match:
        severity: warning
      target_match_re:
        severity: info
    receivers:
    - name: Default
    - name: Watchdog
    - name: Critical
    route:
      group_by:
      - namespace
      group_interval: 5m
      group_wait: 30s
      receiver: Default
      repeat_interval: 12h
      routes:
      - match:
          alertname: Watchdog
        receiver: Watchdog
      - matchers:
        - severity="critical|warning|info"
        - namespace!="dev|ci"
        receiver: Critical
type: Opaque

**Comment by trestea** [comment]
> Looks like your alertmanager configuration is incorrect, can you share alertmanager Secret and jsonnet configuration?

apiVersion: v1
kind: Secret
metadata:
  labels:
    alertmanager: main
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.22.2
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m
    inhibit_rules:
    - equal:
      - namespace
      - alertname
      source_match:
        severity: critical
      target_match_re:
        severity: warning|info
    - equal:
      - namespace
      - alertname
      source_match:
        severity: warning
      target_match_re:
        severity: info
    receivers:
    - name: Default
    - name: Watchdog
    - name: Critical
    route:
      group_by:
      - namespace
      group_interval: 5m
      group_wait: 30s
      receiver: Default
      repeat_interval: 12h
      routes:
      - match:
          alertname: Watchdog
        receiver: Watchdog
      - matchers:
        - severity="critical|warning|info"
        - namespace!="dev|ci"
        receiver: Critical
type: Opaque

**Comment by paulfantom** [comment]
> app.kubernetes.io/version: 0.22.2

That's not alertmanager 0.23.0. If you are using lower version your `matchers` configuration needs to be amended, I mean this one:
```

**Comment by PhilipGough** [comment]
Also, note that support for non -deprecated match syntax was only added in https://github.com/prometheus-operator/prometheus-operator/pull/4309 - what version of prometheus-operator are you running?

**Comment by trestea** [comment]
> > app.kubernetes.io/版本：0.22.2
> 
> 那不是alertmanager 0.23.0。如果你使用的是低版本你的`matchers`配置需要修改，我的意思是这个部分：
> 
> ```
>       - matchers:
>         - severity="critical|warning|info"
>         - namespace!="dev|ci"
> ```

I directly replaced the mirror version of alertmanager to 0.23

According to the above environmental information, which release should I use, 0.8 or 0.9 or higher, and how should the configuration be configured

**Comment by trestea** [comment]
> 另请注意，仅在[prometheus-operator/prometheus-operator#4309 中](https://github.com/prometheus-operator/prometheus-operator/pull/4309)添加了对非弃用匹配语法的支持[](https://github.com/prometheus-operator/prometheus-operator/pull/4309)
> 
> 由于您说您正在运行`0.8`该映射到https://github.com/prometheus-operator/kube-prometheus/blob/release-0.8/manifests/setup/prometheus-operator-deployment.yaml#L30 `0.47.0`不包括增强。

According to the above environmental information, which release should I use for matchers, 0.8 or 0.9 or higher, and how to configure the configuration

**Comment by paulfantom** [comment]
You need to use prometheus-operator in version of at least 0.52.0 (with updated CRDs too) and alertmanager in version of at least 0.23.0. Those versions are by default only included on `main` branch and will be available in `release-0.10`.

If you need to use release branches, change your matchers configuration to one that is supported by the software version you are using (for `release-0.8` it would be https://github.com/prometheus-operator/kube-prometheus/blob/release-0.8/manifests/alertmanager-secret.yaml#L43-L48). Bear in mind that alertmanager 0.23 support old and new matchers.

**Comment by simonpasquier** [comment]
This is fixed in the latest operator version.
