### ISSUE TITLE
"prometheuses.monitoring.coreos.com" is invalid

### ISSUE THREAD

**Issue by vinzol** [prometheus-operator/kube-prometheus#1533]
The CustomResourceDefinition "prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes

**Comment by paulfantom** [comment]
Duplicate of https://github.com/prometheus-operator/kube-prometheus/issues/1511

Please use `kubectl apply --server-side`.

**Comment by freemankevin** [comment]
`kubectl apply --server-side -f bundle.yaml `

**Comment by freemankevin** [comment]
`kubectl apply --server-side -f bundle.yaml `
