### ISSUE TITLE
prometheus-adapter empty item list but successful HTTP request

### ISSUE THREAD

**Issue by NadhemMohamedRached** [prometheus-operator/kube-prometheus#1551]
**hello i have an issues 
i installed prometheus to make a custom metrics container_network_receive_bytes_total
but always i get an empty list of values** 
````{"kind":"MetricValueList","apiVersion":"custom.metrics.k8s.io/v1beta1","metadata":{"selfLink":"/apis/custom.metrics.k8s.io/v1beta1/namespaces/monitoring/pods/%2A/container_network_receive_bytes_per_second"},"items":[]}
here is the rule : 
    "rules":
      # seriesQuery is a Prometheus query on its own, we'll set up parameters below
      # container_network_receive_bytes_total is a metric provided to us as part of kube-prometheus
      - "seriesQuery": "container_network_receive_bytes_total"
        # resources overrides allows us to define parameters for our query
        "resources":
          "overrides":
            # define a `namespace` parameter, where the value is the namespace of the resource (pods for our HorizonalPodAutoscaler)
            "namespace":
              "resource": "namespace"
            # define a `pod` parameter, where the value is the name of the resource (pods for our HorizonalPodAutoscaler)
            "pod":
              "resource": "pod"
        # We want to scale pods due to a surge in traffic. A metric that is a total isn't great for this, but
        # we can see the rate of change using Prometheus' `rate`, which is a good metric to scale by
        # metricsQuery is Go templating with a few variables defined such as `.Series` being seriesQuery
        # and .LabelMatchers being parameters for our query
        "metricsQuery": 'sum(rate(<<.Series>>{id=~".*docker.*",<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)'
        # name allows us to modify the metric name given the seriesQuery
        # by default the name would be container_network_receive_bytes_total, which is misleading after our metricsQuery
        # produces a metric where we get bytes received per second
        "name":
          # matches allows to use capture groups to select the part of seriesQuery we want
          # in this case we're capturing everything before `_total` resulting in `container_network_receive_bytes`
          "matches": "^(.*)_total$"
          # as allows us to use our capture groups from `matches` and adjust as desired
          # in this case we're appending `_per_second` to `container_network_receive_bytes` resulting in `container_network_receive_bytes_per_second`
          "as": "${1}_per_second"
````
**Logs of adapter :**
````
adapter.go:101] successfully using in-cluster auth
I1214 18:26:48.199756       1 serving.go:325] Generated self-signed cert (/var/run/serving-cert/apiserver.crt, /var/run/serving-cert/apiserver.key)
E1214 18:26:48.475423       1 provider.go:227] unable to update list of all metrics: unable to fetch metrics for query "container_network_receive_bytes_total": Get "http://prometheus-k8s.monitoring.svc.cluster.local:9090/api/v1/series?match%5B%5D=container_network_receive_bytes_total&start=1639506347.454": dial tcp 10.3.4.19:9090: connect: connection refused
I1214 18:26:48.621499       1 secure_serving.go:197] Serving securely on [::]:6443
I1214 18:26:48.622023       1 requestheader_controller.go:169] Starting RequestHeaderAuthRequestController
I1214 18:26:48.622419       1 shared_informer.go:240] Waiting for caches to sync for RequestHeaderAuthRequestController
I1214 18:26:48.622527       1 dynamic_serving_content.go:130] Starting serving-cert::/var/run/serving-cert/apiserver.crt::/var/run/serving-cert/apiserver.key
I1214 18:26:48.622820       1 tlsconfig.go:240] Starting DynamicServingCertificateController
I1214 18:26:48.623553       1 configmap_cafile_content.go:202] Starting client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I1214 18:26:48.623653       1 shared_informer.go:240] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I1214 18:26:48.623775       1 configmap_cafile_content.go:202] Starting client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I1214 18:26:48.624163       1 shared_informer.go:240] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I1214 18:26:48.722643       1 shared_informer.go:247] Caches are synced for RequestHeaderAuthRequestController
I1214 18:26:48.724311       1 shared_informer.go:247] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I1214 18:26:48.724319       1 shared_informer.go:247] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
````

**i can't found why i have this erro**r 
```` unable to update list of all metrics: unable to fetch metrics for query "container_network_receive_bytes_total": Get "http://prometheus-k8s.monitoring.svc.cluster.local:9090/api/v1/series?match%5B%5D=container_network_receive_bytes_total&start=1639506347.454": dial tcp 10.3.4.19:9090: connect: connection refused````

**Comment by AaronWGoh** [comment]
@NadhemMohamedRached , I have the same issue now. Did you end up resolving this?

**Comment by NadhemMohamedRached** [comment]
Yes I change the file kubernetes/
kube-prometheus/
manifests/
prometheusAdapter-configMap.yaml 
To
apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: monitoring
data:
  config.yaml: |
    rules:
    - seriesQuery: 'container_network_transmit_bytes_total'
      resources:
        overrides:
          namespace:
            resource: namespace
          pod:
            resource: pod
      name:
        matches: ^(.*)_total$
        as: "${1}_per_second"
      metricsQuery: sum(rate(<<.Series>>{id=~".*.*",<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)
    resourceRules:
      cpu:
        containerQuery: sum(rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>)
        nodeQuery: sum(rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>, id='/'}[1m])) by (<<.GroupBy>>)
        resources:
          overrides:
            instance:
              resource: node
            namespace:
              resource: namespace
            pod:
              resource: pod
        containerLabel: container
      memory:
        containerQuery: sum(container_memory_working_set_bytes{<<.LabelMatchers>>}) by (<<.GroupBy>>)
        nodeQuery: sum(container_memory_working_set_bytes{<<.LabelMatchers>>,id='/'}) by (<<.GroupBy>>)
        resources:
          overrides:
            instance:
              resource: node
            namespace:
              resource: namespace
            pod:
              resource: pod
        containerLabel: container
      window: 1m
    externalRules:
    - seriesQuery: '{__name__=~"^.*_queue_(length|size)$",namespace!=""}'
      resources:
        overrides:
          namespace:
            resource: namespace
      name:
        matches: ^.*_queue_(length|size)$
        as: "$0"
      metricsQuery: max(<<.Series>>{<<.LabelMatchers>>})
    - seriesQuery: '{__name__=~"^.*_queue$",namespace!=""}'
      resources:
        overrides:
          namespace:
            resource: namespace
      name:
        matches: ^.*_queue$
        as: "$0"
      metricsQuery: max(<<.Series>>{<<.LabelMatchers>>})
