### ISSUE TITLE
Consider refactoring or consolidating how we drop metrics

### ISSUE THREAD

**Issue by PhilipGough** [prometheus-operator/kube-prometheus#1554]
**Why do we need it?**

We currently have an addon to drop deprecated metrics, while some metrics are dropped directly in the ServiceMonitor itself. It might be good to formalise how we do this across the project.

While creating https://github.com/prometheus-operator/kube-prometheus/pull/1553 I tried to drop a `coredns` metric via the addon but it had no effect since it does not seem to be applied to that specific SM, but there are other existing examples of this too.

It might be valuable to determine exactly why (perhaps via file/addon name?) we are dropping (i.e deprecation) as opposed to something else (i.e cardinality) but we could perhaps apply them similarly.

**Comment by ArthurSens** [comment]
I'm not sure how others think of it, but I do like the idea of expanding the [lib](https://github.com/prometheus-operator/kube-prometheus/tree/main/jsonnet/kube-prometheus/lib) folder with useful functions. 

I'm not aware if there are any Jsonnet design patterns documented anywhere, but I feel like addons are just plain patches without much logic while lib could provide functions like dropping metrics or rule patching(See https://github.com/prometheus-operator/kube-prometheus/pull/1351).
