### ISSUE TITLE
Missing workload_type: Job for record: namespace_workload_pod:kube_pod_owner:relabel

### ISSUE THREAD

**Issue by pindge** [prometheus-operator/kube-prometheus#1563]
**What is missing?**

We are using `Kubernetes / Compute Resources / Workload` dashboard and couldn't see any `workload_type: Jobs`

This is the metrics query 

```
sum(
    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster="$cluster", namespace="$namespace"}
  * on(namespace,pod)
    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster="$cluster", namespace="$namespace", workload="$workload", workload_type="$type"}
) by (pod)
```

**Why do we need it?**

According to Kubernetes official documentation, there are 4 types of workload https://kubernetes.io/docs/concepts/workloads/
- Deployment/ReplicaSet
- StatefulSet
- DaemonSet
- Job/CronJob

but our manifest only declares 3 types https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/kubernetesControlPlane-prometheusRule.yaml#L1324-L1360

**Anything else we need to know?**:

we are using `kube-prometheus-stack` helm chart and have raised an issue there https://github.com/prometheus-community/helm-charts/issues/1627 also a pr https://github.com/prometheus-community/helm-charts/pull/1628

but the file declares the original source is in this repo https://github.com/prometheus-community/helm-charts/blob/691f631e82546d937d8a383bde2939b1bf3325a8/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/k8s.rules.yaml#L4

**Comment by paulfantom** [comment]
Fix was brought in from kubernetes-mixin project in #1579
