### ISSUE TITLE
Setup Error for custom-metrics.libsonnet

### ISSUE THREAD

**Issue by jnccneto** [prometheus-operator/kube-prometheus#1587]
### Discussed in https://github.com/prometheus-operator/kube-prometheus/discussions/1585

<div type='discussions-op-text'>

<sup>Originally posted by **jnccneto** January 17, 2022</sup>
Hello

I have setup the bundle following the repo instructions:
https://github.com/prometheus-operator/kube-prometheus

Standart is ok, and I have CPU/MEMORY POD metrics.
Now I need custom metrics but I get an error when building with jsonet and enabled custom-metrics.libsonnet.
Any ideas on how to fix it?

error output:

RUNTIME ERROR: max stack frames exceeded.
	vendor/kube-prometheus/addons/custom-metrics.libsonnet:7:18-54	object <anonymous>
	vendor/kube-prometheus/addons/custom-metrics.libsonnet:7:18-54	object <anonymous>
	vendor/kube-prometheus/addons/custom-metrics.libsonnet:7:18-54	object <anonymous>
	vendor/kube-prometheus/addons/custom-metrics.libsonnet:7:18-54	object <anonymous>
	vendor/kube-prometheus/addons/custom-metrics.libsonnet:7:18-54	object <anonymous>
	vendor/kube-prometheus/addons/custom-metrics.libsonnet:7:18-54	object <anonymous>
	vendor/kube-prometheus/addons/custom-metrics.libsonnet:7:18-54	object <anonymous>
	vendor/kube-prometheus/addons/custom-metrics.libsonnet:7:18-54	object <anonymous>
	vendor/kube-prometheus/addons/custom-metrics.libsonnet:7:18-54	object <anonymous>
	vendor/kube-prometheus/addons/custom-metrics.libsonnet:7:18-54	object <anonymous>
	...
	vendor/kube-prometheus/addons/custom-metrics.libsonnet:7:18-54	object <anonymous>
	vendor/kube-prometheus/addons/custom-metrics.libsonnet:7:18-54	object <anonymous>
	vendor/kube-prometheus/addons/custom-metrics.libsonnet:7:18-54	object <anonymous>
	vendor/kube-prometheus/addons/custom-metrics.libsonnet:7:18-54	object <anonymous>
	vendor/kube-prometheus/addons/custom-metrics.libsonnet:7:18-54	object <anonymous>
	vendor/kube-prometheus/addons/custom-metrics.libsonnet:7:18-54	object <anonymous>
	vendor/kube-prometheus/addons/custom-metrics.libsonnet:7:18-54	object <anonymous>
	vendor/kube-prometheus/addons/custom-metrics.libsonnet:7:18-54	object <anonymous>
	vendor/kube-prometheus/components/prometheus-adapter.libsonnet:141:20-40	object <anonymous>
	During manifestation

my jsonet file:

`local kp =
  (import 'kube-prometheus/main.libsonnet') +
  // Uncomment the following imports to enable its patches
  // (import 'kube-prometheus/addons/anti-affinity.libsonnet') +
  // (import 'kube-prometheus/addons/managed-cluster.libsonnet') +
  (import 'kube-prometheus/addons/node-ports.libsonnet') +
  // (import 'kube-prometheus/addons/static-etcd.libsonnet') +
  (import 'kube-prometheus/addons/custom-metrics.libsonnet') +
  // (import 'kube-prometheus/addons/external-metrics.libsonnet') +
  {
    values+:: {
      common+: {
        namespace: 'monitoring',
      },
    },
  };

{ 'setup/0namespace-namespace': kp.kubePrometheus.namespace } +
{
  ['setup/prometheus-operator-' + name]: kp.prometheusOperator[name]
  for name in std.filter((function(name) name != 'serviceMonitor' && name != 'prometheusRule'), std.objectFields(kp.prometheusOperator))
} +
// serviceMonitor and prometheusRule are separated so that they can be created after the CRDs are ready
{ 'prometheus-operator-serviceMonitor': kp.prometheusOperator.serviceMonitor } +
{ 'prometheus-operator-prometheusRule': kp.prometheusOperator.prometheusRule } +
{ 'kube-prometheus-prometheusRule': kp.kubePrometheus.prometheusRule } +
{ ['alertmanager-' + name]: kp.alertmanager[name] for name in std.objectFields(kp.alertmanager) } +
{ ['blackbox-exporter-' + name]: kp.blackboxExporter[name] for name in std.objectFields(kp.blackboxExporter) } +
{ ['grafana-' + name]: kp.grafana[name] for name in std.objectFields(kp.grafana) } +
{ ['kube-state-metrics-' + name]: kp.kubeStateMetrics[name] for name in std.objectFields(kp.kubeStateMetrics) } +
{ ['kubernetes-' + name]: kp.kubernetesControlPlane[name] for name in std.objectFields(kp.kubernetesControlPlane) }
{ ['node-exporter-' + name]: kp.nodeExporter[name] for name in std.objectFields(kp.nodeExporter) } +
{ ['prometheus-' + name]: kp.prometheus[name] for name in std.objectFields(kp.prometheus) } +
{ ['prometheus-adapter-' + name]: kp.prometheusAdapter[name] for name in std.objectFields(kp.prometheusAdapter) }`</div>

**Comment by Dspatharakis** [comment]
I have the same problem!

**Comment by jnccneto** [comment]
I ended up using the Helm chart installation. Works better

**Comment by rajasaur** [comment]
I got the same issue (as discussed in #1585 ), and the problem was in the custom-metrics.libsonnet. The offending lines are at
```
{
  values+:: {
    prometheusAdapter+: {
      namespace: $.values.prometheusAdapter.namespace,
```

I think (Not really sure) that this is looping back to including the local variable initialization in example.jsonnet, which then loops back to this and then back to the original file. When I changed that value from `$.values.prometheusAdapter.namespace` to my namespace, say, `monitoring`, the build works properly and I was able to get the manifests.

I havent really worked out how to separate out the variables included in the example.jsonnet separately so that this wont loop itself again but thought Id share in case anyone faces this.

**Comment by MatTerra** [comment]
Did what @rajasaur proposed and it worked, but the prometheus-adapter pod keeps restarting...

**Comment by nabadger** [comment]
Still hitting this issue and not sure what the work around is. Not keen on updating the vendored-in code...any ideas?

**Comment by edwargix** [comment]
We're experiencing this issue on the release-0.11 branch (commit e3066575dc8b)
