### ISSUE TITLE
Investigate and update `allowPrivilegeEscalation` in manifests 

### ISSUE THREAD

**Issue by PhilipGough** [prometheus-operator/kube-prometheus#1588]
**What is missing?**

In #1584 we introduced security scanning of our manifests via [kubescape](https://github.com/armosec/kubescape).

The output of that scan shows the following resources have a [securityContext](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/) with `allowPrivilegeEscalation=true`

* Deployment - blackbox-exporter 
* Deployment - grafana 
* Deployment - kube-state-metrics 
* Deployment - prometheus-adapter 
* Deployment - prometheus-operator 
* DaemonSet - node-exporter 

> This defaults to allowed so as to not break setuid binaries. Setting it to false ensures that no child process of a container can gain more privileges than its parent.

We should investigate in all listed cases if we can set the value to `false`. If we can not make the change, we should document why and add an [exception](https://github.com/armosec/kubescape/blob/master/examples/exceptions/README.md) to our configuration. 

After we make the changes, we should determine the new risk score and adjust [the threshold](https://github.com/prometheus-operator/kube-prometheus/blob/f7d3019a8f1bf8b49402c77ad651c95ef16be68d/Makefile#L69) accordingly

**Why do we need it?**

> Attackers may gain access to a container and uplift its privilege to enable excessive capabilities.
See https://hub.armo.cloud/docs/c-0016

cc @ArthurSens

**Comment by paulfantom** [comment]
AFAIK `allowPrivilegeEscalation=true` is a default setting and we did not change it to `false` :shrug: I would guess this can be set to `false` for everything but node_exporter and blackbox_exporter. However the latter might only need it for ICMP scans and thus it can be enabled conditionally (same as in https://github.com/prometheus-operator/kube-prometheus/blob/main/jsonnet/kube-prometheus/components/blackbox-exporter.libsonnet#L169-L175). This needs to be tested though :)

**Comment by ArthurSens** [comment]
> AFAIK `allowPrivilegeEscalation=true` is a default setting and we did not change it to `false` 🤷 I would guess this can be set to `false` for everything but node_exporter and blackbox_exporter. However the latter might only need it for ICMP scans and thus it can be enabled conditionally (same as in https://github.com/prometheus-operator/kube-prometheus/blob/main/jsonnet/kube-prometheus/components/blackbox-exporter.libsonnet#L169-L175). This needs to be tested though :)

Yeah, I've been reading docs and experimenting a bit for this one today. From [k8s docs](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/):
```
AllowPrivilegeEscalation: Controls whether a process can gain more privileges than its parent process. This bool directly controls whether the no_new_privs flag gets set on the container process. AllowPrivilegeEscalation is true always when the container is: 1) run as Privileged OR 2) has CAP_SYS_ADMIN.
```

So, by default, all our components already have this set to `false`. I believe blackbox-exporter is the only one that can become privileged in case it needs access to `NET_RAW`.

Even though they are all false by default, kubescape asks us to explicitly set it to false.

**Comment by ArthurSens** [comment]
One thing to notice: the container definition of Grafana and Kube-state-metrics are implemented upstream. I'll open a PR overriding them here, but I'll also open PRs upstream hoping that we don't need to override anything
