### ISSUE TITLE
Investigate the automatic mapping of service accounts

### ISSUE THREAD

**Issue by PhilipGough** [prometheus-operator/kube-prometheus#1589]
**What is missing?**

In #1584 we introduced security scanning of our manifests via [kubescape](https://github.com/armosec/kubescape).

The output of that scan shows following resources have enabled automatic mapping of their service account tokens

* ServiceAccount - alertmanager-main 
* ServiceAccount - blackbox-exporter 
* ServiceAccount - grafana 
* ServiceAccount - kube-state-metrics 
* ServiceAccount - node-exporter 
* ServiceAccount - prometheus-k8s 
* ServiceAccount - prometheus-adapter 
* ServiceAccount - prometheus-operator 
* Deployment - blackbox-exporter 
* Deployment - grafana 
* Deployment - kube-state-metrics 
* Deployment - prometheus-adapter 
* Deployment - prometheus-operator 
* DaemonSet - node-exporter 

We should investigate in all listed cases if we can disable this default setting, enabling it only for PODS that need them. If we can not make the change, we should document why and add an [exception](https://github.com/armosec/kubescape/blob/master/examples/exceptions/README.md) to our configuration. 

After we make the changes, we should determine the new risk score and adjust [the threshold](https://github.com/prometheus-operator/kube-prometheus/blob/f7d3019a8f1bf8b49402c77ad651c95ef16be68d/Makefile#L69) accordingly

**Why do we need it?**

> Description: Potential attacker may gain access to a POD and steal its service account token. Therefore, it is recommended to disable automatic mapping of the service account tokens in service account configuration and enable it only for PODs that need to use them.

See https://hub.armo.cloud/docs/c-0034

cc @ArthurSens

**Comment by paulfantom** [comment]
I completely forgot to finish this after the investigation I did in my homelab. Sorry.

The result was that after setting `automountServiceAccountToken` set to false in all ServiceAccount objects only the following components needed to have this reenabled on pod level:
- prometheus
- prometheus-operator
- kube-state-metrics
- prometheus-adapter

Bear in mind that to do this properly we need to modify code in 4 different repositories (specific files listed below):
- [prometheus-operator](https://github.com/prometheus-operator/prometheus-operator/blob/main/jsonnet/prometheus-operator/prometheus-operator.libsonnet)
- [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/jsonnet/kube-state-metrics/kube-state-metrics.libsonnet)
- [kubernetes-grafana](https://github.com/brancz/kubernetes-grafana/blob/master/grafana/grafana.libsonnet)
- here ;)

**Comment by PhilipGough** [comment]
Closed via #1591

**Comment by werdnum** [comment]
See https://github.com/prometheus-operator/kube-prometheus/pull/1808 - this change has broken the scraper in my installation.
