### ISSUE TITLE
Investigate updating the default 'readOnlyRootFilesystem' to enforce immutable container fs

### ISSUE THREAD

**Issue by PhilipGough** [prometheus-operator/kube-prometheus#1595]
**What is missing?**

In #1584 we introduced security scanning of our manifests via [kubescape](https://github.com/armosec/kubescape).

The output of that scan shows following resources have, by default permitted mostly unrestricted execution within their own context. 

We should investigate in all listed cases if we can set `readOnlyRootFilesystem : true` in `securityContext`. If we can not make the change, we should document why and add an [exception](https://github.com/armosec/kubescape/blob/master/examples/exceptions/README.md) to our configuration. 

* Deployment - blackbox-exporter 
* Deployment - grafana 
* Deployment - kube-state-metrics 
* Deployment - prometheus-adapter 
* Deployment - prometheus-operator 
* DaemonSet - node-exporter 

**Why do we need it?**

>  An attacker who has access to a container, can create files and download scripts as they wish, and modify the underlying application running on the container.

See https://hub.armo.cloud/docs/c-0017

**Comment by ArthurSens** [comment]
> Set the filesystem of the container to read-only when possible (POD securityContext, readOnlyRootFilesystem: true). If containers application needs to write into the filesystem, it is recommended to mount secondary filesystems for specific directories where application require write access.

If I'm not mistaken, Grafana is the only component that needs to write to the filesystem right? Since it has a built-in database to save manual changes, e.g. creating a new dashboard or notification. Is that correct?

**Comment by ArthurSens** [comment]
Answering my own question: It is not needed for Grafana as well!

We can set `readOnlyRootFilesystem : true` to all components, as long as we create volume mounts to the specific directories we want to write to.

Our grafana already has its database [as a volumeMount](https://github.com/prometheus-operator/kube-prometheus/blob/c2d6b3e8c60891b40f72ce50bd90ae9a43a22a81/manifests/grafana-deployment.yaml#L51-L53)
