### ISSUE TITLE
Grafana dashboards imported by a ConfigMap can't be deleted

### ISSUE THREAD

**Issue by stoupance** [prometheus-operator/kube-prometheus#1604]
**What happened?**
Grafana dashboards imported by a `configMap` is not deleted in Grafana pod & UI once the `configMap` has been deleted on Kubernetes side

**Did you expect to see some different?**
The dashboard should be deleted

**How to reproduce it (as minimally and precisely as possible)**:
Delete the `configMap` with `kubectl delete configmap -n namespace mydashboard` but the dashboard remains on grafana pod

**Environment**

* Prometheus Operator version:

    `quay.io/prometheus-operator/prometheus-operator:v0.50.0`
    

* Kubernetes version information:

    `Client v1.23.3`
    `Server v1.20.9`
    

* Kubernetes cluster kind:

    This cluster was deployed with AKS

**Comment by ArthurSens** [comment]
That's how Kubernetes works really 😅.

After you spin up a pod with a configmap mounted, the file is mounted at startup time and will remain on the filesystem of that container. It doesn't matter if the configmap is deleted afterward, the confimap was already mounted.

If you edit Grafana's deployment unmounting the configmap, then your dashboard won't be present in Grafana's UI

**Comment by stoupance** [comment]
Well, I know is the expected behavior of course, when you create a new configMap. It will mount it in the pod's filesystem of the `grafana` pod, then it will reload Grafana through `grafana-sc-dashboard` pod, but I expected it will do the same when a configMap is deleted. It will removed it from the pod's filesystem and/or delete the dashboard inside the Grafana pod and reload it.

How do you then delete Grafana dashboard?

**Comment by ArthurSens** [comment]
If you are using jsonnet to render and deploy the manifests, you can just filter dashboards out before deploying, and I believe we can improve documentation on that end for sure. 

If you've already deployed the stack, you need to edit the Grafana deployment to unmount the dashboards you don't need

**Comment by ArthurSens** [comment]
hi @stoupance,

I've just opened a [pull request](https://github.com/prometheus-operator/kube-prometheus/pull/1615) with an example of how to drop unwanted dashboards. Does that help?
