### ISSUE TITLE
Run node_exporter in system-node-critical priority class

### ISSUE THREAD

**Issue by paulfantom** [prometheus-operator/kube-prometheus#1626]
**What is missing?**

It might be good to consider running node_exporter pods with `priorityClassName: system-node-critical` to allow smooth operations in clusters with autoscaler enabled and high resource occupancy.

**Why do we need it?**

More context in https://kubernetes.slack.com/archives/CFFDS2Z7F/p1644364876048319

**Environment**

* kube-prometheus version:

    `Insert Git SHA here`

**Anything else we need to know?**:

Similar approach is done by OpenShift - https://github.com/openshift/cluster-monitoring-operator/blob/master/assets/node-exporter/daemonset.yaml#L132 (side question: @simonpasquier @PhilipGough any reason OpenShift is running node_exporter in `system-cluster-critical` and not `system-node-critical`?)

**Comment by PhilipGough** [comment]
@paulfantom - looks like based on https://github.com/openshift/cluster-monitoring-operator/pull/97#issuecomment-420290015, since the highest priority is assigned to workloads whose absence could take the cluster down.

The change was made initially in https://github.com/openshift/cluster-monitoring-operator/pull/99

**Comment by paulfantom** [comment]
I agree with reasoning from https://github.com/openshift/cluster-monitoring-operator/pull/97#issuecomment-420290015 so let's assign node_exporter an `priorityClassName: system-cluster-critical`.

**Comment by PhilipGough** [comment]
@paulfantom - I agree that the change you suggested is probably the best outcome, although reading https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/ I am not sure it will guarantee scheduling and solve the issue linked in Slack?

**Comment by simonpasquier** [comment]
The CMO setting is aligned with the OpenShift conventions: https://github.com/openshift/enhancements/blob/master/CONVENTIONS.md#priority-classes

**Comment by paulfantom** [comment]
I am not sure it would solve it either. However, IMHO it is still a good idea to run node_exporter pods with `priorityClassName: system-cluster-critical` for the same reasons OpenShift is running node_exporter with this priority class.

**Comment by PhilipGough** [comment]
> However, IMHO it is still a good idea to run node_exporter pods with priorityClassName: system-cluster-critical
+1 from me
