### ISSUE TITLE
Quickstart Grafana not able to connect to http://prometheus

### ISSUE THREAD

**Issue by matthewchngshopback** [prometheus-operator/kube-prometheus#1648]
**What happened?**
Followed Quickstart install.

1. Port-forwarded Grafana and launched UI
2. Login and navigate to Configuration > Data sources > Prometheus
3. Scroll to bottom and clicked `Test` button.
4. Sees following error
  ```
  Error reading Prometheus: Post "http://prometheus-k8s.monitoring.svc:9090/api/v1/query": dial tcp 10.96.149.147:9090: i/o timeout
  ```
**Did you expect to see some different?**
It should show this instead
```
Data source is working
```

**How to reproduce it (as minimally and precisely as possible)**:
As explained in "What happned?" above.

**Environment**
1. Kind with Docker Desktop Windows WSL2
2. prometheus-operator/kube-prometheus branch: main

* Prometheus Operator version:

branch: main
/manifests

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-23T01:39:14Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

Cluster created with Knative Quickstart plugin using Kind and Docker Desktop Windows WSL2
```
kn quickstart kind
```

* Manifests:

```
na
```

* Prometheus Operator Logs:

```
na
```

* Prometheus Logs:

```
na
```

**Anything else we need to know?**:

Using `nc -zv <host> <port>` to check from the `grafana` pod,
- `prometheus-k8s:9090` not opened
- `prometheus-operated:9090` is opened

**Comment by PhilipGough** [comment]
I don't have a windows machine I can test this out on, but I did install `kn` and the quickstart plugin to see if I could reproduce the issue on OS X and I cannot.

Have a check in the `monitoring` namespace to ensure all the Pods are running. There is nothing special happening between Grafana and Prometheus that falls outside the realm of typical comms between Pods on over the internal DNS.

**Comment by matthewchngshopback** [comment]
Everything is defintely running. I can get everything working fine by switching the data source URL to `http://prometheus-operated.monitoring.svc:9090`.

```
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 8.3.6
  name: grafana-datasources
  namespace: monitoring
stringData:
  datasources.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
                "access": "proxy",
                "editable": false,
                "name": "prometheus",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://prometheus-operated.monitoring.svc:9090",
                "version": 1
            }
        ]
    }
type: Opaque
```

**Comment by douglascamata** [comment]
Hey folks! I took a shot at getting to the bottom of this. 

In the end, the problem happens because the Prometheus Operator uses a Service with session affinity. As described in [kube-proxy docs](https://kind.sigs.k8s.io/docs/user/using-wsl2/#kubernetes-service-with-session-affinity):

> If you want to create a Kubernetes Service with sessionAffinity: ClientIP it will not be accessible (and neither will any Service created afterwards). WSL2 kernel is missing xt_recent kernel module, which is used by Kube Proxy to implement session affinity. You need to compile a custom kernel to enable this feature.

I went the hardcore way and did the kernel compilation (there are instructions in the kube-proxy docs link above). It worked like a charm, but the dependency list given by them docs are out of date. You should install all of these: `apt install -y git build-essential flex bison libssl-dev libelf-dev bc python3 dwarves`.

Or, if you're using it for testing purposes, you could disable the session affinity via jsonnet or manually. I do not know what would be the consequences, so proceed with caution.
