### ISSUE TITLE
prometheus not respecting pod annotations

### ISSUE THREAD

**Issue by yellowhat** [prometheus-operator/kube-prometheus#1653]
Hi,
I would like to use the `kube-prometheus-stack` to deploy `prometheus` and `grafana`.

I have added the following annotation to the pod I would like to extract metrics from:

```
$ kubectl describe pod test
Annotations:  cluster-autoscaler.kubernetes.io/safe-to-evict: false
              prometheus.io/path: /test/prometheus/
              prometheus.io/port: 8080
              prometheus.io/scrape: true
Status:       Running
IP:           172.16.1.14
IPs:
  IP:           172.16.1.14

$ kubectl exec -it pod -- curl http://172.16.1.14:8080/test/prometheus/
...
jenkins_executor_in_use_history{quantile="0.5",} 0.0
jenkins_executor_in_use_history{quantile="0.75",} 0.0
jenkins_executor_in_use_history{quantile="0.95",} 0.0
jenkins_executor_in_use_history{quantile="0.98",} 0.0
```

I have installed the chart using:

```
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
kubectl create namespace monitoring
helm install prometheus prometheus-community/kube-prometheus-stack \
    --namespace monitoring \
    --set "grafana.ingress.enabled=True"
```

If I connect to the grafana WebUI I am able to use the metrics collected by the included dashboard, but if I search for `jenkins` under the `explore` tab nothing comes up.

Are there other option to enable in the chart to force prometheus to search for that annotation?

Thanks

**Environment**

* Prometheus Operator version:

```
$ kubectl -n monitoring describe deployment prometheus-kube-prometheus-operator
...
Labels:                 app=kube-prometheus-stack-operator
                        app.kubernetes.io/instance=prometheus
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/part-of=kube-prometheus-stack
                        app.kubernetes.io/version=32.2.1
                        chart=kube-prometheus-stack-32.2.1
                        heritage=Helm
                        release=prometheus
...
  Containers:
   kube-prometheus-stack:
    Image:      quay.io/prometheus-operator/prometheus-operator:v0.54.0
    Port:       10250/TCP
    Host Port:  0/TCP
```

* Kubernetes version information:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"archive", BuildDate:"2022-02-18T22:31:12Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9-gke.300", GitCommit:"d94fd1808d7f2b616f611c58f9975f41d48a4662", GitTreeState:"clean", BuildDate:"2022-01-24T09:29:20Z", GoVersion:"go1.16.12b7", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
```

**Comment by yellowhat** [comment]
I have tried to use the `prometheus` helm chart:
```console
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
helm install prometheus prometheus-community/prometheus \
    --namespace monitoring \
    --create-namespace
```

From the prometheus webui I am able to search for the `jenkins_executor_in_use_history` metric.
Is there a particular flag to enable for the `kube-prometheus-stack` helm chart?

Thanks

**Comment by PhilipGough** [comment]
Hi 👋 

A couple of things. Firstly the helm charts are not maintained by the maintainer of prometheus-operator or kube-prometheus. It is a community maintained project that leverages this project.

Secondly, this project deploys prometheus-operator which uses [custom resources](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/), not annotations to discover and scrape targets.

Please take a look at https://prometheus-operator.dev/docs/operator/design/ and https://github.com/prometheus-operator/prometheus-operator/tree/main/Documentation

**Comment by yellowhat** [comment]
I have tried to deploy a `ServiceMonitor`:

```console
$ kubectl get servicemonitors monitoring-b -o yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  creationTimestamp: "2022-02-21T20:28:13Z"
  generation: 1
  labels:
    controller: b
  name: monitoring-b
  namespace: cloudbees-core
  resourceVersion: "10727"
  uid: 224b926c-01b1-49de-a487-f6e4dbde3305
spec:
  endpoints:
  - interval: 15s
    path: /b/prometheus/
    port: "8080"
  selector:
    matchLabels:
      com.cloudbees.cje.type: master
      tenant: b
```

This is the service I am trying to monitor:

```console
$ kubectl get svc b -o yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2022-02-21T20:28:13Z"
  labels:
    com.cloudbees.cje.tenant: b
    com.cloudbees.cje.type: master
    com.cloudbees.pse.tenant: b
    com.cloudbees.pse.type: master
    tenant: b
    type: master
  name: b
  namespace: cloudbees-core
  resourceVersion: "10731"
  uid: 70fba29f-c0ee-4c54-badc-87f0c333b20e
spec:
  clusterIP: 172.16.75.193
  clusterIPs:
  - 172.16.75.193
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: agent
    port: 50001
    protocol: TCP
    targetPort: 50000
  selector:
    com.cloudbees.cje.tenant: b
    com.cloudbees.cje.type: master
    com.cloudbees.pse.tenant: b
    com.cloudbees.pse.type: master
    tenant: b
    type: master
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

From the prometheus WebUi under "Status" --> "Service Discovery" I still do not see the custom `ServiceMonitor`.
Is a special configuration required to scrape `ServiceMonitor` in an another namespace?

Thanks

**Comment by PhilipGough** [comment]
PTAL at https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/troubleshooting.md#has-my-servicemonitor-been-picked-up-by-prometheus and https://github.com/prometheus-operator/prometheus-operator/blob/a7b4f69b5e02773dad99269fb8f44139c3cd0a79/Documentation/user-guides/getting-started.md 

> The Prometheus resource includes a field called serviceMonitorSelector, which defines a selection of ServiceMonitors to be used. By default and before the version v0.19.0, ServiceMonitors must be installed in the same namespace as the Prometheus instance. With the Prometheus Operator v0.19.0 and above, ServiceMonitors can be selected outside the Prometheus namespace via the serviceMonitorNamespaceSelector field of the Prometheus resource.

**Comment by yellowhat** [comment]
Thanks for the reply:

From the helm chart values:
```yaml
    ## ServiceMonitors to be selected for target discovery.
    ## If {}, select all ServiceMonitors
    ##
    serviceMonitorSelector: {}

    ## Namespaces to be selected for ServiceMonitor discovery.
    ##
    serviceMonitorNamespaceSelector: {}
```

I am assuming the `serviceMonitorNamespaceSelector: {}` means all namespaces.

**Comment by PhilipGough** [comment]
Yes. Your endpoint definition in the ServiceMonitor should reference `port` by name, in your case `http.

I am closing this now because this is not the correct forum (or project) for this type of support. Please read through the linked documentation and if you have any further questions, please search or feel free to reach out on #prometheus-operator on kubernetes Slack.

**Comment by DanielYWoo** [comment]
> Hi 👋
> 
> A couple of things. Firstly the helm charts are not maintained by the maintainer of prometheus-operator or kube-prometheus. It is a community maintained project that leverages this project.
> 
> Secondly, this project deploys prometheus-operator which uses [custom resources](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/), not annotations to discover and scrape targets.
> 
> Please take a look at https://prometheus-operator.dev/docs/operator/design/ and https://github.com/prometheus-operator/prometheus-operator/tree/main/Documentation

The operator will modify the `scrape_configs` by inspecting ServiceMonitor CRDs. I took a look at the generated `scrape_configs` and `relabel_configs` with the operator, there are no "drop" rules, but the pods with the annotations (`prometheus.io/scrape`) just won't show up, why is that? Both CRD and annotations should work if we solely look at the generated config.
