### ISSUE TITLE
Seeting CPU limits for container in the k8s resource

### ISSUE THREAD

**Issue by Leke-Ariyo** [prometheus-operator/kube-prometheus#1664]
I would like to set cpu limit for a specific container ```kube-rbac-proxy-main``` which is not the default one - in the k8s resource - ```kube-state-metrics``` in jsonnet, as currently, I am experiencing some CPU throttling.

how do I go about it.

**Comment by paulfantom** [comment]
Answered in slack: https://kubernetes.slack.com/archives/CFFDS2Z7F/p1646219889287799

**Comment by foosinn** [comment]
From the Slack Thread:

```jsonnet
{
  values: {
    kubeStateMetrics+:
      kubeRbacProxySelf+: {
        resources+: {
          limits: {
            cpu: '100m',
          },
        },
      },
    },
  },
}
```

@paulfantom commented:
> Then it doesn't have logic from https://github.com/prometheus-operator/kube-prometheus/pull/1637 which is needed for this.

This means `release-0-10` won't work.
