### ISSUE TITLE
prometheuses.monitoring.coreos.com  must have at most 262144 bytes

### ISSUE THREAD

**Issue by dyg070115** [prometheus-operator/kube-prometheus#1681]
[root@master setup]# kubectl apply -f 0prometheusCustomResourceDefinition.yaml
The CustomResourceDefinition "prometheuses.monitoring.coreos.com" is invalid: **metadata.annotations**: Too long: must have at most 262144 bytes

**Comment by dyg070115** [comment]
The content of metadata.annotations does not exceed that many bytes, and now it is impossible to create custom resources

**Comment by paulfantom** [comment]
Closing as a dup of https://github.com/prometheus-operator/kube-prometheus/issues/1511, https://github.com/prometheus-operator/kube-prometheus/issues/1533, https://github.com/prometheus-operator/prometheus-operator/issues/4367, https://github.com/prometheus-operator/prometheus-operator/issues/4355, https://github.com/prometheus-operator/prometheus-operator/issues/4348, and https://github.com/prometheus-operator/kube-prometheus/discussions/1474

**Comment by freemankevin** [comment]
`kubectl apply --server-side -f bundle.yaml `
