### ISSUE TITLE
Popular graphana dashboards show no data for "Pods Memory usage" and "Pods CPU usage"

### ISSUE THREAD

**Issue by surfingjoe** [prometheus-operator/kube-prometheus#1695]
### Discussed in https://github.com/prometheus-operator/kube-prometheus/discussions/1694

<div type='discussions-op-text'>

<sup>Originally posted by **surfingjoe** March 21, 2022</sup>
Running bare-metal K8s with flannel network and MetalLB as Load Balancer.
Cloned `https://github.com/prometheus-operator/kube-prometheus.git` just a few days ago.  Created "monitoring" namespace.  Performed Kubectl apply for manifests/setup, waited till all pods are up, then applied  manifests/

Instead of port forwarding, I patched each service to be: "Type" load-balancer considering that I'm using MetalLB.

Everything is operational.  Can successfully deploy containers with services exposed externally by the load balancer MetalLB.  All is well in the world. Can open Prometheus port 9090 & Graphana port 3000  externally from a browser and everything seems operational.  Graphana is seeing Prometheus data, and community dashboards are seeing some of the Prometheus data.

Import popular community dashboards like Community dashboard number 315 for example.  Oops, the dashboard reports "No Data" for PODS memory and CPU usage, but Graphana can see Cluster Memory & CPU usage. The dashboard can see Network I/O pressure, but "No data" for Pods network I/O.

As I'm a newbie to Graphana, I'm hoping someone wiser than me can help :)</div>

**Comment by MaximilianMeister** [comment]
Same issue here, it seems that some metrics referenced from the dashboard queries like `node_namespace_pod_container` are not available/exported by the metrics-server

**Comment by cguertin14** [comment]
+1 on this, cpu+memory and other metrics are not showing in the provided grafana dashboards

**Comment by jehutyy** [comment]
+1 issue still there

**Comment by fguiet** [comment]
+1 issue still here as well (Kubernetes deployed with Rancher)

```bash
# Stack deployed
prometheus-stack                monitoring-ns   10              2022-12-09 12:41:56.026097892 +0100 CET deployed        kube-prometheus-stack-42.2.0            0.60.1
```

![image](https://user-images.githubusercontent.com/13849639/208312312-7bd9ffba-148d-43a9-9560-aad78008af29.png)

**Comment by greg-peters** [comment]
@fguiet, edit the panel and remove `name=~"^k8s_.*",` from all the panels that aren't showing data. Your current settings are filtering out the view.

**Comment by willzhang** [comment]
same here, kuernetes v1.25.6 installl with kubeadm , kube-prometheu-stack v0.63.0 install with helm

![image](https://github.com/prometheus-operator/kube-prometheus/assets/33590311/2d894853-0e6b-4112-906d-91471dbacfd5)

**Comment by DolceParadise** [comment]
Same here. Number of replicas are correctly reflected in and shown in graph but there N/A for pod cluster usage

<img width="1270" alt="Screenshot 2023-05-30 at 3 15 39 PM" src="https://github.com/prometheus-operator/kube-prometheus/assets/74451989/e1b2e3f1-e833-432b-b560-304b8bf81c83">

**Comment by prionkor** [comment]
Is there any fix for the issue? or any dashboard id out there that I can import. I want to see pod resource uses over time for a deployment.

**Comment by eddyzags** [comment]
+1 issue still there

**Comment by comminutus** [comment]
Same problem for me

**Comment by MahdadGhasemian** [comment]
> @fguiet, edit the panel and remove `name=~"^k8s_.*",` from all the panels that aren't showing data. Your current settings are filtering out the view.

It worked

**Comment by oferdiari** [comment]
i all panel that not working ,just edit them and remove all this: "image!="",name=~"^k8s_.*","
it worked for me..
