### ISSUE TITLE
It Possible to fetch GPU metrics with kube-prometheus project 

### ISSUE THREAD

**Issue by Prashantsaini25** [prometheus-operator/kube-prometheus#1698]
Kube-Prometheus project not able to fetch GPU metrics how to Fetch GPU metrics with Kube-Prometheus project

**Comment by ArthurSens** [comment]
Looking at [Node-exporter's README](https://github.com/prometheus/node_exporter#node-exporter), GPU metrics are not supported.

They recommend using a third-party exporter https://github.com/NVIDIA/dcgm-exporter

**Comment by Prashantsaini25** [comment]
@ArthurSens I am using Kube-Prometheus project. we have try that also but Kube-Prometheus not take is automatically so to add endpoint in this project

**Comment by Prashantsaini25** [comment]
Done I have use DCGM then create secrets for DCGM and pass it to prometheus-prometheus.yaml then its working
