### ISSUE TITLE
Error while deploying using manifests

### ISSUE THREAD

**Issue by Choogster1** [prometheus-operator/kube-prometheus#1750]
I'm getting the following error for the kubectl apply --server-side -f manifests/setup command which fails to deploy

Error from server: failed to create typed patch object: errors:
  .spec.template.spec.containers[name="prometheus-operator"].ports: element 0: associative list with keys has an element that omits key field "protocol"
  .spec.template.spec.containers[name="kube-rbac-proxy"].ports: element 0: associative list with keys has an element that omits key field "protocol"
Error from server: failed to create typed patch object: .spec.ports: element 0: associative list with keys has an element that omits key field "protocol"

I've previously used the same method for deployment on the same server, but now it fails. Has anybody come across this?

**Comment by thinkmassive** [comment]
Hi @Choogster1, I encountered the same error when trying to install `release-0.7` on k8s `v1.19`, which lead me to:
- kubernetes-sigs/structured-merge-diff/issues/130

Based on that issue, I tried removing `--server-side` and was able to proceed with the quickstart:
```
kubectl apply -f manifests/setup
until kubectl get servicemonitors --all-namespaces ; do date; sleep 1; echo ""; done 
kubectl apply -f manifests/
```
