### ISSUE TITLE
How does promql query the basic information of all nodes, including k8s nodes outside the cluster?

### ISSUE THREAD

**Issue by lizhe19** [prometheus-operator/kube-prometheus#1756]
How does promql query the basic information of all nodes, including k8s nodes outside the cluster?

**Comment by slashpai** [comment]
I am not sure if I understand your question correctly. Could you please explain a bit more what you are trying to do?

**Comment by lizhe19** [comment]
你好...谢谢你的邮件 我已收到！

**Comment by lizhe19** [comment]
你好...谢谢你的邮件 我已收到！

**Comment by lizhe19** [comment]
你好...谢谢你的邮件 我已收到！

**Comment by lizhe19** [comment]
你好...谢谢你的邮件 我已收到！

**Comment by lizhe19** [comment]
你好...谢谢你的邮件 我已收到！

**Comment by lizhe19** [comment]
你好...谢谢你的邮件 我已收到！

**Comment by lizhe19** [comment]
你好...谢谢你的邮件 我已收到！
