### ISSUE TITLE
How to monitor job with kube-prometheus 

### ISSUE THREAD

**Issue by Prashantsaini25** [prometheus-operator/kube-prometheus#1778]
any one know how to monitor job with this kube-prometheus

**Comment by slashpai** [comment]
I suppose you are looking for how to monitor applications in kubernetes thats done with prometheus-operator's custom resources ServiceMonitor/PodMonitor. Please look at examples in  https://github.com/prometheus-operator/prometheus-operator/tree/main/example/user-guides/getting-started

**Comment by Prashantsaini25** [comment]
@slashpai It's done my qus about the jobs of Kubernetes.
