### ISSUE TITLE
alerts: KubeMemoryOvercommit and KubeCPUOvercommit look incorrect

### ISSUE THREAD

**Issue by cybergrind** [prometheus-operator/kube-prometheus#1791]
Hi all,
Sorry for bothering. ATM both alerts have same structure that looks like:

```
sum(namespace_cpu:kube_pod_container_resource_requests:sum{})  # total requested resources 
- (
    sum(kube_node_status_allocatable{resource="cpu"})  # total available resources
    - max(kube_node_status_allocatable{resource="cpu"})  # max resources on biggest node
) > 0
```

For me it looks like it has meaning: `total requested resources` - `available resources` - `resources of biggest node`
I'm not sure why we exclude resources from biggest node (`max(kube_node_status_allocatable{resource="cpu"})`) from our total pool.

Am I missing something?

**Comment by PhilipGough** [comment]
Hi @cybergrind , the alerts in question are sourced from https://github.com/kubernetes-monitoring/kubernetes-mixin if you wouldn't mind opening the issue there? Thanks

**Comment by cybergrind** [comment]
@PhilipGough thank you for pointing out!
Looks like it was a deliberate decision in https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/646

It isn't great for small clusters but at least makes sense
