### ISSUE TITLE
How to port forward in GKE?

### ISSUE THREAD

**Issue by shaon21** [prometheus-operator/kube-prometheus#1796]
Hi,

We have performed the helm install and can see the following services in GKE.
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/36475910/175948802-abae70b6-db88-4d40-83ea-db19df511a16.png">
So now which services to port forward and how can we achieve that? Is there documentation we can follow for GKE?

Regards,
Rias

**Comment by godwhoa** [comment]
The helm chart is not maintained by prometheus-operator maintainers.    
But they do mention accessing grafana in their quick start(which doesn't use helm).       
https://prometheus-operator.dev/docs/prologue/quick-start/#access-grafana
