### ISSUE TITLE
configmap-reloader by manual or change the time interval between polls for ConfigMap?

### ISSUE THREAD

**Issue by liaoqiArno** [prometheus-operator/kube-prometheus#1799]
How upload prometheus'rule  by manual  rules-configmap-reloader ?
Because I should wait for moment after change the configmap,I think wait to long...

**Comment by paulfantom** [comment]
> How upload prometheus'rule by manual rules-configmap-reloader ?

You don't. That ConfigMap is governed by prometheus-operator and shouldn't be edited manually. You should use PrometheusRule objects for storing alerting and recording rules.
