### ISSUE TITLE
How to modify the value of Configuration in Prometheus, I want to modify the scrape_interval field in the global.

### ISSUE THREAD

**Issue by biggercousin** [prometheus-operator/kube-prometheus#1804]
<img width="674" alt="image" src="https://user-images.githubusercontent.com/47242235/177516768-b57ed77e-bd27-4039-9352-829f1dc18bbb.png">
I want to modify the value of scrape_interval, I know it is in prometheus.yaml.gz, but I don't know how prometheus.yaml.gz is generated, I can't find the relevant fields in all yaml files.

**Comment by simonpasquier** [comment]
you can define `scrapeInterval` in https://prometheus-operator.dev/docs/operator/api/#prometheusspec

**Comment by biggercousin** [comment]
> you can define `scrapeInterval` in https://prometheus-operator.dev/docs/operator/api/#prometheusspec

This problem has been bothering me for 2 days, thank you very much for helping me solve this problem.

**Comment by hellowang-pj** [comment]
> > you can define `scrapeInterval` in https://prometheus-operator.dev/docs/operator/api/#prometheusspec
> 
> This problem has been bothering me for 2 days, thank you very much for helping me solve this problem.
Hello, I would like to know how the modification was made in the end. I used 'kubectl edit' to modify the 'prometheus.yaml.gz' file mounted in the 'config-reloader', but the changes only took effect for a moment.Then it was reverted back.
