### ISSUE TITLE
Can't get notifications from GitHub App

### ISSUE THREAD

**Issue by jobinjosem1** [prometheus-operator/kube-prometheus#1835]
Can we have GitHub App installed for this repo to get slack notifications for releases?

Currently, if I try to setup  notifications using /github subscribe prometheus-operator/kube-prometheus,  I get error to install the app.

![image](https://user-images.githubusercontent.com/55230905/183905341-3fb63e40-c7b7-4278-bd06-52ad43308d9b.png)

**Comment by slashpai** [comment]
I think it says to install github app on your slack org for getting github notifications :)
You might want to check with your org's slack admin for that
