### ISSUE TITLE
Error creating: pods "node-exporter-" is forbidden: error looking up service account monitoring/node-exporter: serviceaccount "node-exporter" not found

### ISSUE THREAD

**Issue by vitorafgomes** [prometheus-operator/kube-prometheus#1839]
After executing the commands below without any error being returned. When trying to import a dashboard into Grafana, I got an error.

kubectl create -f manifests/setup

kubectl create -f manifests/

![image](https://user-images.githubusercontent.com/5174765/184692485-2fc33623-a365-4b92-bf4a-a6071b6ffd45.png)

![image](https://user-images.githubusercontent.com/5174765/184691544-0c2945d8-5a82-4422-97ad-2dfbd3d1660a.png)

![image](https://user-images.githubusercontent.com/5174765/184691639-64185516-ce12-4ace-b78b-253cb360826a.png)

![image](https://user-images.githubusercontent.com/5174765/184691504-f25e8975-5c07-41bf-9e93-c931de9fd4e3.png)

**Comment by beebird** [comment]
This fix the issue
```bash
cat <<EOF | kubectl apply -f=-
apiVersion: v1
kind: ResourceQuota
metadata:
  name: prometheus-resource-quota
  namespace: monitoring
spec:
  hard:
    pods: 1000
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values:
      - system-node-critical
      - system-cluster-critical
     EOF

**Comment by vitorafgomes** [comment]
thanks @beebird
