### ISSUE TITLE
Where is the Prometheus.yml? 

### ISSUE THREAD

**Issue by jcquiles** [prometheus-operator/kube-prometheus#1845]
Hello, I deployed this particular helm chart, but cant seem to locate the prometheus.yml to scrap configs. I tried looking in all the usal palces like /etc/promtheus. Is there somewhere I should look in order to edit the prometheus.yml and scrap metrics?

Thank you! 

This repository now has the new GitHub Discussions enabled: 
https://github.com/coreos/kube-prometheus/discussions

Please create a new discussion to ask for any kind of support, which is not a Bug or Feature Request.

Thank you for being part of this community!

---

We are still happy to chat with you in the #prometheus-operator channel on Kubernetes Slack!

**Comment by slashpai** [comment]
The [prometheus-community/kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) helm chart is maintained by the Prometheus community. So issue on helm chart should be logged there :)

**Comment by jcquiles** [comment]
Yup, you're right thank you.
