### ISSUE TITLE
What happened?The grafana-Pod from the grafana deployment does not work.

### ISSUE THREAD

**Issue by Tim168888** [prometheus-operator/kube-prometheus#1847]
Environment:
Prometheus Operator stack version: github.com/prometheus-operator/prometheus-operator:v0.11
Kubernetes version information: v1.24.4+
Manifests: manifests/grafana-deployment.yaml

root@k8s-master01:~# kubectl describe pod grafana -n monitoring 
...
 Normal   Scheduled    37m                default-scheduler  Successfully assigned monitoring/grafana-949994976-hwfjv to k8s-master02
  Warning  FailedMount  37m                kubelet            MountVolume.SetUp failed for volume "grafana-dashboard-alertmanager-overview" : failed to sync configmap cache: timed out waiting for the condition
  Warning  FailedMount  37m                kubelet            MountVolume.SetUp failed for volume "grafana-dashboard-k8s-resources-pod" : failed to sync configmap cache: timed out waiting for the condition
  Warning  FailedMount  37m                kubelet            MountVolume.SetUp failed for volume "grafana-dashboard-prometheus" : failed to sync configmap cache: timed out waiting for the condition
  Warning  FailedMount  37m                kubelet            MountVolume.SetUp failed for volume "grafana-dashboard-k8s-resources-cluster" : failed to sync configmap cache: timed out waiting for the condition
  Warning  FailedMount  37m                kubelet            MountVolume.SetUp failed for volume "grafana-dashboard-k8s-resources-namespace" : failed to sync configmap cache: timed out waiting for the condition
  Warning  FailedMount  37m (x2 over 37m)  kubelet            MountVolume.SetUp failed for volume "grafana-dashboard-nodes" : failed to sync configmap cache: timed out waiting for the condition
  Warning  FailedMount  37m (x2 over 37m)  kubelet            MountVolume.SetUp failed for volume "grafana-dashboard-nodes-darwin" : failed to sync configmap cache: timed out waiting for the condition
  Warning  FailedMount  37m (x2 over 37m)  kubelet            MountVolume.SetUp failed for volume "grafana-dashboard-node-rsrc-use" : failed to sync configmap cache: timed out waiting for the condition
  Warning  FailedMount  37m (x2 over 37m)  kubelet            MountVolume.SetUp failed for volume "grafana-dashboards" : failed to sync configmap cache: timed out waiting for the condition
  Warning  FailedMount  37m (x6 over 37m)  kubelet            (combined from similar events): MountVolume.SetUp failed for volume "grafana-dashboard-k8s-resources-pod" : failed to sync configmap cache: timed out waiting for the condition
  Normal   Pulling      37m                kubelet            Pulling image "grafana/grafana:9.1.0"
  Normal   Pulled       36m                kubelet            Successfully pulled image "grafana/grafana:9.1.0" in 50.484983149s
  Normal   Created      36m                kubelet            Created container grafana
  Normal   Started      36m                kubelet            Started container grafana
  Warning  Unhealthy    36m (x2 over 36m)  kubelet            Readiness probe failed: Get "http://10.249.92.66:3000/api/health": dial tcp 10.249.92.66:3000: connect: connection refused

root@k8s-master01:~# kubectl logs -f grafana-949994976-hwfjv -n monitoring
...
logger=provisioning.notifiers t=2022-08-24T12:10:54.210569311Z level=error msg="Can't read alert notification provisioning files from directory" path=/etc/grafana/provisioning/notifiers error="open /etc/grafana/provisioning/notifiers: no such file or directory"
logger=provisioning.alerting t=2022-08-24T12:10:54.21064291Z level=error msg="can't read alerting provisioning files from directory" path=/etc/grafana/provisioning/alerting error="open /etc/grafana/provisioning/alerting: no such file or directory"
...

please help me

**Comment by jiaokele** [comment]
I am also

**Comment by Tim168888** [comment]
> 
OK，I have solved this problem。You must run the following command as root。
For example：
# kubectl delete networkpolicy --all -n monitoring

**Comment by galah92** [comment]
Getting the exact same problem, `kubectl delete networkpolicy --all -n monitoring` didn't work. Is there another solution?

**Comment by brendaoo** [comment]
meet the same problem

**Comment by brendaoo** [comment]
meet the same problem
k8s version:1.26
prometheus-satck repo:release-0.13

I run the command, but it dosen't work
`kubectl delete networkpolicy --all -n monitoring`

**Comment by jiangsanyin** [comment]
> > 
> 
> OK，I have solved this problem。You must run the following command as root。 For example：
> 
> # kubectl delete networkpolicy --all -n monitoring

I deployed kube-prometheus v0.11.0 from https://github.com/prometheus-operator/kube-prometheus.git in kubernetes 1.23.10, and meeted this problem. "kubectl delete networkpolicy --all -n monitoring" works for me.
