### ISSUE TITLE
No metrics for pods in Grafana, targets missing in prometheus

### ISSUE THREAD

**Issue by ChrisScottThomas** [prometheus-operator/kube-prometheus#188]
**What happened?**
I get no pod related metrics in Grafana, no targets in prometheus

**Did you expect to see some different?**

Yes.  I expected to see metrics and targets.

**How to reproduce it (as minimally and precisely as possible)**:

Slightly customized versions of the 0.1 manifests (we use PSPs)

**Environment**

* Prometheus Operator version:

    `quay.io/coreos/prometheus-operator:v0.30.0`

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:46:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}`

* Kubernetes cluster kind:

 `The hard way...`

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
klf -n monitoring prometheus-operator-84854bf584-m877v --tail 5
level=info ts=2019-08-20T08:04:40.394021773Z caller=operator.go:456 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
level=info ts=2019-08-20T08:09:40.394133213Z caller=operator.go:456 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
W0820 08:10:22.762634       1 reflector.go:289] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:417: watch of *v1.ConfigMap ended with: too old resource version: 28429011 (28430270)
level=info ts=2019-08-20T08:14:40.394514241Z caller=operator.go:456 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
level=info ts=2019-08-20T08:19:40.394578209Z caller=operator.go:456 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
```

* Prometheus Logs:

```
klf -n monitoring prometheus-k8s-0 prometheus --tail 5
level=warn ts=2019-08-20T08:03:16.330814466Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="/app/discovery/kubernetes/kubernetes.go:300: watch of *v1.Endpoints ended with: too old resource version: 28426567 (28428069)"
level=warn ts=2019-08-20T08:13:49.363798776Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="/app/discovery/kubernetes/kubernetes.go:300: watch of *v1.Endpoints ended with: too old resource version: 28429920 (28430409)"
level=warn ts=2019-08-20T08:14:52.359687843Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="/app/discovery/kubernetes/kubernetes.go:300: watch of *v1.Endpoints ended with: too old resource version: 28429673 (28430638)"
level=warn ts=2019-08-20T08:15:26.34261353Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="/app/discovery/kubernetes/kubernetes.go:300: watch of *v1.Endpoints ended with: too old resource version: 28429499 (28430765)"
level=warn ts=2019-08-20T08:16:06.348884581Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="/app/discovery/kubernetes/kubernetes.go:300: watch of *v1.Endpoints ended with: too old resource version: 28430555 (28430914)"
```

**Anything else we need to know?**:

Examples in attached screenshots below.  I've checked the logs of everything running and seeing nothing of concern.  Yet I am missing data.  You can also see that it's missing coredns, scheduler and controller-manager in targets.  There's no reason deployment wise, why they wouldn't work.  Locations and labeling are as Prometheus expects.

![Screenshot 2019-08-20 at 09 15 28](https://user-images.githubusercontent.com/47419381/63330711-2ea42f00-c32c-11e9-8dbf-f4a4118f77e2.png)
![Screenshot 2019-08-20 at 09 23 58](https://user-images.githubusercontent.com/47419381/63330742-4380c280-c32c-11e9-9e97-6877392acc55.png)
![Screenshot 2019-08-20 at 09 24 35](https://user-images.githubusercontent.com/47419381/63330837-6dd28000-c32c-11e9-8a22-10c411c6fb5f.png)
![Screenshot 2019-08-20 at 09 24 42](https://user-images.githubusercontent.com/47419381/63330839-6dd28000-c32c-11e9-949e-4dda58fa139f.png)
![Screenshot 2019-08-20 at 09 24 55](https://user-images.githubusercontent.com/47419381/63330840-6e6b1680-c32c-11e9-9e70-97c32e23254b.png)

**Comment by brancz** [comment]
are you successfully gathering metrics from the kubelet and kube-state-metrics?

**Comment by ChrisScottThomas** [comment]
yes they look all fine.  
<img width="1361" alt="Screenshot 2019-08-20 at 11 26 14" src="https://user-images.githubusercontent.com/47419381/63339708-64054880-c33d-11e9-805b-243983253678.png">

**Comment by brancz** [comment]
I see, the `master` of kube-prometheus is 1.14+ only. For 1.13 you want to use the head of the `release-0.1` branch.

**Comment by ChrisScottThomas** [comment]
Gah...I swear I had redeployed from that branch. I'm getting metrics now, but targets still show zero for coredns, controller, scheduler.  I have a feeling it's a labeling issue, as they're showing as dropped.

**Comment by brancz** [comment]
Yes that comes down to labeling. You can choose one of the available platforms, otherwise you will just need to make sure that the respective services and servicemonitors have matching labels.

**Comment by marcinma** [comment]
I see exactly same problem on AKS with v1.14.6 kubernetes version

**Comment by paulfantom** [comment]
Closing due to staleness. Please reopen if you think this is still relevant.
