### ISSUE TITLE
how can i config timezone to a container with a libsonnet file

### ISSUE THREAD

**Issue by niuhp** [prometheus-operator/kube-prometheus#190]
how can i config timezone to a container with a libsonnet file

or mount the /etc/localtime file

**Comment by paulfantom** [comment]
You probably shouldn't as monitoring should be done in UTC and if necessary, timezone should be applied at presentation stage.

More info: https://prometheus.io/docs/introduction/faq/#can-i-change-the-timezone-why-is-everything-in-utc

**Comment by paulfantom** [comment]
Closing due to staleness. Please reopen if you think this is still relevant.
