### ISSUE TITLE
How to clone multiple git repositories in workflow

### ISSUE THREAD

**Issue by Mayankm13** [prometheus-operator/kube-prometheus#1926]
I want to clone multiple repositories for the workflow to be configured in GitHub for Continuous Integration.

I am getting below error

Run pwd 

/runner/_work/EuronetsoftwareRenaissanceOnline/EuronetsoftwareRenaissanceOnline
total 4.0K
drwxr-xr-x 2 runner runner   22 Oct 30 [17](https://github.oneeuronet.com/Euronet-REN/EuronetsoftwareRenaissanceOnline/runs/42232?check_suite_focus=true#step:4:18):54 .
-rw-r--r-- 1 runner runner 1.7K Oct 30 17:54 test.pem
drwxr-xr-x 3 runner runner   46 Oct 30 17:54 ..
Cloning into '../renaissance-online-external-libs'...
fatal: unable to access 'https://IP/Euronet-REN/renaissance-online-external-libs/': SSL: certificate subject name (github.uklo.office.eeft.com) does not match target host name '10.25.95.100'

Below is my workflow for PUSH 
on: [push]
env: 
  WF_ENV: workflow envirnment variables
  PEM_KEY: ${{ secrets.APP_PEM_BADAM }}
jobs: 
  run-shell-command: 
    runs-on: [ 'self-hosted', 'linux', 'x64', 'docker' ]
    steps:
      - name: checking host details 
        run: |
          pwd
          uname -a
          pwd
          ls -lath 
          git --version
          git config  --list
          echo "GITHUB_ACTOR:  ${GITHUB_ACTOR}"
          echo "GIT_REPOSITORY: ${GIT_REPOSITORY}"
          echo ${PEM_KEY} >  test.pem
          cat test.pem
          echo ${{ github.token }}

      - name: checking git config details 
        run: |
          pwd 
          git config  --list
          ls -lath   
          git clone https://${{ github.token }}@Ip/REPO-REN/online-external-libs ../online-external-libs       
          pwd 
          ls -lath   
      - name: clone shared libs 
        uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
          
      - name: checking host details 
        run: |
          pwd
          ls -alrth  
          cd Linux
          ls -ltrha

**Comment by PhilipGough** [comment]
@Mayankm13 have you created this issue here by mistake?
