### ISSUE TITLE
How do you discover custom tags in a service or pod? 

### ISSUE THREAD

**Issue by Heyz6** [prometheus-operator/kube-prometheus#1969]
version：kube-prometheus-0.9.0
I need help, I want to query and alert in prometheus according to the metadata labels defined in the pod or service, how should I do it, thanks

The kubernetes pod yaml example file is as follows
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    prodcut: Customization-prod

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    prodcut: Customization-dev

![image](https://user-images.githubusercontent.com/13972460/207216467-2f98d6d6-cd6c-42d6-855b-68a7f1f4ab55.png)

**Comment by Animezjy** [comment]
I'm having the same issue. Have you found the right solution?

**Comment by Heyz6** [comment]
I'm sorry, but I have not found a solution to this problem.Despite all my attempts @Animezjy
