### ISSUE TITLE
Some dashboards show No Data.

### ISSUE THREAD

**Issue by IMAN-NAMJOOYAN** [prometheus-operator/kube-prometheus#1970]
Hi

I am new in kubernetes.
I have a problem with grafana. The "Controller Manager", "Compute Resource","proxy"  and "Scheduler"  dashboards show "No Data".
![image](https://user-images.githubusercontent.com/16554389/207360121-e9fdd87f-5444-4c91-9372-4fb54e771f85.png)

![image](https://user-images.githubusercontent.com/16554389/207363133-b952be95-08ab-4385-a31c-e7f826ba0003.png)

**Comment by jameshearttech** [comment]
What is your environment? We are running k8s self-managed. I've set this up on my end. In my experience you have to configure the control plane resources so prometheus can scrape them. I actually just rebuilt our dev cluster and revised the setup notes. Here's what I have for the resources you mentioned. Use at your own risk.

Configure kube-controller-manager for Prometheus. Change bind address from 127.0.0.1 to 0.0.0.0 on all control plane nodes one at a time.

```
sudo sed -e 's/--bind-address=127.0.0.1/--bind-address=0.0.0.0' -i /etc/kubernetes/manifests/kube-controller-manager
```

Confirm kube-controller-manager pod restarts and is running before moving on to the next control plane node.

```
watch kubectl get pod -n kube-system
```

Configure kube-controller-scheduler for Prometheus. Change bind address from 127.0.0.1 to 0.0.0.0 on all control plane nodes one at a time.

```
sudo sed -e 's/--bind-address=127.0.0.1/--bind-address=0.0.0.0' -i /etc/kubernetes/manifests/kube-scheduler
```

Confirm kube-controller-scheduler pod restarts and is running before moving on to kube-proxy.

```
watch kubectl get pod -n kube-system
```

Configure kube-proxy for Prometheus. Change the metrics bind address from "" to "0.0.0.0" by editing the ConfigMap. Confirm kube-proxy pods restart and are running before moving on to etcd.

```
kubectl edit cm/kube-proxy -n kube-system
kubectl rollout restart daemonset.apps/kube-proxy -n kube-system
watch kubectl get pod -n kube-system
```

**Comment by IMAN-NAMJOOYAN** [comment]
> What is your environment? We are running k8s self-managed kubeadm install. I've set this up on my end. In my experience you have to configure the control plane resources so prometheus can scrape them. I actually just rebuilt our dev cluster and revised the setup notes. Here's what I have for the resources you mentioned. Use at your own risk.
> 
> Configure kube-controller-manager for Prometheus. Change bind address from 127.0.0.1 to 0.0.0.0 on all control plane nodes **one at a time**.
> 
> ```
> sudo sed -e 's/--bind-address=127.0.0.1/--bind-address=0.0.0.0' -i /etc/kubernetes/manifests/kube-controller-manager
> ```
> 
> Confirm kube-controller-manager pod restarts and is running **before moving on to the next control plane node**.
> 
> ```
> watch kubectl get pod -n kube-system
> ```
> 
> Configure kube-controller-scheduler for Prometheus. Change bind address from 127.0.0.1 to 0.0.0.0 on all control plane nodes **one at a time**.
> 
> ```
> sudo sed -e 's/--bind-address=127.0.0.1/--bind-address=0.0.0.0' -i /etc/kubernetes/manifests/kube-scheduler
> ```
> 
> Confirm kube-controller-scheduler pod restarts and is running **before moving on to the next control plane node or to kube-proxy**.
> 
> ```
> watch kubectl get pod -n kube-system
> ```
> 
> Configure kube-proxy for Prometheus. Change the metrics bind address from "" to "0.0.0.0" by editing the ConfigMap.
> 
> ```
> kubectl get configmap/kube-proxy -n kube-system -o yaml | \
> sed -e "s/metricsBindAddress: \"\"/metricsBindAddress: \"0.0.0.0\"/" | \
> kubectl apply -f -
> ```
> 
> Confirm kube-proxy pods restart and are running **before moving on to etcd**.
> 
> ```
> kubectl rollout restart daemonset.apps/kube-proxy -n kube-system
> watch kubectl get pod -n kube-system
> ```
> 
> Btw, Prometheus will need the following certs to scrape etcd.
> 
> * /etc/kubernetes/pki/etcd/ca.crt
> * /etc/kubernetes/pki/etcd/server.crt
> * /etc/kubernetes/pki/etcd/server.key

**Hi 
Thank you so much.**
