### ISSUE TITLE
Is there any demo for podmonitor?

### ISSUE THREAD

**Issue by ShenFeng312** [prometheus-operator/kube-prometheus#2015]
This repository now has the new GitHub Discussions enabled: 
https://github.com/prometheus-operator/kube-prometheus/discussions

Please create a new discussion to ask for any kind of support, which is not a Bug or Feature Request.

Thank you for being part of this community!

---

We are still happy to chat with you in the #prometheus-operator channel on Kubernetes Slack!

**Comment by simonpasquier** [comment]
see https://prometheus-operator.dev/docs/user-guides/getting-started/#using-podmonitors

**Comment by ShenFeng312** [comment]
> see https://prometheus-operator.dev/docs/user-guides/getting-started/#using-podmonitors

Thanks. It helps me a lot. But it's just too undetailed

**Comment by ShenFeng312** [comment]
@simonpasquier 
```apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: example-app
  labels:
    app: example-app
spec:
  selector:
    matchLabels:
      app: my-samples-provider
  podMetricsEndpoints:
    - port: http
      path: /metrics
  namespaceSelector:
    any: true
```
I try to use namespaceSelector.any = true.But it not work for me .how can I fix this

**Comment by simonpasquier** [comment]
There can be lots of reasons. Check https://prometheus-operator.dev/docs/operator/troubleshooting/#troubleshooting-servicemonitor-changes and the logs of the Prometheus operator.
