### ISSUE TITLE
ClusterRoles and ClusterRoleBindings should not be namespaced

### ISSUE THREAD

**Issue by fculpo** [prometheus-operator/kube-prometheus#2016]
Our GitOps agent refuses to apply CR and CRB as they are not valid

Error is "resource is cluster-scoped but has a non-empty namespace monitoring")

Some affected objects:

- rbac.authorization.k8s.io-v1.ClusterRole-monitoring-prometheus-k8s.yaml
- rbac.authorization.k8s.io-v1.ClusterRole-monitoring-resource-metrics-server-resources.yaml
- rbac.authorization.k8s.io-v1.ClusterRoleBinding-monitoring-node-exporter.yaml
- ...

The "bug" seems to be there, at least for the node exporter component:

https://github.com/prometheus-operator/kube-prometheus/blob/e435c1d6401b232f308f4e53c56d130299640d37/jsonnet/kube-prometheus/components/node-exporter.libsonnet#L89

The referenced _metadata{} has a namespace value

https://github.com/prometheus-operator/kube-prometheus/blob/e435c1d6401b232f308f4e53c56d130299640d37/jsonnet/kube-prometheus/components/node-exporter.libsonnet#L61-L65

Can this be fixed ? (possibly backported - we currently use release 0.10 on 1.22/1.23 clusters)

Thanks

**Comment by simonpasquier** [comment]
Interesting, there's indeed room for improvement :)
Would you like to contribute the patch?

**Comment by fculpo** [comment]
Well I can look into it. This of course needs to be fixed in the components lib directly if rendering a clusterRoleXXX object

**Comment by simonpasquier** [comment]
Is there anything else to do than nullify the `namespace` field for clusterrolebinding objects?

**Comment by fculpo** [comment]
Both clusterrole and clusterrolebinding should not be namespaced.

Only seems to occur in the 3 components I patched.

**Comment by btorresgil** [comment]
Created a fix for this in PR #2158. Open to feedback.
