### ISSUE TITLE
stat /bin/prometheus-config-reloader: no such file orr directory: unknown

### ISSUE THREAD

**Issue by justinmans** [prometheus-operator/kube-prometheus#2050]
k8sveriosn：1.20.1
![image](https://user-images.githubusercontent.com/42922475/226388981-13d79db6-64c2-463b-9273-cfe7dfe4b8d9.png)

kube-prometheus:0.8
kube-prometheus-release-0.8

我在安装的时候
![image](https://user-images.githubusercontent.com/42922475/226390041-f5284238-96bb-4fd0-9661-db716400b89d.png)

发现promethues的资源对象提示缺少文件，但是我的镜像来自镜像仓库pull的
报错情况如下：
![image](https://user-images.githubusercontent.com/42922475/226390925-7d631641-ec3c-4a47-b724-b4f57370caa0.png)

希望能够得到帮助，我需要提供什么

**Comment by justinmans** [comment]
Container image "10.129.1.25:1603/prometheus/prometheuis:v2.26.0" already present on machine
Created container prometheus
Started container prometheus
Container image "10.129.1.25:1603/prometheus/prometheuis-operator:v0.47.0" already present on machine
Created container config-reloader
Error: failed to start container "config-reloader": Error response from daemon: failed to create shim: OCI rcuntime create
failed: container linux.go:380:
starting container process caused: exec: "/bin/prometheus-config-reloader": stat/bin/prometheus-config-reloader: no such file or directsory: unknown

**Comment by biggercousin** [comment]
I encountered this problem when upgrading, and I don't know how to solve it

**Comment by zhengxin152327** [comment]
0.13 same

**Comment by yangdatianxia** [comment]
my k8s version is 1.28
my kube-prometheus version is 0.13
![image](https://github.com/prometheus-operator/kube-prometheus/assets/28724448/def8da2b-6195-4b47-a4a7-4caf0a8016f4)

I can't find any logs about alertmanager
![image](https://github.com/prometheus-operator/kube-prometheus/assets/28724448/c1aaafc3-7a06-4b71-bd0b-d591bacf019f)
describe pod is:

![image](https://github.com/prometheus-operator/kube-prometheus/assets/28724448/670ec9d3-9019-4e62-9b8e-01035796743e)

**Comment by SeiketsuJael** [comment]
Any progress on this issue, I can see the reloader image has the bin/prometheus-config-reloader file but when it is deployed in a pod, it cannot find it.
![image](https://github.com/prometheus-operator/kube-prometheus/assets/40410824/c9b2d3ce-67f9-4d76-88e2-bc50b2d1431c)
