### ISSUE TITLE
Windows.pod.rules using incorrect job name when windows-exporter deployed as a DS

### ISSUE THREAD

**Issue by marosset** [prometheus-operator/kube-prometheus#2054]
**What happened?**
I set up the kube-prometheus stack in a Kubernetes cluster and enabled the Windows addon (following [this guide](https://github.com/prometheus-operator/kube-prometheus/blob/main/docs/windows.md)) and then deployed the windows-exporter to the cluster (following [this guide](https://github.com/prometheus-community/windows_exporter/blob/master/kubernetes/kubernetes.md) which deploys the exporter as a daemonSet).

After running a few pods in the cluster I noticed that metrics for the Windows containers weren't being reported.
After some digging I found that all of the `windows.pod.rules` were using a job named **kubernetes-windows-exporter** and after changing the rules to use a job named **monitoring/windows-exporter** metrics started showing up as expected.

I traced the default job name to https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/ff4a78a828279258eaf5b1f0fa1c8f2a974d3766/config.libsonnet#L32 

At this point I'm unsure what the best way to fix this issue is because I am not familiar with all the different components at play here.
Some options I'm considering are

1. Update the [default windowsExporterSelector job name to monitoring/windows-exporter](https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/config.libsonnet#L32 in the kubernetes-mixin GH repo
1. Update the Windows related [docs](https://github.com/prometheus-operator/kube-prometheus/blob/main/docs/windows.md) and [windows.jsonnet]( https://github.com/prometheus-operator/kube-prometheus/blob/main/examples/windows.jsonnet) example config to set windowsExporterSelector to monitoring/windows-exporter
1. Update the [docs](https://github.com/prometheus-community/windows_exporter/blob/master/kubernetes/kubernetes.md) in the prometheus-community/windows-exporter repo to note that the windowsExporterSelector value should be set to monitoring/windows-exporter _if_ deploying the windows-exporter as a daemonSet and using the supplied [windows-exporter-podmonitor](https://github.com/prometheus-community/windows_exporter/blob/master/kubernetes/windows-exporter-podmonitor.yaml) deployment file 

**How to reproduce it (as minimally and precisely as possible)**:

See above

**Environment**

* Prometheus Operator version:

   main - commit `c984288cc339fa0454dce05fcf1d6b95875a7073`

* Kubernetes version information:

    1.27.rc-0

* Kubernetes cluster kind:

    N/A

* Manifests:

  N/A

* Prometheus Operator Logs:
   
  N/A

* Prometheus Logs:

  N/A

**Anything else we need to know?**:

![image](https://user-images.githubusercontent.com/18291632/227645441-f66af208-ccda-486c-834a-ee14ccd36613.png)

**Comment by dineshsharmads** [comment]
@marosset if it helps, I have raised a pull request ( #2048 ) to add an additional addon which implements windows-exporter as DS. Also adds example and documentation for it as you noted in point 2.

It sets the job name in dashboard and rules as provided by user.

**Comment by philipgough** [comment]
Closing based on linked PR being merged
