### ISSUE TITLE
prometheus的statefulset修改无效

### ISSUE THREAD

**Issue by Xuejicha0** [prometheus-operator/kube-prometheus#2087]
为什么 prometheus的statefulset修改无效呢，求大佬解惑

**Comment by AliDev0ps** [comment]
You should do this by customizing jsonnet, rather than modifying the generated k8s manifests !
Or you can describe in detail the function you want to modify

**Comment by slashpai** [comment]
Could you please give details what you are trying to do?

**Comment by chauncyAAA** [comment]
需要在prometheus的deployment中加变量，修改statefulset是无效的

**Comment by Xuejicha0** [comment]
我就是想修改 prometheus的存储时长，直接修改k8s 中的statefulset 无效，还是15天，需要修改 prometheus-prometheus.yaml
在配置文件下面添加   retention: 60d
