### ISSUE TITLE
How are the alertmanagers being configured in the Prometheus operator?

### ISSUE THREAD

**Issue by davidhwang-anthropic** [prometheus-operator/kube-prometheus#2091]
The prometheus operator defaults it's `alertmanagers` to be 
```
          namespace: p._config.namespace,
          name: 'alertmanager-' + p._config.alertmanagerName,
          port: 'web',
          apiVersion: 'v2',
```

See https://github.com/prometheus-operator/kube-prometheus/blob/main/jsonnet/kube-prometheus/components/prometheus.libsonnet#L349.

Looking at the documentation, I don't actually see that configuration option for `alertmanagers`. https://prometheus.io/docs/prometheus/latest/configuration/configuration/#alertmanager_config

On gut, this seems like a label selector or is the name of the sts. Is there something I'm missing here? Possibly I'm looking at the wrong part of the docs?

**Comment by AliDev0ps** [comment]
This is the CRD resource for the prometheus operator, you should refer to :
- https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1.AlertingSpec
- `kubectl explain Prometheus.spec.alerting.alertmanagers`
