### ISSUE TITLE
enable grafana anonymous access

### ISSUE THREAD

**Issue by jia2** [prometheus-operator/kube-prometheus#210]
My question is, how could I integrate the generated grafana config in grafana-deployment.yaml? 

**What did you do?**
I did a customization for enabling grafana anonymous access like this:

 ```yaml
 {
    _config+:: {
      namespace: 'monitoring',
      grafana+:: {
          config: { // http://docs.grafana.org/installation/configuration/
            sections: {
              "auth.anonymous": {enabled: true},
            },
          },
        },
    },

  };
```
A grafana-config.yaml is generated correctly.

**Did you expect to see some different?**
I had expected that this secret is used in grafana deployment descriptor, grafana-deployment.yaml, but it seems not.

**Environment**

* Prometheus Operator version:

    `prometheus-operator:v0.29.0`

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-eks-5ac0f1", GitCommit:"5ac0f1d9ab2c254ea2b0ce3534fd72932094c6e1", GitTreeState:"clean", BuildDate:"2019-08-20T22:39:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}`
   
* Kubernetes cluster kind:

    I use AWS EKS 1.13.8

I appreciate for any help.

Thanks
Dingjun

**Comment by blandflakes** [comment]
I did similar and did get find that the config was referenced under `volumes` in my `grafana-deloyment.yaml`:

      - name: grafana-config
         secret:
           secretName: grafana-config

**Comment by brancz** [comment]
Yes what @blandflakes said is what should happen.
