### ISSUE TITLE
nodeport无法访问

### ISSUE THREAD

**Issue by 008-2021** [prometheus-operator/kube-prometheus#2106]
clusterIP: 10.110.56.206
  clusterIPs:
  - 10.110.56.206
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 31509
    port: 3000
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

grafana-service.yaml中的type类型改为NodePort后，其他机器无法访问

**Comment by AliDev0ps** [comment]
Check if your network plug-in supports network policies?

If the network plugin supports NetworkPolicy, you need to delete or modify NetworkPolicy with Grafana！

**Comment by 008-2021** [comment]
> Check if your network plug-in supports network policies?
> 
> If the network plugin supports NetworkPolicy, you need to delete or modify NetworkPolicy of Grafana！

您好，我单独部署了一个nginx的例子，然后用nodeport方式暴露端口，是可以访问的

**Comment by 008-2021** [comment]
> Check if your network plug-in supports network policies?
> 
> If the network plugin supports NetworkPolicy, you need to delete or modify NetworkPolicy of Grafana！

Hello, thank you for your answer. The problem has been resolved。thank you!
