### ISSUE TITLE
Harcoded namespcae in Alertmanagr rules

### ISSUE THREAD

**Issue by Shm013** [prometheus-operator/kube-prometheus#2108]
Hello!

I found that all alerts in [alertmanager-prometheusRule.yaml](https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/alertmanager-prometheusRule.yaml) has hardcoded namespace `monitoring`.

For example

```
  expr: |
        # Without max_over_time, failed scrapes could create false negatives, see
        # https://www.robustperception.io/alerting-on-gauges-in-prometheus-2-0 for details.
        max_over_time(alertmanager_config_last_reload_successful{job="alertmanager-main",namespace="monitoring"}[5m]) == 0
```

If I'll install helm chart in other namespace, this rules will not work. Can you remove this clause from expressions or use parameter in there?

**Comment by IceWreck** [comment]
This isn't a helm chart this is kube-prometheus which uses jsonnet. The file you linked is a generated file and is simply the default configuration.

If you wish to customize it, you can do so by defining your customizations in jsonnet. (look at the README)
