### ISSUE TITLE
prometheus operator is throughing error """" unknown long flag '--kubelet-service'  """"

### ISSUE THREAD

**Issue by Tushar5525** [prometheus-operator/kube-prometheus#2114]
![image](https://github.com/prometheus-operator/kube-prometheus/assets/14202465/1e2e7a14-bc2a-4f4e-865f-1ecbf8509b24)

**Comment by CHYhave** [comment]
hey have you resolved is ?

**Comment by slashpai** [comment]
what version of prometheus-operator are you using?
