### ISSUE TITLE
node_exporter cpu request

### ISSUE THREAD

**Issue by rkojedzinszky** [prometheus-operator/kube-prometheus#214]
**What did you do?**
Just observed, that node_exporter has 102m cpu request. What is the real reason behind 102m ?

**Did you expect to see some different?**
I expected to see a rounded value there, either 100m or 10m.

**Environment**
General.

**Comment by brancz** [comment]
No reason that I can remember. Happy to have it be an even number if you want to change it.

**Comment by omerlh** [comment]
I'm noticing that 102m is not enough for node_exporter, and it might need something around 800m or even more, am I the only one experiencing it?

**Comment by brancz** [comment]
wow, that is quite a lot, do you happen to have any special collectors running?

**Comment by omerlh** [comment]
Nope, using vanilla configuration as provided by kube-prometheus and latest version...

**Comment by rkojedzinszky** [comment]
Strange. On my pi boards node_exporters consume 0.02 cpu per node.

Regards,

2020. február 3. 10:50:59 CET, Omer Levi Hevroni <notifications@github.com> írta:
>Nope, using vanilla configuration as provided by kube-prometheus and
>latest version...
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/coreos/kube-prometheus/issues/214#issuecomment-581327827

-- 
Ezt a levelet az Android készülékemről küldtem K-9 Mail-el. Elnézést a tömörségemért.

**Comment by omerlh** [comment]
I actually had to increase resources to solve throttling issue, so the discussion should move to /kubernetes-monitoring/kubernetes-mixin#108

**Comment by paulfantom** [comment]
CPUThrottlingHigh is now only an `info`-level alert and should be inhibited if nothing else is firing. We have an issue in https://github.com/prometheus-operator/kube-prometheus/issues/861 tracking adding such inhibition.

I would advise increasing resource requirements only if you see that node_exporter scrapes are taking too long. In other cases, there is nothing to be worried about.
