### ISSUE TITLE
Update node-exporter mixin

### ISSUE THREAD

**Issue by jcpunk** [prometheus-operator/kube-prometheus#2157]
**What is missing?**
https://github.com/prometheus/node_exporter/pull/2644

**Why do we need it?**
These are the current rules provided by the node-exporter project

**Environment**

* kube-prometheus version:

    `858a2a53f42720a8baa048de5984835deb59328d`

**Anything else we need to know?**:

**Comment by slashpai** [comment]
This is done with auto update of versions https://github.com/prometheus-operator/kube-prometheus/pull/2155/files#diff-0dd35d5d72076cc82c635c93bea51a569896fa20c909d054f3263cbf2a973e02 :)
