### ISSUE TITLE
metadata.annotations: Too long

### ISSUE THREAD

**Issue by msillence** [prometheus-operator/kube-prometheus#2179]
**What happened?**
I was following the instructions on https://strimzi.io/docs/operators/latest/deploying.html#proc-metrics-deploying-prometheus-operator-str

Installing the "bundle.yaml" I get the following two errors:

```
Error from server (Invalid): error when creating "prometheus-operator-deployment.yaml": CustomResourceDefinition.apiextensions.k8s.io "prometheusagents.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
Error from server (Invalid): error when creating "prometheus-operator-deployment.yaml": CustomResourceDefinition.apiextensions.k8s.io "prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

**Did you expect to see some different?**

**How to reproduce it (as minimally and precisely as possible)**:

This 

**Environment**

Google Cloud

* Prometheus Operator version:

master - SHA 2f756fa

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"27"
Server Version: version.Info{Major:"1", Minor:"26",

* Kubernetes cluster kind:

   GCP kubernetes installed using terraform

**Comment by philipgough** [comment]
https://github.com/prometheus-operator/prometheus-operator/issues/5104#issuecomment-1281824624
