### ISSUE TITLE
Release 0.13 not available yet

### ISSUE THREAD

**Issue by robert-heinzmann-logmein** [prometheus-operator/kube-prometheus#2180]
Currently there is still no 0.13 release. People wanting to update to  k8s 1.26 are somehow either unsupported with 0.12 OR need to use main, which might be unstable. 

Would be great of 0.13 would be available.

**Comment by philipgough** [comment]
@robert-heinzmann-logmein - ack, will take care of this next week. Releases were typically tied to OpenShift releases but some changes there meant it no longer depends on a release branch. We may start releasing per Kube release if the appetite is there which it appears to be. I'll bring it up for discussion in the next meeting!

**Comment by rajatvig** [comment]
Is the release still planned? Dependencies in `main` are all set to `main` for other repositories which makes it awkward to consume the library for 1.26.

**Comment by philipgough** [comment]
Yep, it is, sorry for the lag. I have a draft here waiting for review https://github.com/prometheus-operator/kube-prometheus/pull/2210

**Comment by thiDucTran** [comment]
seems k8s version 1.26 will not be supported for release 0.13?

**Comment by philipgough** [comment]
> seems k8s version 1.26 will not be supported for release 0.13?



Correct, but that has always been the case. See https://github.com/prometheus-operator/kube-prometheus/blob/main/RELEASE.md#update-kubernetes-supported-versions

**Comment by robert-heinzmann-logmein** [comment]
Interestingly there is actually no supported 1.26 release of kube-prometheus then. While I think this is practically not an issue, as there are no deprecated API's in 1.26 (See https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-26), it looks kind of strange. Is it hard to add CI/CD for 3 releases this time ?

**Comment by philipgough** [comment]
Its a good point. Historically the releases were tied to OpenShift, but the branching strategy changed there so the project no longer needed a release branch.

What I'll do is try to make an exception this time and include the last 3 release and going forward try to release with Kubernetes releases and the last two versions supported. How does that sound?

**Comment by philipgough** [comment]
Done https://github.com/prometheus-operator/kube-prometheus/releases/tag/v0.13.0

**Comment by yangdatianxia** [comment]
hello，can you help me look look my problem:
https://github.com/prometheus-operator/kube-prometheus/issues/2276

**Comment by yangdatianxia** [comment]
hello，Can you help me look look my problem:
https://github.com/prometheus-operator/kube-prometheus/issues/2276 , my alertmanager-main-0 pod keeps restarting
