### ISSUE TITLE
external target didnʼt show up

### ISSUE THREAD

**Issue by kural82** [prometheus-operator/kube-prometheus#2193]
Hi there,
I deployed the kube-prometheus-stack-48.1.1 Helm chart to AKS using Terraform. To monitor my external application outside the cluster, I added an additional service monitor in the values.yaml file. However, despite Terraform not throwing any errors, it didn't create the new service monitor.

prometheusOperator:
  serviceMonitorSelectorNilUsesHelmValues: true
  serviceMonitorNamespaceSelector:
    matchNames:
      - default

additionalServiceMonitors:
  - name: external-website-monitor
    namespace: default
    selector:
      matchLabels:
        app: external-website
    endpoints:
      - port: http-metrics
        interval: 30s
        path: /metrics
        scheme: https       
        relabelings:
          - sourceLabels: [__address__]
            targetLabel: __param_target
          - sourceLabels: [__param_target]
            targetLabel: instance
          - targetLabel: __address__
            replacement: https:example.com
Any help would be appreciated .
Thanks in advance.

**Comment by philipgough** [comment]
Hi, this project does not use or leverage helm in any way. Probably best to raise that over on https://github.com/prometheus-community/helm-charts
