### ISSUE TITLE
`jb install ...` is currently broken because pyrra is not pinned (pyrra 0.7 release)

### ISSUE THREAD

**Issue by jgehrcke** [prometheus-operator/kube-prometheus#2224]
In

https://github.com/prometheus-operator/kube-prometheus/blob/8ce7838d24537a276a684da3f1fe5ffc08bfd495/jsonnetfile.lock.json#L150

we define

```
    {
      "source": {
        "git": {
          "remote": "https://github.com/pyrra-dev/pyrra.git",
          "subdir": "config/crd/bases"
        }
      },
      "version": "8ef5703723f0a4079d7d9ad15ca1fb6bda430a8e",
      "sum": "v0uv2DLx8qjW+OviUfzTFOzZ+0IizXqBhuglGHIhGmo="
    },
```

That version indeed contains the `config/crd/bases` directory:

https://github.com/pyrra-dev/pyrra/tree/8ef5703723f0a4079d7d9ad15ca1fb6bda430a8e/config/crd/bases

@metalmatze has 14 hours ago commited https://github.com/pyrra-dev/pyrra/commit/f2052cce0c848bb8c4c4d5d964a97b5038237487 which seems to have removed the `config/*` directory tree from the repo.

Now, despite kube-prometheus's jsonnetfile.lock.json specifying `8ef570` during the jsonnet build we see the the build fetching the current HEAD of main:

```
GET https://github.com/pyrra-dev/pyrra/archive/f2052cce0c848bb8c4c4d5d964a97b5038237487.tar.gz 200
panic: rename vendor/.tmp/jsonnetpkg-github.com-pyrra-dev-pyrra-config-crd-bases-main336769959/config/crd/bases vendor/github.com/pyrra-dev/pyrra/config/crd/bases: no such file or directory
```

Specifically, this error happens during running

```
jb install github.com/prometheus-operator/kube-prometheus/jsonnet/kube-prometheus@7fafc4cadc1
```

which is a [documented way](https://github.com/prometheus-operator/kube-prometheus/blob/main/docs/customizing.md#installing) to initiate the jsonnet build (which we use in our CI).

Why would the JSONNET build fetch the HEAD of main of `pyrra-dev/pyrra` instead of the specified commit? We seem to have a second reference to pyrra in the kube-prometheus repo, and indeed it's a moving target:

```
    {
      "source": {
        "git": {
          "remote": "https://github.com/pyrra-dev/pyrra.git",
          "subdir": "config/crd/bases"
        }
      },
      "version": "main"
    },
```

That definition [lives in](https://github.com/prometheus-operator/kube-prometheus/blob/8ce7838d24537a276a684da3f1fe5ffc08bfd495/jsonnet/kube-prometheus/jsonnetfile.json#L114) `jsonnet/kube-prometheus/jsonnetfile.json`.

Obvious question: what  is the separation of concerns is between

- `jsonnetfile.lock.json`
- `jsonnet/kube-prometheus/jsonnetfile.json`

?

As a quick resolution we should probably pin pyrra to a specific commit in `jsonnet/kube-prometheus/jsonnetfile.json`.

**Comment by jgehrcke** [comment]
For the record, there is a third reference to pyrra, pointing to the 0.6.4 release: https://github.com/prometheus-operator/kube-prometheus/blob/8ce7838d24537a276a684da3f1fe5ffc08bfd495/jsonnet/kube-prometheus/versions.json#L12.

**Comment by jgehrcke** [comment]
I have adjusted the title. Of course the maintainers here have the more credible opinion, but if I understand correctly this breaks `jb install ...` for all versions of kube-prometheus, because in the past they have all referred to this pyrra moving target (which has rarely moved, until now). Obviously we can patch `kube-prometheus` in that regard, but maybe we should also think of all those systems that try to rely on older versions of kube-prometheus being `jb install`able. Maybe that demands a more creative solution CC @metalmatze.

**Comment by jgehrcke** [comment]
We run `jb install ...` in https://quay.io/repository/coreos/jsonnet-ci. I was considering that the version of  `jb` baked into that image is too old.

I reproduced without coreos/jsonnet-ci:

```
$ jb --version
0.4.0
$ jb install github.com/prometheus-operator/kube-prometheus/jsonnet/kube-prometheus@7fafc4cadc1
GET https://github.com/prometheus-operator/kube-prometheus/archive/.tar.gz 404
...
HEAD is now at 7fafc4ca Release sync - v0.13.0 (#2215)
GET https://github.com/brancz/kubernetes-grafana/archive/5698c8940b6dadca3f42107b7839557bc041761f.tar.gz 200
GET https://github.com/grafana/grafana/archive/1120f9e255760a3c104b57871fcb91801e934382.tar.gz 200
GET https://github.com/prometheus-operator/prometheus-operator/archive/ea8968b99e48bf7a759d1c6e9006755eb38f2798.tar.gz 200
GET https://github.com/kubernetes/kube-state-metrics/archive/b91dd311397047f15aae4f6dacba0708f24cf446.tar.gz 200
GET https://github.com/prometheus/node_exporter/archive/e8c5110ada6152ec0efb8b2dc8be7e493624d232.tar.gz 200
GET https://github.com/prometheus/prometheus/archive/a3f424641a9eb468da71ac14c3a7c1ef168a45a0.tar.gz 200
GET https://github.com/prometheus/alertmanager/archive/c6be0bcabf37e837d24786e3d5c10565ac499531.tar.gz 200
GET https://github.com/etcd-io/etcd/archive/55253cee1b57eddef7f2199b5c4208874abc5959.tar.gz 200
GET https://github.com/prometheus-operator/prometheus-operator/archive/ea8968b99e48bf7a759d1c6e9006755eb38f2798.tar.gz 200
GET https://github.com/kubernetes-monitoring/kubernetes-mixin/archive/31169fd115654ca023c03cd7b45b9c96704a87e2.tar.gz 200
GET https://github.com/kubernetes/kube-state-metrics/archive/b91dd311397047f15aae4f6dacba0708f24cf446.tar.gz 200
GET https://github.com/pyrra-dev/pyrra/archive/f2052cce0c848bb8c4c4d5d964a97b5038237487.tar.gz 200
panic: rename /tmp/vendor/.tmp/jsonnetpkg-github.com-pyrra-dev-pyrra-config-crd-bases-main3821615403/config/crd/bases /tmp/vendor/github.com/pyrra-dev/pyrra/config/crd/bases: no such file or directory

goroutine 1 [running]:
panic({0x55e3f8e947c0, 0xc000322000})
...
```

**Comment by jgehrcke** [comment]
Interesting, this resolves the expected pyrra version:

```
± jb install jsonnet/kube-prometheus/
LOCAL kube-prometheus -> /home/jp/dev/kube-prometheus/jsonnet/kube-prometheus
...
GET https://github.com/pyrra-dev/pyrra/archive/8ef5703723f0a4079d7d9ad15ca1fb6bda430a8e.tar.gz 200
```

(when running `jb install ...` _in_ a local kube-prometheus checkout).

**Comment by jgehrcke** [comment]
Okay, I think this direct comparison is highly interesting:

### jb install from local checkout (commit 8ce7838)

```
$ pwd
/home/jp/dev/kube-prometheus
$ git rev-parse HEAD
8ce7838d24537a276a684da3f1fe5ffc08bfd495
$ jb install
...
GET https://github.com/pyrra-dev/pyrra/archive/8ef5703723f0a4079d7d9ad15ca1fb6bda430a8e.tar.gz 200
...
```


### jb install from remote (also commit 8ce7838)

```
$ pwd
/tmp
$ rm -rf vendor && jb install github.com/prometheus-operator/kube-prometheus/jsonnet/kube-prometheus@8ce7838d24
...
HEAD is now at 8ce7838d [bot] [main] Automated version update (#2223)
...
GET https://github.com/pyrra-dev/pyrra/archive/f2052cce0c848bb8c4c4d5d964a97b5038237487.tar.gz 200
panic: rename /tmp/vendor/.tmp/jsonnetpkg-github.com-pyrra-dev-pyrra-config-crd-bases-main2953392027/config/crd/bases /tmp/vendor/github.com/pyrra-dev/pyrra/config/crd/bases: no such file or directory
...
```

**Comment by jgehrcke** [comment]
I noticed that pyrra is not yet a named dependency. Over time, we seem to have started to name dependencies:
- https://github.com/prometheus-operator/kube-prometheus/pull/1050
- https://github.com/prometheus-operator/kube-prometheus/issues/827

But that might also be unrelated.

**Comment by jgehrcke** [comment]
For our CI I have for now switched to the "jb install from local checkout" method. However, I clearly lack some more puzzle pieces here and I would be grateful for feedback. After all, we may want to adjust the docs that show the 'jb install from remote' method, or add a patch that makes it so that that method also adheres to the version pin.

**Comment by jibinrajck** [comment]
+1 

@jgehrcke - Thanks for your tip to install from local.

**Comment by philipgough** [comment]
thanks @jgehrcke - cc @metalmatze

**Comment by metalmatze** [comment]
Yeah. Sorry. I think we might want to pin the release-0.6 branch until I open the PR to properly integrate Pyrra soon.

For now, I need to finish the PromCon. 😂
