### ISSUE TITLE
Alertmanager pods stuck in terminating loop with healthy start up logs (We have two operators in multiple namespaces)

### ISSUE THREAD

**Issue by aca8089** [prometheus-operator/kube-prometheus#2226]
We have multiple operators running in two namespaces and only one namespace have the alertmanager configured which is stuck in the terminating loop. So needs to know if we can fix this issue without deleting another operator.

**Comment by aca8089** [comment]
Hi, Anyone had a chance to look on this and support me in this case ?

**Comment by simonpasquier** [comment]
please see https://prometheus-operator.dev/docs/operator/troubleshooting/#prometheusalertmanager-pods-stuck-in-terminating-loop-with-healthy-start-up-logs

**Comment by aca8089** [comment]
@simonpasquier Is it possible to run two operators in different namespaces ? Because we have an operator running in another namespace with their own values.

So we are trying to setup operator in another namespace with our customized values instead of disturbing other one.

**Comment by simonpasquier** [comment]
It's possible but you need to make sure that the operators don't watch for resources in the same namespaces. Usually you would use the `-namespaces` CLI argument to restrict a given operator to a set of namespaces.

**Comment by simonpasquier** [comment]
pls share the deployment manifests for both operators.
