### ISSUE TITLE
Dashboards & users getting deleted

### ISSUE THREAD

**Issue by akashsethiya** [prometheus-operator/kube-prometheus#223]
I deployed the kube-prometheus on gke and created some new dashboard & users.
But after sometime whenever the pod restarts they disappear and its goes back to state like its freshly installed.

what could be the problem here?

**Comment by blandflakes** [comment]
This is deliberate (which I find unfortunate, but that's ok). Check out this issue:
https://github.com/brancz/kubernetes-grafana/issues/54

tl;dr: the grafana deployment is designed such that you should let another system manage auth, and such that dashboards are committed as YAML and deployed. In other words, it is stateless.

So, the state for grafana is a local dir that, as you've observed, is blown away when a pod is rescheduled.

How do you solve this? I'd use either some SAAS database (Cloud SQL) or an in-cluster Postgres instances (we did the latter, which "solved" this for us) and override the grafana config for the database.

**Comment by akashsethiya** [comment]
@blandflakes Thanks. Will try postgres

**Comment by metalmatze** [comment]
We advocate on running this Grafana purely for cluster metrics. For everything else it should be not too hard to run a separate Grafana with Postgres as example.

**Comment by brancz** [comment]
I generally recommend to manager _all_ grafana dashboards through config files and keep it completely stateless.

**Comment by paulfantom** [comment]
Closing due to staleness. Please reopen if you think this is still relevant.
