### ISSUE TITLE
Deprecated Metric Usage

### ISSUE THREAD

**Issue by AuHoppe** [prometheus-operator/kube-prometheus#2264]
**Issue:**
The v2 release of `kube-state-metrics` removes several deprecated metrics, one [with usage](https://github.com/prometheus-operator/kube-prometheus/blob/main/jsonnet/kube-prometheus/addons/weave-net/grafana-weave-net-cluster.json#L3138) here.

**Additional Context:**
Referenced at: https://github.com/kubernetes/kube-state-metrics/blob/release-1.9/docs/README.md#metrics-deprecation

**Resolution:**
`jsonnet/kube-prometheus/addons/weave-net/grafana-weave-net-cluster.json` should be updated with the new form of `kube_node_status_capacity_pods`:
`kube_node_status_capacity_pods` ~ `kube_node_status_capacity{resource="pods",unit="integer"}`

**Comment by philipgough** [comment]
Thanks. Do you want to have a go and creating the fix?
