### ISSUE TITLE
grafana 10.2.0 fails to start

### ISSUE THREAD

**Issue by pschulten** [prometheus-operator/kube-prometheus#2267]
**What happened?**
Installed the latest version from main. with https://github.com/prometheus-operator/kube-prometheus/pull/2262 grafana got updated to `grafana/grafana:10.2.0` and fails to run with errors:
```
logger=dashboard-service t=2023-11-14T08:53:29.804106559Z level=error msg="Could not make user admin" dashboard="Kubernetes / Networking / Pod" namespaceID=user userID=0 error="identifier is not initialized"
logger=dashboard-service t=2023-11-14T08:53:29.815184303Z level=error msg="Could not make user admin" dashboard="Grafana Overview" namespaceID=user userID=0 error="identifier is not initialized"
logger=dashboard-service t=2023-11-14T08:53:29.833243335Z level=error msg="Could not make user admin" dashboard="Kubernetes / Compute Resources / Cluster" namespaceID=user userID=0 error="identifier is not initialized"
```

**How to reproduce it (as minimally and precisely as possible)**:
Install latest version

**Environment**

* Prometheus Operator version:

    `quay.io/prometheus-operator/prometheus-operator:v0.69.1`

* Kubernetes version information:

    `Server Version: v1.28.3`

* Kubernetes cluster kind:

    kubeadm

**Comment by richzhu369** [comment]
i got same problem , did you resolve it ?

**Comment by philipgough** [comment]
Looks like this is related to https://github.com/grafana/grafana/issues/77211

**Comment by philipgough** [comment]
@pschulten I've merged https://github.com/prometheus-operator/kube-prometheus/pull/2317 to `main` which includes `10.2.3`. Please let me know if this is still a problem!

**Comment by pschulten** [comment]
sorry for the delay, yes that works, thanks!
