### ISSUE TITLE
如何给prometheus添加一个全局标签呢（external_labels）

### ISSUE THREAD

**Issue by 1015688170** [prometheus-operator/kube-prometheus#2275]
global:
  external_labels:
    additional_label: "value"
如何把这个配置加到prometheus.yml中呢

**Comment by yangdatianxia** [comment]
你用的版本是kube-prometheus0.13版本吗，我一直得alertmanager一直在重启不知道为什么

**Comment by wilsontly** [comment]
kubectl edit sts -n monitoring prometheus-k8s?

**Comment by 1015688170** [comment]
> 你用的版本是kube-prometheus0.13版本吗，我一直得alertmanager一直在重启不知道为什么

我用的是0.12的

**Comment by 1015688170** [comment]
> kubectl edit sts -n 监控 prometheus-k8s？

在线调整不了，目前找到了解决方式，在prometheus-prometheus.yaml文件中增加内容
externalLabels: 
    cluster: {cluster}

**Comment by desperadoccy** [comment]
> 你用的版本是kube-prometheus0.13版本吗，我一直得alertmanager一直在重启不知道为什么

你可能修改了monitoring 中secret 的 alertmanager-main中的配置，具体查看pod重启的日志

**Comment by yang-maple** [comment]
> > kubectl edit sts -n 监控 prometheus-k8s？
> 
> 在线调整不了，目前找到了解决方式，在prometheus-prometheus.yaml文件中增加内容 externalLabels: cluster: {cluster}

你好 为啥我这边添加后 这个字段没有生效啊
