### ISSUE TITLE
My alertmanager-main-0 pod keeps restarting

### ISSUE THREAD

**Issue by yangdatianxia** [prometheus-operator/kube-prometheus#2276]
my alertmanager-main pod  keeps restarting
my k8s version is1.28.4
my kube-prometheus version is 0.13
When I executed "kubectl apply -f  manifests/setup/" and "kubectl apply -f  manifests/"
![image](https://github.com/prometheus-operator/kube-prometheus/assets/28724448/ea18ab03-4e47-467e-963e-393b02b79ee0)
my cluster info :
![image](https://github.com/prometheus-operator/kube-prometheus/assets/28724448/5b423399-f01f-40ba-bdfa-55dd72321693)

When I executed  "kubectl describe pod -n monitoring    alertmanager-main-0"
![image](https://github.com/prometheus-operator/kube-prometheus/assets/28724448/7daacec5-0d3f-4b3d-9c81-1e65bcbb26f5)

When I executed  "kubectl logs -f  -n monitoring    alertmanager-main-0"
![image](https://github.com/prometheus-operator/kube-prometheus/assets/28724448/4c28de4d-f8ff-489c-a435-1c33fad1a3f9)

I don't find any obout loginfo

**Comment by wilsontly** [comment]
可能是alertmanager还没启动完成，但就绪指针探测状态不正常就又重启了，可以尝试将readiness和liveness的时间加长一点

**Comment by yangdatianxia** [comment]
不确定了，这个问题我已经解决了，把所有的node和多余的master节点全部都踢掉，然后装0.13得kube-prometheus就没有问题，然后再把其他节点加入进来即可，但是不确定这是个bug还是啥

**Comment by DangNguyen146** [comment]
When I set replicaset in `manifests/alertmanager-alertmanager.yaml=1` and run pod in master 
`kubectl taint nodes --all node-role.kubernetes.io/control-plane-`
, `alertmanager-main-0` is run complete.
But it is only a temporary way to put out the fire!
Do you have any current way to solve it?
