### ISSUE TITLE
9100/metrics: context deadline exceeded

### ISSUE THREAD

**Issue by anstns** [prometheus-operator/kube-prometheus#232]
**What happened?**

**Did you expect to see some different?**

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
Insert Prometheus Operator logs relevant to the issue here
```

* Prometheus Logs:
ERROR: logging before flag.Parse: I0923 08:03:18.088750       1 pod_nanny.go:65] Invoked by [/pod_nanny --container=kube-state-metrics --cpu=100m --extra-cpu=2m --memory=150Mi --extra-memory=30Mi --threshold=5 --deployment=kube-state-metrics]
ERROR: logging before flag.Parse: I0923 08:03:18.088862       1 pod_nanny.go:81] Watching namespace: monitoring, pod: kube-state-metrics-59c47cfcfb-whtlr, container: kube-state-metrics.
ERROR: logging before flag.Parse: I0923 08:03:18.088867       1 pod_nanny.go:82] storage: MISSING, extra_storage: 0Gi
ERROR: logging before flag.Parse: I0923 08:03:18.089886       1 pod_nanny.go:171] Failed to read data from config file "MISSING/NannyConfiguration": open MISSING/NannyConfiguration: no such file or directory, using default parameters
ERROR: logging before flag.Parse: I0923 08:03:18.089931       1 pod_nanny.go:109] cpu: 100m, extra_cpu: 2m, memory: 150Mi, extra_memory: 30Mi
ERROR: logging before flag.Parse: I0923 08:03:18.089943       1 pod_nanny.go:138] Resources: [{Base:{i:{value:100 scale:-3} d:{Dec:<nil>} s:100m Format:DecimalSI} ExtraPerNode:{i:{value:2 scale:-3} d:{Dec:<nil>} s:2m Format:DecimalSI} Name:cpu} {Base:{i:{value:157286400 scale:0} d:{Dec:<nil>} s:150Mi Format:BinarySI} ExtraPerNode:{i:{value:31457280 scale:0} d:{Dec:<nil>} s:30Mi Format:BinarySI} Name:memory}]

```
Insert Prometheus logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by anstns** [comment]
![屏幕快照 2019-09-23 下午4 10 48](https://user-images.githubusercontent.com/36152763/65410551-3e2c0180-de1d-11e9-9618-d84ae7a21ddb.png)
error info

**Comment by brancz** [comment]
This looks like there is some sort of network problem. Can you ensure that you have the firewall open so Prometheus can perform the scrapes? :)

**Comment by anstns** [comment]
I have uninstalled the firewall.

**Comment by brancz** [comment]
And it works?

**Comment by anstns** [comment]
No effect,my apiserver manager logs
![IMAGE 2019-09-24 15:19:10](https://user-images.githubusercontent.com/36152763/65489868-a989d800-dede-11e9-872d-d86fa15bf122.jpg)
![tg_image_2473874050](https://user-images.githubusercontent.com/36152763/65489886-b1e21300-dede-11e9-90f6-87c3d139fa2c.jpeg)
![tg_image_520526569](https://user-images.githubusercontent.com/36152763/65489887-b1e21300-dede-11e9-9f75-b54147c7f6d9.jpeg)
![tg_image_479342581](https://user-images.githubusercontent.com/36152763/65489888-b1e21300-dede-11e9-9f41-2415a90901f1.jpeg)
![IMAGE 2019-09-24 15:19:41](https://user-images.githubusercontent.com/36152763/65489915-bc041180-dede-11e9-9443-50dfe70f6a52.jpg)

**Comment by brancz** [comment]
Can you exec into the prometheus container and try to wget a node exporter? Only if that works, then there may be a problem with Prometheus or the Prometheus Operator, but from what I can tell so far, this is a networking problem of your setup.

**Comment by anstns** [comment]
Can you elaborate on how to operate it?

**Comment by anstns** [comment]
![image](https://user-images.githubusercontent.com/36152763/65492567-bbba4500-dee3-11e9-91de-b37392f4e76a.png)
I always think that's the reason.

**Comment by anstns** [comment]
![image](https://user-images.githubusercontent.com/36152763/65493101-c1645a80-dee4-11e9-8eb9-b6d34f73c9a8.png)
 kubectl logs -f node-exporter-b7h4t -n monitoring -c kube-rbac-proxy

**Comment by anstns** [comment]
![image](https://user-images.githubusercontent.com/36152763/65493256-143e1200-dee5-11e9-85c7-20eb509b54d3.png)
kubectl logs -f kube-state-metrics-59c47cfcfb-76qqf -n monitoring -c kube-state-metrics

**Comment by anstns** [comment]
![image](https://user-images.githubusercontent.com/36152763/65493290-2750e200-dee5-11e9-826e-77eb5ae61faa.png)
kubectl logs -f kube-state-metrics-59c47cfcfb-76qqf -n monitoring -c addon-resizer

**Comment by n1ce37** [comment]
node-exporter-daemonset.yaml file.change daemonset args --web.listen-address=127.0.0.1:9100 to   
 --web.listen-address=0.0.0.0:9100. may be it will work

**Comment by n1ce37** [comment]
> ![image](https://user-images.githubusercontent.com/36152763/65493290-2750e200-dee5-11e9-826e-77eb5ae61faa.png)
> kubectl logs -f kube-state-metrics-59c47cfcfb-76qqf -n monitoring -c addon-resizer

storage missing,no extra storage:0Gi

**Comment by lvs071103** [comment]
Hi, I've had the same problem, The newly added node node-exporter cannot access kubernetes svc clusterIP.
![image](https://user-images.githubusercontent.com/5029708/76718231-0751fb00-6771-11ea-8ec7-3f1a0b618156.png)

report error:
```
[root@k8s-master-node1 2-install-k8s]# kubectl logs -f  node-exporter-sqjnz -c kube-rbac-proxy -n monitoring
.......
E0316 02:34:13.800605   43507 proxy.go:67] Unable to authenticate the request due to an error: Post https://10.254.0.1:443/apis/authentication.k8s.io/v1beta1/tokenreviews: dial tcp 10.254.0.1:443: i/o timeout
......
```
![image](https://user-images.githubusercontent.com/5029708/76719078-aa0b7900-6773-11ea-8a36-a01f896c0a46.png)

My k8s environment is deployed in binary

enter prometheus container wget url result follow: 
![image](https://user-images.githubusercontent.com/5029708/76746916-3be6a680-67b3-11ea-96f6-e6a627ac9379.png)

**Comment by brancz** [comment]
This still sounds like a networking setup problem especially as it’s consistent between masters and worker nodes.

**Comment by lvs071103** [comment]
I installed prometheus with helm no problem and have successfully obtained the data
![image](https://user-images.githubusercontent.com/5029708/76924175-82054c80-6910-11ea-9da8-a530ddf1155c.png)
I think there should be problems when installing prometheus using source code, I have time to try again later

**Comment by lvs071103** [comment]
The network is good, maybe RABC doesn't have permission

**Comment by yadavsudhir405** [comment]
I am also facing these issues but it's working fine with one of the worker node.
![image](https://user-images.githubusercontent.com/11731706/83285097-4d105280-a1fb-11ea-98c9-696ee9aa3b3c.png)

**Comment by brancz** [comment]
Check which node your Prometheus is on, I'm certain it's the one it's able to scrape :) there may be other things preventing scraping.

**Comment by yadavsudhir405** [comment]
@brancz  Thanks for your reply. It was networking issues. I was using calico as a network plugin. I did re-setup of the cluster with canal network plugin and then it started working fine.

**Comment by paulfantom** [comment]
Closing as this appears to be already fixed. Please reopen if this is still an issue.

**Comment by pjamenaja** [comment]
Just for the person who come to this issue later. This link https://vividcode.io/fix-context-deadline-exceeded-error-in-prometheus-operator/ helps to fix this issue.

**Comment by baiye1314** [comment]
@yadavsudhir405 I also replaced flannel with calico, which is normal. Thank you.

**Comment by baiye1314** [comment]
This problem bothered me for a week, and then changed the network plug-in from flannel to calico, which was normal.

**Comment by JaLe29** [comment]
Hello prometheus team,

I am having exactly same issue.

I realized that some data for my app missing in prometheus and I found issue on prometheus status page. (in short I can't see cpu stats for some deployments)

``` 
Get "https://192.168.21.179:10250/metrics/cadvisor": context deadline exceeded
 ```
https://i.imgur.com/P6PBCFM.png

I think, that this unhealthy nodes is connected to some data missing.

I don't understand how previous problems was fixed.

I am having two nodes in AWS EKS.

Thank you for any hints

> https://github.com/prometheus-operator/kube-prometheus/issues/232#issuecomment-847004538

Doesn't help me.

**Comment by rthamrin** [comment]
mine is also the same, suddenly my grafana:3000, corendns:9153 are context deadline exceeded , at the beginning i delete the pods and it solved the problem, but is not working now. my node exporter is fine.

changing scrape_interval means nothing to me. it does not work

**Comment by emmanuel-sonalake** [comment]
I am having the same issue but I'm trying to test this on my local computer, so I spinned up the prometheus docker, prom node exporter and the config to my third target which is a working application. I can see the Application, Node exporter  and Prometheus server as targets on the Prom UI but the Node exporter is not up and running because of this error 

"Get "http://localhost:9100/metrics": dial tcp 127.0.0.1:9100: connect: connection refused

**Comment by wyq1229409654** [comment]
I am having the same

**Comment by LordGaav** [comment]
In my case it was because the node-exporter pod was running with `hostNetwork: true`, so the existing firewall rule between nodes that allows flannel communication wasn't catching it. I had to open the prometheus port on all the nodes, so the scraper can access it.

**Comment by rickstaa** [comment]
I encountered a similar issue where UFW was obstructing incoming requests from my Docker subnet to the host machine. Resolved it by executing `sudo ufw allow in from 172.19.0.0/16 to any port 9100` to include the necessary allow rule.

**Comment by RiRa12621** [comment]
@paulfantom can we delete this comment --> https://github.com/prometheus-operator/kube-prometheus/issues/232#issuecomment-847004538 
that's redirect to adware and probably not good to keep
