### ISSUE TITLE
The collected indicators do not contain resource tags, and the default configuration of kube-prometheus is used.

### ISSUE THREAD

**Issue by zyz-notebooks** [prometheus-operator/kube-prometheus#2377]
![image](https://github.com/prometheus-operator/kube-prometheus/assets/52662505/80480750-8304-452d-8486-110890f75850)

**Comment by philipgough** [comment]
Does https://github.com/prometheus-operator/kube-prometheus/issues/887#issuecomment-1408471187 help?
