### ISSUE TITLE
Appears to be an issue with the Grafana grid.libsonnet

### ISSUE THREAD

**Issue by TimothySutton81** [prometheus-operator/kube-prometheus#2388]
**What happened?**
RUNTIME ERROR running  https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/main/build.sh with grafana

RUNTIME ERROR: field does not exist: get
	vendor/github.com/grafana/grafonnet/gen/grafonnet-v10.4.0/custom/util/./grid.libsonnet:119:25-32	thunk <width>
	vendor/github.com/grafana/grafonnet/gen/grafonnet-v10.4.0/custom/util/./grid.libsonnet:121:29-34	function <func>
	std.jsonnet:789:24-47	thunk <running>
	std.jsonnet:789:9-57	function <aux>
	std.jsonnet:789:9-57	function <aux>
	std.jsonnet:790:5-28	function <anonymous>
	vendor/github.com/grafana/grafonnet/gen/grafonnet-v10.4.0/custom/util/./grid.libsonnet:(93:5)-(172:6)	function <anonymous>
	vendor/github.com/kubernetes-monitoring/kubernetes-mixin/dashboards/apiserver.libsonnet:(320:11)-(345:10)	thunk <panels>
	vendor/github.com/grafana/grafonnet/gen/grafonnet-v10.4.0/clean/../custom/dashboard.libsonnet:24:30-36	thunk <v>
	std.jsonnet:32:25	
	...
	std.jsonnet:919:10-19	function <aux>
	std.jsonnet:947:39-78	thunk <array_element>
	std.jsonnet:951:9-28	function <aux>
	std.jsonnet:952:5-23	function <anonymous>
	vendor/github.com/brancz/kubernetes-grafana/grafana/grafana.libsonnet:100:25-79	object <anonymous>
	vendor/github.com/brancz/kubernetes-grafana/grafana/grafana.libsonnet:100:15-81	object <anonymous>
	vendor/github.com/brancz/kubernetes-grafana/grafana/grafana.libsonnet:(93:7)-(101:8)	thunk <array_element>
	vendor/github.com/brancz/kubernetes-grafana/grafana/grafana.libsonnet:(92:12)-(132:6)	object <anonymous>
	example.jsonnet:31:1-83	object <anonymous>
	During manifestation	

**Did you expect to see some different?**
For the build to complete with out errors
**How to reproduce it (as minimally and precisely as possible)**:
b init # Creates the initial/empty `jsonnetfile.json`
jb install github.com/prometheus-operator/kube-prometheus/jsonnet/kube-prometheus@main
wget https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/main/build.sh -O build.sh
chmod +x build.sh
./build.sh

**Environment**
Using standard example.jsonnet creates this issue 
* Prometheus Operator version:
This is latest from git

* Kubernetes version information:
Not even using kubectl

* Kubernetes cluster kind:

k3s but not even at that point
* Manifests:

```
insert manifests relevant to the issue
```

example.jsonnet:

ocal kp =
  (import 'kube-prometheus/main.libsonnet') +
  // Uncomment the following imports to enable its patches
  // (import 'kube-prometheus/addons/anti-affinity.libsonnet') +
  // (import 'kube-prometheus/addons/managed-cluster.libsonnet') +
  // (import 'kube-prometheus/addons/node-ports.libsonnet') +
  // (import 'kube-prometheus/addons/static-etcd.libsonnet') +
  // (import 'kube-prometheus/addons/custom-metrics.libsonnet') +
  // (import 'kube-prometheus/addons/external-metrics.libsonnet') +
  // (import 'kube-prometheus/addons/pyrra.libsonnet') +
  {
    values+:: {
      common+: {
        namespace: 'monitoring',
      },
    },
  };

{ 'setup/0namespace-namespace': kp.kubePrometheus.namespace } +
{
  ['setup/prometheus-operator-' + name]: kp.prometheusOperator[name]
  for name in std.filter((function(name) name != 'serviceMonitor' && name != 'prometheusRule'), std.objectFields(kp.prometheusOperator))
} +
// { 'setup/pyrra-slo-CustomResourceDefinition': kp.pyrra.crd } +
// serviceMonitor and prometheusRule are separated so that they can be created after the CRDs are ready
{ 'prometheus-operator-serviceMonitor': kp.prometheusOperator.serviceMonitor } +
{ 'prometheus-operator-prometheusRule': kp.prometheusOperator.prometheusRule } +
{ 'kube-prometheus-prometheusRule': kp.kubePrometheus.prometheusRule } +
{ ['alertmanager-' + name]: kp.alertmanager[name] for name in std.objectFields(kp.alertmanager) } +
{ ['blackbox-exporter-' + name]: kp.blackboxExporter[name] for name in std.objectFields(kp.blackboxExporter) } +
{ ['grafana-' + name]: kp.grafana[name] for name in std.objectFields(kp.grafana) } +
// { ['pyrra-' + name]: kp.pyrra[name] for name in std.objectFields(kp.pyrra) if name != 'crd' } +
{ ['kube-state-metrics-' + name]: kp.kubeStateMetrics[name] for name in std.objectFields(kp.kubeStateMetrics) } +
{ ['kubernetes-' + name]: kp.kubernetesControlPlane[name] for name in std.objectFields(kp.kubernetesControlPlane) }
{ ['node-exporter-' + name]: kp.nodeExporter[name] for name in std.objectFields(kp.nodeExporter) } +
{ ['prometheus-' + name]: kp.prometheus[name] for name in std.objectFields(kp.prometheus) } +
{ ['prometheus-adapter-' + name]: kp.prometheusAdapter[name] for name in std.objectFields(kp.prometheusAdapter) }

**Comment by TimothySutton81** [comment]
This was a go path issue on my part.

**Comment by zyz-1998** [comment]
I have the same problem, how can I fix it? Thanks

**Comment by zyz-1998** [comment]
else
117           // handle regular panel
118           local gridPos = std.get(panel, 'gridPos', {});
119           local width = std.get(gridPos, 'w', panelWidth);
120           local height = std.get(gridPos, 'h', panelHeight);
121           if acc.cursor.x + width > gridWidth
122           then
123             // start new row as width exceeds gridWidth
124             acc + {
125               panels+: [
126                 panel + {
