### ISSUE TITLE
New release 0.14.

### ISSUE THREAD

**Issue by jakubbak** [prometheus-operator/kube-prometheus#2468]
Hello Team , 

do we know when new release 0.14 will be delivered ?

Thanks in advance!

**Comment by tuxamito** [comment]
It would be nice to have a shorter release cycle to get updated images of all the components and also to officially support newer Kubernetes versions.  I hope version 0.14 is tagged soon with support for Kubernetes 1.29/1.30.  Thanks!

**Comment by nogweii** [comment]
This is especially important as v0.13 has an older pinned version of kubernetes-monitoring/kubernetes-mixin that breaks linting when using an updated version of Grafana Inc's jsonnet libraries. This is [resolved in kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin/commit/85e01121a951a75ef9ee5cc21a9bf81ba3096178) but the version is pinned to an earlier commit.

**Comment by tuxamito** [comment]
Hello @philipgough , could you please help with this?  It has been a year since the last release.  Can we support it somehow?  Thank you!

**Comment by philipgough** [comment]
Hey all. I gave some info on this previously https://github.com/prometheus-operator/kube-prometheus/issues/2180#issuecomment-1706853708

But the summary is that OpenShift team (which was the reason for creating the release workflow and schedule initially), no longer uses release branches so the urgency from their side is gone. Things have changed internally for me too so I no longer use this project day-to-day. I am just trying to do my best to maintain it and keep it up to date on the side but time is limited.

I'll try my best to schedule some time for a new release this week! 

> It would be nice to have a shorter release cycle
It would indeed be nice but there is not really anyone else active in the project at the moment and as stated above, my time is limited here. I'll try to be more diligent about scheduling time for it regularly. Its not just cutting the release though. Releases need to be supported.

**Comment by tuxamito** [comment]
Thank you for your answer and explainations.

> Hey all. I gave some info on this previously [#2180 (comment)](https://github.com/prometheus-operator/kube-prometheus/issues/2180#issuecomment-1706853708)

Sorry, I was not aware.

> But the summary is that OpenShift team (which was the reason for creating the release workflow and schedule initially), no longer uses release branches so the urgency from their side is gone. Things have changed internally for me too so I no longer use this project day-to-day. I am just trying to do my best to maintain it and keep it up to date on the side but time is limited.

I totally understand.  We continue using this project but we have no resources to maintain it :(

> I'll try my best to schedule some time for a new release this week!

Thank you!

**Comment by KlavsKlavsen** [comment]
so this is being used and maintained by redhat openshift team (and only them)?

**Comment by KlavsKlavsen** [comment]
We can offer to help (a bit - like cutting releases for new k8s versions - as part of our ongoing update of our own and customer k8s clusters anyways).. if it would be relevant/useful.. We're using it in our open source project KubeAid.io - https://github.com/Obmondo/kubeaid/tree/master/build/kube-prometheus - and can atleast spread some maintenance cost across the customers we do have that pays us to support their use of KubeAid. We already have built several mixins - we're trying to find a way to preferrably merge into upstream projects, such as argocd etc. - that we currently carry in KubeAid https://github.com/Obmondo/kubeaid/tree/master/build/kube-prometheus/mixins

We don't really need commit rights or anything.. just to know that a PR would get some feedback and be merged (once we learn to do it right :)

**Comment by philipgough** [comment]
Starting here by updating ci https://github.com/prometheus-operator/kube-prometheus/pull/2507

**Comment by philipgough** [comment]
@KlavsKlavsen thanks for the offer. Any help would indeed be appreciated. Feel free to get me on Slack if you want to discuss any details :)

**Comment by philipgough** [comment]
Closing as done. :)

**Comment by tuxamito** [comment]
@philipgough Thank you!

**Comment by jakubbak** [comment]
Thank you Philip

**Comment by jakubbak** [comment]
Hello @philipgough , may I have one last question ? 

Could you please let me know how often you are guys preparing security patches in this prometheus repo ?
