### ISSUE TITLE
etcdDatabaseHighFragmentationRatio should change default rule 

### ISSUE THREAD

**Issue by zgfh** [prometheus-operator/kube-prometheus#2470]
**What happened?**

https://github.com/etcd-io/etcd/blob/main/contrib/mixin/alerts/alerts.libsonnet#L222
I meet alert: etcdDatabaseHighFragmentationRatio

becuse the default quota space is 2G of etcd
![image](https://github.com/user-attachments/assets/c3600123-e548-4574-8c91-355f931f9814)

I this is ok if there just 50M fragmentation
should we change the rule to 1024M?  like this(1073741824=1024M):
```
(last_over_time(etcd_mvcc_db_total_size_in_use_in_bytes[5m]) / last_over_time(etcd_mvcc_db_total_size_in_bytes[5m])) < 0.5 and etcd_mvcc_db_total_size_in_use_in_bytes > 1073741824
```

the default alert is 
```
  (last_over_time(etcd_mvcc_db_total_size_in_use_in_bytes[5m]) / last_over_time(etcd_mvcc_db_total_size_in_bytes[5m])) < 0.5 and etcd_mvcc_db_total_size_in_use_in_bytes > 104857600

```

**Comment by simonpasquier** [comment]
You'd need to ask to https://github.com/etcd-io/etcd/

**Comment by slashpai** [comment]
closing as this is related to https://github.com/etcd-io/etcd

**Comment by zgfh** [comment]
link: https://github.com/etcd-io/etcd/discussions/18620
