### ISSUE TITLE
Adding custom configmap and adding volumes for deployment

### ISSUE THREAD

**Issue by KocsistemCloud** [prometheus-operator/kube-prometheus#253]
Hi
Utilizing kube-prometheus in the environment. I have to add a custom configmap with jobs and custom relabelling for istio monitoring , but couldn't find the overriding keywords in jsonnet file. I also want to mount Istio's certificates to Prometheus in deployment.yaml. 
Will you please guide me where i can find the keywords?
Thanks,

**Comment by KocsistemCloud** [comment]
In case someone like my newbieness needs :), added this to my jsonnet.. 
          secrets+: ['istio.default'],
          additionalScrapeConfigs: {
            name: 'additional-scrape-configs',
            key: 'prometheus-additional.yaml',
          }, //end additionalScrapeConfigs

Probably a question out of kube-prometheus, but any way to implement the additionalScrapeConfigs secret in the project?
Thanks,

**Comment by jamie-34254** [comment]
```
local k = import 'ksonnet/ksonnet.beta.3/k.libsonnet';
local secret = k.core.v1.secret;

local promConfig = {
  job_name: 'blabla',
  scrape_interval: '15s',
  honor_labels: true,
  metrics_path: '/federate',
  params: {
    'match[]': [
      '{job=~".+"}',
    ],
  },
  ],
};

local secretConfig = { 'prom-additional-jobs.yaml': std.base64(std.encodeUTF8(std.manifestYamlDoc(promConfig))) };

{
  "secret": secret.new('prom-additional-scrape-configs', secretConfig) +    
  secret.mixin.metadata.withNamespace("monitoring")
}
```

**Comment by gitmedur** [comment]
Can i ask how you mounted the istio certs to prometheus pod?

**Comment by paulfantom** [comment]
Closing as this appears to be answered. Please reopen if you think this is still relevant.
