### ISSUE TITLE
Statefulsets dashboard shows doubled CPU/Memory usage (statefulset.json)

### ISSUE THREAD

**Issue by almariah** [prometheus-operator/kube-prometheus#256]
**What happened?**
CPU and memory in Statefulsets dashboard (grafana) shows doubled metrics. 

The definition: 
```
"expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubelet\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$statefulset.*\"}[3m]))",
``` 

should be replaced by:

```
"expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubelet\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$statefulset.*\", container_name!=\"\"}[3m]))",
```

* Prometheus Operator version:
v0.33.0

**Comment by brancz** [comment]
This dashboard comes from the [kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin). Could you open a PR there and fix the issue and then [bump the dependency](https://github.com/coreos/kube-prometheus#contributing) in this repo? :slightly_smiling_face:

**Comment by paulfantom** [comment]
I think this was already fixed. Please reopen if this is still an issue.
