### ISSUE TITLE
kustomize resource "grafana-rawDashboardDefinitions.yaml" missing on master

### ISSUE THREAD

**Issue by bzub** [prometheus-operator/kube-prometheus#269]
To reproduce:

```
ref="master"
kustomize build "github.com/coreos/kube-prometheus?ref=${ref}"
```

error:
```
Error: accumulating resources: accumulating resources from './manifests/grafana-rawDashboardDefinitions.yaml': evalsymlink failure on '/private/var/folders/w4/c24yvdzn7qb7lfbn03mwnx8nhjh8lv/T/kustomize-666221288/manifests/grafana-rawDashboardDefinitions.yaml' : lstat /private/var/folders/w4/c24yvdzn7qb7lfbn03mwnx8nhjh8lv/T/kustomize-666221288/manifests/grafana-rawDashboardDefinitions.yaml: no such file or directory
```

It worked previous to https://github.com/coreos/kube-prometheus/commit/e7c3ca314da6823fb6cdcb666403c05bb76dbe55 where `grafana-rawDashboardDefinitions.yaml` was added to `kustomization.yaml`

**Comment by brancz** [comment]
This file is only potentially there if you build the stack using jsonnet. I think this shouldn't be in the kustomize file. Could you remove it?

**Comment by paulfantom** [comment]
Closing due to staleness. Please reopen if you think this is still relevant.
