### ISSUE TITLE
Grafana Networking dashboards have wrong datasource hardcoded

### ISSUE THREAD

**Issue by den-is** [prometheus-operator/kube-prometheus#288]
**What happened?**
`kube-prometheus/manifests/grafana-dashboardDefinitions.yaml` has "wrong" datasource hardcoded in all "Networking"definitions.

**Did you expect to see some different?**
probably something like that `"datasource": "$datasource",` should be there instead of `"datasource": "prometheus",`

**How to reproduce it (as minimally and precisely as possible)**:
You can deploy prometheus-operator chart from this PR https://github.com/helm/charts/pull/18564 and enjoy broken "Networking" dashboards everything else seems to be great 

**Environment**
* Prometheus Operator version: `0.33`
* Kubernetes version information: `1.16.2`
* Kubernetes cluster kind: hand-made pure linux + kubernetes environment

**Comment by den-is** [comment]
I have pushed fix https://github.com/helm/charts/pull/18375/commits/4e2e7e54fd2d3f41b6f253605600d83d13712fc9 to chart only. a.k.a "temporary fix until Upstream fixes own stuff"
I would say that it is littlbe bit strange bug... as some manifest have datasource variable and proper resources, others have nothing at all
Also good to discover that now i have to bootstrap grafana with plugin to properly display that dashboards
![Screen Shot 2019-10-26 at 20 35 04](https://user-images.githubusercontent.com/5287237/67623131-03a9f000-f833-11e9-80df-f9c342b3ecf8.png)

**Comment by brancz** [comment]
Yes this is indeed incorrect. [Someone else already noticed this as well](https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/284) and fixed a couple other mistakes but not this one yet. Do you want to go ahead and fix it?

**Comment by den-is** [comment]
@brancz Unfortunately I don't have time and motivation to mess with jsonnet/libsonnet so hopefully someone more suitable for that job will be able to fix it in upstream.

In the meantime I will open similar issue in kubernetes-mixin repo.

**Comment by paulfantom** [comment]
Closing due to staleness. Please reopen if you think this is still relevant.
