### ISSUE TITLE
grafana persist dashboards

### ISSUE THREAD

**Issue by vincentjorgensen** [prometheus-operator/kube-prometheus#292]
**What did you do?**
I installed prometheus to my EKS cluster
I saved my dashboard to `grafana-custom-home-dashboard.json`
Then I created a configMap

```
kubectl -n monitoring create configmap grafana-moveworks-home-dashboard --from-file=grafana-custom-home-dashboard.json
kubectl -n monitoring label configmaps grafana-custom-home-dashboard grafana_dashboard=1
```
**Did you expect to see some different?**
I do not see my custom dashboard 

**Environment**

* Prometheus Operator version:

    `quay.io/coreos/prometheus-operator:v0.31.1`
    

* Kubernetes version information:

    `v1.14.1`
    

* Kubernetes cluster kind:
EKS 1.14

* Manifests:
jsonnet file used to create manifests
```
// local k = import 'ksonnet/ksonnet.beta.3/k.libsonnet';
// local pvc = k.core.v1.persistentVolumeClaim;

local kp =
  (import 'kube-prometheus/kube-prometheus.libsonnet') +
  // Uncomment the following imports to enable its patches
  // (import 'kube-prometheus/kube-prometheus-anti-affinity.libsonnet') +
  // (import 'kube-prometheus/kube-prometheus-managed-cluster.libsonnet') +
  // (import 'kube-prometheus/kube-prometheus-node-ports.libsonnet') +
  // (import 'kube-prometheus/kube-prometheus-static-etcd.libsonnet') +
  // (import 'kube-prometheus/kube-prometheus-thanos-sidecar.libsonnet') +
  {
    _config+:: {
      namespace: 'monitoring',
    },

    prometheus+:: {
      prometheus+: {
        spec+: {
          retention: '30d',
          storage: {
            volumeClaimTemplate: {
              metadata: {
                name: 'prometheus-storage',
                namespace: 'monitoring',
              },
              spec: {
                accessModes: ['ReadWriteOnce'],
                withStorageClassName: 'gp2',
                resources: {
                  requests: {
                    storage: '250Gi',
                  },
                },
              },
            },
           },
        }, // spec
      }, // prometheus
    }, // prometheus
  }; // kp

{ ['00namespace-' + name]: kp.kubePrometheus[name] for name in std.objectFields(kp.kubePrometheus) } +
{ ['0prometheus-operator-' + name]: kp.prometheusOperator[name] for name in std.objectFields(kp.prometheusOperator) } +
{ ['node-exporter-' + name]: kp.nodeExporter[name] for name in std.objectFields(kp.nodeExporter) } +
{ ['kube-state-metrics-' + name]: kp.kubeStateMetrics[name] for name in std.objectFields(kp.kubeStateMetrics) } +
{ ['alertmanager-' + name]: kp.alertmanager[name] for name in std.objectFields(kp.alertmanager) } +
{ ['prometheus-' + name]: kp.prometheus[name] for name in std.objectFields(kp.prometheus) } +
{ ['prometheus-adapter-' + name]: kp.prometheusAdapter[name] for name in std.objectFields(kp.prometheusAdapter) } +
{ ['grafana-' + name]: kp.grafana[name] for name in std.objectFields(kp.grafana) }
```

* Prometheus Operator Logs:
Did not see anything about loading grafana in the grafana stdout logs

* Prometheus Logs:
n/a
**Anything else we need to know?**:
Is there a way to do this as a persistent volume instead? If so, what is the relevant jsonnet snippet to include `grafana-storage` in `grafana-deployment.yaml` as I've done with prometheus storage in the jsonnet above?

Thank you!

**Comment by vincentjorgensen** [comment]
Also, when I do (which is outside jsonnet), and set the claim inside `grafana-deployment.yaml`:
```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: grafana
    grafana: k8s
  name: grafana-storage-k8s
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp2
...
```
I get `mkdir: cannot create directory '/var/lib/grafana/plugins': Permission denied`.

**Comment by vincentjorgensen** [comment]
I can go to the node that is hosting the pod and chmod the directory, but it seems that I shouldn't have to do that.

**Comment by brancz** [comment]
We intentionally run grafana fully from config files provisioned way as that allows us to treat Grafana in a stateless way. I highly recommend doing the same, otherwise you’re going to end up running an HA MySQL for your dash boarding system.

**Comment by vincentjorgensen** [comment]
@brancz I'd prefer that, but I'm using EBS right now until we figure out while the dashboards aren't being picked up. I've read that for helm, one does `grafana.sidecar.dashboards.enabled=true`. Is there an equivalent to enable sidecar dashboards when installing via `jsonnet` and `kubectl apply`? If it's available OOTB, what step(s) did I miss? Thank you and regards, Vincent

**Comment by brancz** [comment]
Did you follow: https://github.com/coreos/kube-prometheus/blob/master/docs/developing-prometheus-rules-and-grafana-dashboards.md#dashboards ?

**Comment by vincentjorgensen** [comment]
@brancz No, I tried the configMap method, outlined about. That may be specific to Helm?

**Comment by vincentjorgensen** [comment]
I followed the above directions and so long as I re-apply `grafana-deployment.yaml` and `grafana-dashboardDefinitions.yaml`, I see my custom dashboards. Thank you.

**Comment by vincentjorgensen** [comment]
The grafana-dashboardDefinitions file has gotten quite large. Is there a way to break it up into individual configmaps per dashboard?

**Comment by brancz** [comment]
It’s already that way, the file contains a ConfigMapList, which contains a configmap per dashboard. We could split them out into separate files but naming is likely to be weird as it would be generated.

**Comment by fbaier-fn** [comment]
This has been stale for a while but I'd like to bring this up again.

> I've read that for helm, one does `grafana.sidecar.dashboards.enabled=true`. Is there an equivalent to enable sidecar dashboards when installing via `jsonnet` and `kubectl apply`? If it's available OOTB, what step(s) did I miss? Thank you and regards, Vincent

https://github.com/coreos/kube-prometheus/blob/master/docs/developing-prometheus-rules-and-grafana-dashboards.md#dashboards is not really mentioning anything about a sidecar but rather how to create the configmap. But what happens after the configmap was updated? I couldn't find anything like in the Helm chart within `kube-prometheus` that would reload the updated dashboard. 

Is the only way in this case to have your updated dashboard within your Grafana instance loaded a full restart of the pod? Thanks for clarifying in advance!

**Comment by metalmatze** [comment]
It reloads the configmaps _eventually_. This may happen between a few seconds and a few minutes. Can you verify it?

**Comment by metalmatze** [comment]
Here's some more explanation on eventual ConfigMap reloading: https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#mounted-configmaps-are-updated-automatically
Thanks for pointing out @fbaier-fn.

**Comment by surajssd** [comment]
I understand that dashboards can be loaded in grafana using configmap. But how to do user management without storage? Is there a mechanism where I can provide user info and only those users can login, etc?

How do you manage that @metalmatze ?

**Comment by brancz** [comment]
We use an oauth proxy in front of Grafana.

**Comment by cten** [comment]
I use Kustomize pointed at this repo, so I am not using jsonnet to build my resources. Is there any other way besides overlaying more volumeMounts to Grafana?

**Comment by alfaro28** [comment]
@brancz could you elaborate a little on the oauth proxy approach, I understand this question is more related to grafana itself but how do I modify grafana settings on kube-prometheus to enable oauth?
