### ISSUE TITLE
Cannot jb update current master

### ISSUE THREAD

**Issue by karancode** [prometheus-operator/kube-prometheus#296]
**What happened?**
After cloning the new master (b8f513e4d485db099a1dec4dffd219518b4d8d57) `jb update` is failing with the error : 
```
>>> Installed node-mixin version 5a7b85876d6108a91f0d8673c0d7eca38687671b
jb: error: failed to install: failed to insert dependency to lock dependencies: multiple colliding versions specified for node-mixin: 20fe5bfb5be4caf3c8c11533b7fb35cb97d810f5 (from vendor/kube-prometheus/jsonnetfile.json) and 5a7b85876d6108a91f0d8673c0d7eca38687671b (from jsonnetfile.json)
```

**Did you expect to see some different?**
`jb update` should be successful with updated versions in the lock file.

**How to reproduce it (as minimally and precisely as possible)**:
```
git clone https://github.com/coreos/kube-prometheus.git && cd kube-prometheus
jb update
```

**Environment**
OS : macOS Catalina Version `10.15`.
kube-prometheus : latest master (commit : b8f513e4d485db099a1dec4dffd219518b4d8d57)

**Comment by brancz** [comment]
@s-urbaniak i think we did an incorrect update there. Pinning should not happen in the root of this repo, if at all then in jsonnet/kube-prometheus.

**Comment by s-urbaniak** [comment]
interesting :thinking: let me have a look what I did wrong here.

**Comment by s-urbaniak** [comment]
ah I know, we needed to pin node mixin as there was a bug, my bad i pinned it in the root.

**Comment by s-urbaniak** [comment]
@karancode regardless, using the newest version of `jb` I don't get any error when doing an `jb update` in the root directory. Do you mind to retry with the most recent `jb` version?

**Comment by karancode** [comment]
@s-urbaniak i tried but couldn’t get it updated.

**Comment by paulfantom** [comment]
Closing due to staleness. Please reopen if you think this is still relevant.
