### ISSUE TITLE
How to install dashboards from public catalog

### ISSUE THREAD

**Issue by Paxa** [prometheus-operator/kube-prometheus#320]
I installed kube-prometheus more then a year ago, and would like to add new dashboards, without risking to lose all settings I made.

Can we find packaged dasboards at https://grafana.com/grafana/dashboards ?

**Comment by brancz** [comment]
We intentionally run Grafana in a fully stateless mode, so if you want to add any dashboards, you do so via the provisioning features. There are a couple of ways described here: https://github.com/coreos/kube-prometheus/blob/master/docs/developing-prometheus-rules-and-grafana-dashboards.md

**Comment by Paxa** [comment]
Will it override dashboards that I have from initial provisioning (that I ran last year)?
I already customized them for my needs and don't wanna lose this changes.

Any plans to add to public catalog?

**Comment by brancz** [comment]
Yes you will lose them, the Grafana Setup does not have any persistence and is fully provisioned from files like described I the docs.

**Comment by Paxa** [comment]
I already customized my setup to use PVC for grafana and make backups.
Too bad, I'll need to add them manually

**Comment by brancz** [comment]
If you have a PVC then things that were not already there won’t change if that helps.

**Comment by paulfantom** [comment]
Closing due to staleness. Please reopen if you think this is still relevant.
