### ISSUE TITLE
Update deploy scripts in QuickStart

### ISSUE THREAD

**Issue by alanpeng** [prometheus-operator/kube-prometheus#334]
**What is missing?**

**Why do we need it?**
Update the scripts in QuickStart:

Please refer to this project https://github.com/wise2c-devops/breeze/blob/master/prometheus-playbook/version/file/deploy.sh 

line 41-69
 
**Environment**

* kube-prometheus version:

    `Insert Git SHA here`

**Anything else we need to know?**:

**Comment by alanpeng** [comment]
By using this script, no necessary to run the command multiple times for all components to be created successfully.

**Comment by brancz** [comment]
We intentionally don’t have a production style script as when we did people relied on it like an API. We encourage people to write and share these things but we’re not going to maintain and ensure any kind of stability in it. kube-prometheus responsibility stops at the point where you have manifests (Or even before that in form of the provided jsonnet libraries). How you deploy them is then up to you.

That said we’re happy to link to examples of how people deploy this stack :)

**Comment by paulfantom** [comment]
We now have examples in https://github.com/prometheus-operator/kube-prometheus/blob/main/docs/migration-guide.md#examples. In the future, we may move them to some more visible place.
