### ISSUE TITLE
How to edit the Prometheus default configuration, when I edit the secret prometheus-k8s, it will become the default configuration.

### ISSUE THREAD

**Issue by mosesyu95** [prometheus-operator/kube-prometheus#335]
kubectl apply -f coreos/kube-prometheus/manifests

**Comment by brancz** [comment]
All targets in kube prometheus are configured using a CRD called ServiceMonitor or PodMonitor. Those then are used to generate the secret you were trying to edit. I recommend getting familiar with the prometheus operator which is the component that does all of this: https://github.com/coreos/prometheus-operator

**Comment by paulfantom** [comment]
Closing due to staleness. Please reopen if you think this is still relevant.
