### ISSUE TITLE
how to change scrape_interval time to 15s 

### ISSUE THREAD

**Issue by mosesyu95** [prometheus-operator/kube-prometheus#337]
how to change scrape_interval time to 15s 

kubectl edit secret prometheus-k8s 

it not use

**Comment by brancz** [comment]
You need to modify it on the servicemonitor that configured the target in question.

**Comment by xkfen** [comment]
just modify the prometheus-prometheus.yaml，add `scrape_interval=15s` in the `spec` partition

**Comment by paulfantom** [comment]
Closing as this appears to be answered. Please reopen if you think this is still relevant.

**Comment by hucongwei** [comment]
spec段写入以下配置项即可 scrapeInterval: 15s，而不是 scrape_interval=15s
