### ISSUE TITLE
incorrect runbook url for alert KubeHpaMaxedOut in prometheus-rules.yaml

### ISSUE THREAD

**Issue by raoofm** [prometheus-operator/kube-prometheus#339]
https://github.com/coreos/kube-prometheus/blob/master/manifests/prometheus-rules.yaml#L606

**Comment by brancz** [comment]
That would be an issue for the [kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin) project. Feel free to add a runbook :)

**Comment by paulfantom** [comment]
Closing due to staleness. Please reopen if you think this is still relevant.
