### ISSUE TITLE
Customizing alerts 

### ISSUE THREAD

**Issue by omerlh** [prometheus-operator/kube-prometheus#343]
**What is missing?**
Being able to select which alerts I want to enable and the labels for each alert.

**Why do we need it?**
Not all alerts might be relevant for everyone, and we would like to choose which alerts we have - and more importantly, which alerts wakes us in the middle of the night :)

**Environment**
Kubernetes

* kube-prometheus version:

    `Insert Git SHA here` latest

**Anything else we need to know?**:

**Comment by Aracki** [comment]
You can comment them out or add them your custom "low" severity.

**Comment by brancz** [comment]
Or you use a small amount of jsonnet code, for example:

```
{
             prometheusAlerts+:: {
               groups:
                 std.map(
                   function(ruleGroup)
                     if ruleGroup.name == 'etcd' then
                       ruleGroup { rules: std.filter(function(rule) !('alert' in rule && rule.alert == 'etcdHighNumberOfFailedGRPCRequests'), ruleGroup.rules) }
                     else
                       ruleGroup,
                   super.groups,
                 ),
             }
}
```

We use this snippet for example until a specific etcd bug is resolved that fixes the grcp error reporting currently distorting the metrics.

**Comment by omerlh** [comment]
Nice, thank you for sharing!

**Comment by paulfantom** [comment]
Closing due to staleness. Please reopen if you think this is still relevant.
