### ISSUE TITLE
prometheus  prompt  No rules defined 

### ISSUE THREAD

**Issue by yq513** [prometheus-operator/kube-prometheus#348]
The prometheus and Alertmanager I deployed are already running
Configured in configmap of prometheus
    rule_files:
     -/etc/prometheus/rules.yml
    alerting:
      alertmanagers:
       -static_configs:
         -targets: ['localhost: 9093']
Configured at the end of the file
 rules.yml: |
    groups:
    -name: test-rule
      rules:
      -alert: NodeMemoryUsage-low
        expr: (node_memory_MemTotal_bytes-(node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes)) / node_memory_MemTotal_bytes * 100> 1
        for: 1m
        labels:
          team: node
          severity: info
        annotations:
          summary: "{{$ labels.instance}}: High Memory usage detected"
          description: "{{$ labels.instance}}: Memory usage is above 80% (current value is: {{$ value}}"
      -alert: go_goroutines_numbers
        expr: go_goroutines> 1
        for: 15s
        annotations:
          summary: "Prometheus has more than 40 gorotine data!": (. +)

But Prometheus's web ui  http://Prometheus URL/rules    prompt No rules defined
![8 3Q92% VZYE3Q%Z8@I(6{D](https://user-images.githubusercontent.com/39945790/71360215-01150e00-25ca-11ea-9f94-7c5e57f8202b.png)

kubernetes 1.16.2  prometheus 2.14.0   Alertmanager 0.20.0

I want to know where it is not configured, please guide, thank you

**Comment by brancz** [comment]
What you shared does not look like a kube-prometheus setup. How did you setup your Prometheus setup?

**Comment by paulfantom** [comment]
Closing due to staleness. Please reopen if you think this is still relevant.
