### ISSUE TITLE
Allow Prometheus to watch all namespaces

### ISSUE THREAD

**Issue by omerlh** [prometheus-operator/kube-prometheus#350]
**What is missing?**
Today, we can configure Prometheus to watch only specific namespaces, and any additional namespaces have to be configured using jsonnet.  There is no option to watch all the namespaces.

**Why do we need it?**
We want to deploy a Prometheus instance using Kube-Prometheus that will scrape also all the pods in the cluster.

**Environment**

* kube-prometheus version:

    `Insert Git SHA here` latest

**Anything else we need to know?**:

**Comment by brancz** [comment]
What's configured in jsonnet is simply the permissions, if you create a ClusterRole and ClusterRoleBinding then that would already work. If you want we can even make this a jsonnet patch and add some docs as I think many people want this behavior. We intentionally went with a very locked down least-privilege approach, but we recognize that maybe not everyone's requirements are quite as strict.

**Comment by omerlh** [comment]
Generally, I'm all in for strict permissions, but when migration from chart to use the operator, the fastest way is keeping one instance to monitor the entire cluster and then break it down. This is the patch I added: 

```jsonnet
      clusterRole+: {
        rules+: 
          local role = k.rbac.v1.role;
          local policyRule = role.rulesType;
          local rule = policyRule.new() +
                        policyRule.withApiGroups(['']) +
                        policyRule.withResources([
                          'services',
                          'endpoints',
                          'pods',
                        ]) +
                        policyRule.withVerbs(['get', 'list', 'watch']);
          [rule]
      },
```
I can open a PR to add it

**Comment by brancz** [comment]
Sounds good :)

**Comment by kskewes** [comment]
Adding to this, I guess we would also want to do (assuming `prometheus-k8s` default name):
1. a `ClusterRoleBinding` to the `prometheus-k8s` ServiceAccount
2. filter out any `Role` and `RoleBinding` with `name: prometheus-k8s`
3. by default all namespaces are watched for ServiceMonitors and PodMonitors through `prometheus-prometheus.yaml` having `[pod|service]MonitorSelector: {}` ?

In the current generated manifests I can't find any reference to specific namespaces except for `Role` and `RoleBindings`.

**Comment by brancz** [comment]
Yes I think you’re right

1) done
2) we should do, I agree!
3) I thought this was the case but if not I agree we should do this!

**Comment by netbidev** [comment]
Hello everyone.

How to allow prometheus to watch namespace.
Log shows this information:

`level=error ts=2020-07-05T21:35:33.751Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:361: Failed to list *v1.Endpoints: endpoints is forbidden: User \"system:serviceaccount:monitoring:prometheus-k8s\" cannot list resource \"endpoints\" in API group \"\" in the namespace \"tool-dev\""`

Sorry for my stupid question.

**Comment by zohiba** [comment]
I also have the same forbidden user error. New to using OpenShift and prometheus. Would like some guidance as to what can be done to solve this

**Comment by netbidev** [comment]
Fixed by https://github.com/prometheus-operator/prometheus-operator/issues/2155#issuecomment-441002864

**Comment by SayakMukhopadhyay** [comment]
Hi, I believe this issue is closed with #380

**Comment by paulfantom** [comment]
I am closing this issue as it seems to be fixed already. If you find this issue to be still present, please comment.

**Comment by LPinto98** [comment]
I'm new to this, and just started with the quick setup. So following the steps, I'm able to see the prometheus dashboard. In the targets I'm not able to see all the namespaces and the pods in those namespaces. What changes have to be done in the manifest files?

**Comment by inductor** [comment]
@LPinto98 

See https://github.com/prometheus-operator/prometheus-operator/issues/2155#issuecomment-441002864
