### ISSUE TITLE
KubeDeploymentGenerationMismatch is never triggered - could it be?

### ISSUE THREAD

**Issue by ira-shumacher** [prometheus-operator/kube-prometheus#355]
It seems that the KubeDeploymentGenerationMismatch out-of-the-box alert is never triggered.
To my understanding, this alert should fire when the kube_deployment_metadata_generation metric does not match the kube_deployment_status_observed_generation metrics, but these two metrics are always the same

**What did you do?**
I tried simulating this alert to fire by deploying a failing deployment.
When a deployment was syntactically incorrect it just failed, not causing any change to the metrics above.
When a deployment succeeded but started some faulty application [Incorrect image, or non existing port] it was still successful, but  showing 0 in READY.

Is it possible this alert never fires? Or did I misunderstand its usecase?

This is my simple nginx sample deployment:

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 33
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginxx:1.7.9 <--- intentional typo here
        ports:
        - containerPort: 80

**Comment by brancz** [comment]
Generation is a tricky thing in Kubernetes. I tend to agree that in the case of the Deployment object it's not extremely useful. Essentially the generation tells us whether the state reported can be believed, so it usually fails when for example the StatefulSet controller is in a state where it cannot decide and (probably) needs human intervention.

**Comment by PhilipGough** [comment]
I'm going to close this since the actual alert is pulled in via [kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/c76b9378b86d28bd617d94a57c72b4770efed510/alerts/apps_alerts.libsonnet#L51-L66)

I also think it is worth keeping based on @brancz explanation regardless
