### ISSUE TITLE
kube-apiserver not running

### ISSUE THREAD

**Issue by mackspc** [prometheus-operator/kube-prometheus#357]
**What did you do?**
I used conmmand  "kubectl apply -f setup/" ,it looks like do not work,there is someting wrong
【The CustomResourceDefinition "prometheusrules.monitoring.coreos.com" is invalid: spec.validation.openAPIV3Schema.properties[metadata]: Forbidden: must not specify anything other than name and generateName, but metadata is implicitly specified】。So i used command 
“kubectl delete -f setup/”，but it still looks wrong. Finally  the kube-apiserver is not running and the port 443 was not listening. 
How can i  repair my cluster.

* Prometheus Operator version:
master
* Kubernetes version information:
v1.16.2
* Kubernetes cluster kind:
Installing with kubeadm

**Comment by brancz** [comment]
kube-apiserver not running is unlikely to be a kube-prometheus issue, but rather an issue with your cluster.

cc @pgier any idea why the `kubectl apply` fails in this way?

**Comment by pgier** [comment]
This looks like the same issue as #341 and should be fixed by #362.  @mackspc can you try again using latest master?

**Comment by heroWang** [comment]
by the way, How to fix the apiservice panic issue, I have excatly the same issue.

**Comment by paulfantom** [comment]
Closing due to staleness. Please reopen if you think this is still relevant.
