### ISSUE TITLE
How do I add an annotation to the prometheus manifest?

### ISSUE THREAD

**Issue by tewing-riffyn** [prometheus-operator/kube-prometheus#359]
I am integrating Thanos into my prometheus deployment and need to assign an IAM role to the prometheus statefulset pods.   What is the jsonnet syntax needed to add this to the prometheus-prometheus.yaml file?
``
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
spec:
  podMetadata:
    annotations:
      iam.amazonaws.com/role: prometheus-iam-role-name

**Comment by brancz** [comment]
Something along the lines of:

```
{
  prometheus+:: {
    prometheus+: {
      spec+: {
        podMetadata: {
          annotations: { iam.amazonaws.com/role: 'prometheus-iam-role-name' },
        },
      },
    },
  },
}
```

If this works, would you mind creating an entry in the docs for this? I assume this is something that likely a lot of people are wondering about :)

**Comment by tewing-riffyn** [comment]
Thank youu @brancz.  I'll try it and write it up.

**Comment by paulfantom** [comment]
Closing as this appears to be answered. Please reopen if you think this is still relevant.
