### ISSUE TITLE
Support for sharding dashboards to avoid configmap size limits

### ISSUE THREAD

**Issue by e9169** [prometheus-operator/kube-prometheus#396]
**What is missing?**

Support for dashboard sharding due to configmap size limits.

**Why do we need it?**

While deploying certain dashboards generated with the import option, I get "metadata.annotations: Too long: must have at most 262144 characters"

**Environment**

Kubernetes 1.15.5 and 1.14.8

**kube-prometheus version:**

Latest

**Anything else we need to know?**:

This is the PR that applies these changes to the libs: https://github.com/grafana/jsonnet-libs/pull/159/files

**Comment by brancz** [comment]
We already put each dashboard in its own config map, I think what you may be running into is a single dashboard being too big which we can’t really solve with what you linked I believe.

**Comment by e9169** [comment]
> We already put each dashboard in its own config map, I think what you may be running into is a single dashboard being too big which we can’t really solve with what you linked I believe.

Hi @brancz No, that's really what they do with that PR and our issue involves a too big dashboard, yes. That PR fixes this issue, which describes perfectly what happens with a big dashboard:

https://github.com/grafana/tanka/issues/50

**Comment by brancz** [comment]
What you linked still shards (full) dashboards only, but does not address the fact that when _single_ dashboard is too large this still happens. We're already doing what you linked in a more primitive way, by not using up all the space available but just putting 1 dashboard into 1 configmap.

**Comment by e9169** [comment]
> What you linked still shards full dashboards only, but does not address the fact that when _single_ dashboard is too large this still happens. We're already doing what you linked in a more primitive way, by not using up all the space available but just putting 1 dashboard into 1 configmap.

I don't fully understand your point, sorry. The change introduced in the PR and Issue mentioned above says " // Optionally shard dashboards into multiple config maps.", and this change is made only to address the error of annotation being too large for a SINGLE dashboard. In fact, we have many dashboards and only a few of them throw the error.

**Comment by brancz** [comment]
What you linked puts multiple dashboards (or all if sharding is disabled) into one configmap and when sharding is enabled it distributes the full dashboards across multiple config maps but doesn’t split dashboards themselves. At least I can’t see in the code where it does that. I can only spot where the dashboards choose their shard, and that process we already kind of do as we essentially have number of shards equal to the amount of dashboards.

**Comment by e9169** [comment]
> What you linked puts multiple dashboards (or all if sharding is disabled) into one configmap and when sharding is enabled it distributes the full dashboards across multiple config maps but doesn’t split dashboards themselves. At least I can’t see in the code where it does that. I can only spot where the dashboards choose their shard, and that process we already kind of do as we essentially have number of shards equal to the amount of dashboards.

Thanks, now it's perfectly clear. I suppose there is no way then to split a big dashboard into different configmaps, right?

**Comment by brancz** [comment]
I am not aware of a way to do that. Maybe we can experiment with how much in size a dashboard would shrink when gzipped, and if it's significant maybe we can convince Grafana to allow loading gzipped dashboards? That's what we did when the Prometheus configuration became too huge and it hasn't been a problem since.

**Comment by GTB3NW** [comment]
I get this with https://grafana.com/grafana/dashboards/1860

Would be great to have another way to load big dashboards

**Comment by pharaujo** [comment]
While there is no long-term fix from Grafana, and understanding that there is actually nothing that can reasonably be done in `kube-prometheus`, I want to share the workaround we found for this particular issue. The problem stems from kubectl trying to save the configmap payload in the `last-applied-configuration` annotation, so what we did internally was to try and not have that annotation. You can do that by e.g.:
- using `--server-side=true` with `kubectl apply`;
- using `kubectl replace`;
- in our case, we use ArgoCD for deployments, and so we added [`argocd.argoproj.io/sync-options: Replace=true`](https://argoproj.github.io/argo-cd/user-guide/sync-options/#replace-resource-instead-of-applying-changes) annotation to our dashboard configmaps.

**Comment by paulfantom** [comment]
>  Grafana should be able to reconstruct the original JSON dashboard from individual parts.

That part is not possible due to how grafana is implemented. I also would not want to go that route as it is very error-prone. 

> Another suggestion is to rewrite the JSON file using Grafonnet.

AFAIK Grafonnet cannot be read directly by grafana, so we still need to ship JSON inside a ConfigMap.

> Does a dashboard used for monitoring need to be that big?

That's the key. IMHO that dashboard is too crowded, but I would be lying if I said I do not use it :)

---

That said I see 3 options to solve this issue:
1) Use std.manifestJsonMinified() and remove all whitespaces.
2) swap to using `binaryData` in ConfigMap and ship dashboards as base64-encoded strings.

The former requires jsonnet version which wasn't released yet, so not ideal. The latter one should be simple to implement in https://github.com/brancz/kubernetes-grafana

**Comment by dimm0** [comment]
Still no way to import the dashboard?

**Comment by pharaujo** [comment]
@dimm0 there are several ways to import the dashboard (e.g. described [here](https://github.com/prometheus-operator/kube-prometheus/issues/396#issuecomment-919026233)); the sharding of large dashboards, though, is still not possible.
