### ISSUE TITLE
Can anyone share how to do this config change for Kube-state-metrics resources?

### ISSUE THREAD

**Issue by peidong-hu** [prometheus-operator/kube-prometheus#416]
In the documentation, it says,
====
In some environments, kube-state-metrics may need additional resources. One driver for more resource needs, is a high number of namespaces. There may be others.

kube-state-metrics resource allocation is managed by addon-resizer You can control it's parameters by setting variables in the config. They default to:

    kubeStateMetrics+:: {
      baseCPU: '100m',
      cpuPerNode: '2m',
      baseMemory: '150Mi',
      memoryPerNode: '30Mi',
    }
=====
Can anyone share with me how exactly I can change this config? Do I need to install Addon-resizer and Vertical AutoScaler addon in k8s? I have searched the Vertical Autoscaler repo, it has install script, but there is no installation guide for Addon-resizer there, https://github.com/kubernetes/autoscaler

I have the mentioned kube-state-metrics resources shortage issue. I will need to make this config for the pod-nanny to make addon-resizer to resize the kube-state-container.

Thanks,

**Comment by DimitrijeManic** [comment]
Are you installing kube-prometheus using this library? 
Addon-resizer is run in the same pod as kube-state-metrics and doesn't require additional setup.
To change the resources you would set these configs in your main.jsonnet.
```JSONNET
local kp = (import 'kube-prometheus/kube-prometheus.libsonnet') + {
  _config+:: {
    namespace: 'monitoring',

    kubeStateMetrics+:: {
      baseCPU: '100m',
      cpuPerNode: '2m',
      baseMemory: '150Mi',
      memoryPerNode: '30Mi',
    }
  },
};

{ ['00namespace-' + name]: kp.kubePrometheus[name] for name in std.objectFields(kp.kubePrometheus) } +
{ ['0prometheus-operator-' + name]: kp.prometheusOperator[name] for name in std.objectFields(kp.prometheusOperator) } +
{ ['node-exporter-' + name]: kp.nodeExporter[name] for name in std.objectFields(kp.nodeExporter) } +
{ ['kube-state-metrics-' + name]: kp.kubeStateMetrics[name] for name in std.objectFields(kp.kubeStateMetrics) } +
{ ['alertmanager-' + name]: kp.alertmanager[name] for name in std.objectFields(kp.alertmanager) } +
{ ['prometheus-' + name]: kp.prometheus[name] for name in std.objectFields(kp.prometheus) } +
{ ['grafana-' + name]: kp.grafana[name] for name in std.objectFields(kp.grafana) }
```

**Comment by paulfantom** [comment]
Closing as this appears to be answered. Please reopen if you think this is still relevant.
