### ISSUE TITLE
sync kubernetes-mixin of kubernetes-system-kubelet rule

### ISSUE THREAD

**Issue by wu0407** [prometheus-operator/kube-prometheus#421]
**What did you do?**
It is  4 mouth ago not sync kubernetes-mixin of kubernetes-system-kubelet rule that add `KubeletPlegDurationHigh` and `KubeNodeReadinessFlapping` .  

**Did you expect to see some different?**
Two rules are missing

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
Insert Prometheus Operator logs relevant to the issue here
```

* Prometheus Logs:

```
Insert Prometheus logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by brancz** [comment]
The PR was only merged this week. It'll trickle in within the next couple of days probably :)

**Comment by wu0407** [comment]
thanks

**Comment by paulfantom** [comment]
I think this was already fixed. Please reopen if this is still an issue.
