### ISSUE TITLE
Can not find release 0.18.1 any more

### ISSUE THREAD

**Issue by Cherishty** [prometheus-operator/kube-prometheus#422]
I remember that I used kube-prometheus 0.18.1 to setup my monitoring system one year ago (maybe Oct 2018) from this repo. (And my grafana version was 5.0.3 at that time)
But for now I can't find this branch, nor release. So that it's hard to debug or customize my metrics and board.

What changes have been made since that time, any suggestion I can take? (maybe I need to upgrade it to the latest version, but I wonder whether my customized metrics and grafana board still work?)

**Comment by Cherishty** [comment]
I can find v0.18.1 from prometheus-operator repo:  https://github.com/coreos/prometheus-operator/releases/tag/v0.18.1
But I do believe I download the package from this repo, as it contains a `manifests` folder, as well grafana has been built-in much of dashboards

**Comment by brancz** [comment]
Kube prometheus was never versioned it only happened to be in the same repo as prometheus operator, which made it seem like that. We moved it into this separate repo about a year or so ago.

**Comment by paulfantom** [comment]
Closing as this appears to be answered. Please reopen if you think this is still relevant.
