### ISSUE TITLE
Add node problem detector

### ISSUE THREAD

**Issue by omerlh** [prometheus-operator/kube-prometheus#433]
**What is missing?**
[Node Problem Detector](https://github.com/helm/charts/tree/master/stable/node-problem-detector)

**Why do we need it?**
Detect issues at node level. Install it + add rules/alerts/dashboards

**Comment by brancz** [comment]
I feel like that might be better suited as a separate jsonnet package. We’d be more than happy to link to any such integrations in the readme!

**Comment by omerlh** [comment]
Just filed an issue!

**Comment by paulfantom** [comment]
Closing due to staleness. Please reopen if you think this is still relevant.
