### ISSUE TITLE
Why insecureSkipVerify: true is configured for Kubelet metrics 

### ISSUE THREAD

**Issue by sachinmsft** [prometheus-operator/kube-prometheus#444]
In the generated manifest I see that servicemonitor for the Kubelet specify  insecureSkipVerify: true 
https://github.com/coreos/kube-prometheus/blob/master/manifests/prometheus-serviceMonitorKubelet.yaml#L70 

what is the reason behind this ?

**Comment by paulfantom** [comment]
This is an option that can be overridden by end-user and lack of cert verification works better for demo purposes. Example for jsonnet override can be found here: https://github.com/openshift/cluster-monitoring-operator/blob/master/jsonnet/prometheus.jsonnet#L112-L114

**Comment by paulfantom** [comment]
We have an issue to allow creating valid TLS certs in https://github.com/prometheus-operator/kube-prometheus/issues/179. Closing this as a duplicate.
