### ISSUE TITLE
spec.storage.volumeClaimTemplate do not support annotations

### ISSUE THREAD

**Issue by ox821110** [prometheus-operator/kube-prometheus#490]
Hi Support,
     I have a kubernetes cluster is on IBM Cloud, when I adding the object storage for the persistant storage on kube-prometheus, find that the iusse is in the custom CRD here https://github.com/coreos/kube-prometheus/blob/75c532df174e3f15f89548c95f5657797fb2cd0e/manifests/setup/prometheus-operator-0prometheusCustomResourceDefinition.yaml#L4275

    Please have a look at my yaml:
-------------------------------------------------------------------------------------------------
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  image: quay.io/prometheus/prometheus:v2.15.2
  nodeSelector:
    kubernetes.io/os: linux
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  replicas: 2
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  storage:
    volumeClaimTemplate:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        annotations:
          ibm.io/auto-create-bucket: "false"
          ibm.io/auto-delete-bucket: "false"
          ibm.io/bucket: "prometheus-test"
          ibm.io/secret-name: "cos-write-access"
          volume.beta.kubernetes.io/storage-class: ibmc-s3fs-standard-perf-cross-region
          volume.beta.kubernetes.io/storage-provisioner: ibm.io/ibmc-s3fs
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 15Gi
        storageClassName: ibmc-s3fs-standard-perf-cross-region
  version: v2.15.2
-----------------------------------------------------------------------------------------------
    The custom resource property 'volumeClaimTemplate' is not supporting annotations in the PVC yaml. This means that the keys defined in the annotations section are not getting passed to be resolved. As I have used kube-prometheus, I hope this problem in the operator code will be fixed

**Comment by ox821110** [comment]
[prometheus-prometheus.zip](https://github.com/coreos/kube-prometheus/files/4457112/prometheus-prometheus.zip)

**Comment by paulfantom** [comment]
This was fixed in later versions of prometheus-operator (0.40+). Please reopen if this is still an issue.
