### ISSUE TITLE
Default Prometheus ClusterRole is missing permissions compared to prometheus-operator documentation

### ISSUE THREAD

**Issue by yogeek** [prometheus-operator/kube-prometheus#492]
**What happened?**

The default [Prometheus ClusteRole in kube-prometheus](https://github.com/coreos/kube-prometheus/blob/3c109369d4d4e19d2bab9e073797eb971a5eb957/manifests/prometheus-clusterRole.yaml) is missing some permissions compared to the [Prometheus ClusterRole from documentation](https://github.com/coreos/prometheus-operator/blob/master/Documentation/rbac.md#prometheus-rbac) from the documentation of prometheus-operator

**Did you expect to see some different?**

Yes, I expected the ClusterRole provided by default with kube-prometheus installation to be the one indicated in the prometheus-operator documentation.

**Environment**

* Prometheus Operator version:

`kube-prometheus release-0.4`

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: `kubeadm`

**Comment by brancz** [comment]
This is intentional. kube-prometheus configures Prometheus with the principle of least privilege, meaning permission is granted specifically for each namespace when needed instead of for every namespace, even where it's not needed.

**Comment by brancz** [comment]
There is already a patch for it, but the docs need some improvement. RE: https://github.com/coreos/kube-prometheus/issues/350

If you would like to improve docs, then I'd be more than happy to review! :)

**Comment by yogeek** [comment]
I will try to do that, thanks for your help @brancz  !

**Comment by SayakMukhopadhyay** [comment]
@brancz I want to have a go at documenting this. There is another mixin related to #72 that is undocumented and I want to try at least a basic documentation for both. Is that fine?

**Comment by mikouaj** [comment]
@brancz I think the problem strikes back. 
The [ClusterRole](https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/prometheus-clusterRole.yaml) used by 'k8s-prometheus' from the main branch is missing a lot of rules when compared to the [Prometheus RBAC](https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/prometheus-clusterRole.yaml) docs.

Because of this, Prometheus can't list / watch services i.e. selected by `ServiceMonitor`:
```
ts=2023-02-28T14:15:32.989Z caller=klog.go:116 level=error component=k8s_client_runtime func=ErrorDepth msg="pkg/mod/k8s.io/client-go@v0.26.1/tools/cache/reflector.go:169: Failed to watch *v1.Service: failed to list *v1.Service: services is forbidden: User \"system:serviceaccount:monitoring:prometheus-k8s\" cannot list resource \"services\" in API group \"\" in the namespace \"kueue-system\""
```

**Comment by jgehrcke** [comment]
@mikouaj did you try following https://github.com/prometheus-operator/kube-prometheus/blob/main/docs/monitoring-other-namespaces.md? I got the same error as you, but I also missed reading that part of the docs before. Trying that solution out right now.
