### ISSUE TITLE
Bump Go to 1.14

### ISSUE THREAD

**Issue by dgrisonnet** [prometheus-operator/kube-prometheus#493]
Follow-up issue to the following discussion: https://github.com/coreos/kube-prometheus/pull/482#issuecomment-613448615

Step to follow:
- Update Go version in `go.mod`
- Update Makefile $(TOOLING) rule to use `go build -o` instead of `go install`
- Move tooling dependencies from `go.mod` to `scripts/go.mod`
- Don't export `GO111MODULE=on` anymore

**Comment by paulfantom** [comment]
Fixed with #787
