### ISSUE TITLE
Manage Prometheus operator

### ISSUE THREAD

**Issue by guleng** [prometheus-operator/kube-prometheus#497]
I have 10 Prometheus operators and a lot of data (2t for each). I want to manage them. I want to display configuration rules and alarm display in one place, just like ZABBIX, where all alarms can be viewed. Do you have a good recommendation

**Comment by brancz** [comment]
You should be sending all alerts to the same Alertmanager cluster, that's where aggregation is intended to happen. We have a similar situation, and at least for configuration, etc. we just provision clusters consistently from version control.

Another interesting thing happening in this area (if merged) is this proposal currently being worked on within Thanos: https://github.com/thanos-io/thanos/pull/2263.

**Comment by guleng** [comment]
@brancz 
Prometheus operator supports specifying the alertmanagement address in another k8s cluster? I can't find the configuration item in the document

**Comment by brancz** [comment]
Best is to use the additionalAlertmanagerConfigs feature which lets you specify raw prometheus discovery config.

**Comment by guleng** [comment]
@brancz 
I've seen that there are 6000000 pieces of data and 1TB of storage, but I / O is a bottleneck when I want to use tanos. I have eight Prometheus of this size. At present, I don't know where the bottleneck of a single Prometheus of this size is

**Comment by brancz** [comment]
That heavily depends on your usage. For most setups memory is the biggest bottleneck. If you think IO is then you should be able to see that in metrics.

**Comment by paulfantom** [comment]
Closing as this appears to be answered. Please reopen if you think this is still relevant.
