### ISSUE TITLE
Compatibility Matrix for 0.5.0

### ISSUE THREAD

**Issue by texasbobs** [prometheus-operator/kube-prometheus#563]
We have been using 0.5.0 on v1.17 and noticed that it was removed from the compatibility list in https://github.com/coreos/kube-prometheus/pull/552

Are there some identified incompatibilities or is this a result of the versions just not being tested?

**Comment by dgrisonnet** [comment]
We noticed an incompatibility after [#408](https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/408) was merged in kubernetes-mixin release-0.4.

**Comment by texasbobs** [comment]
Great.  I think we can work around that and continue to use 0.5.0 with 1.17.

**Comment by paulfantom** [comment]
Closing due to staleness. Please reopen if you think this is still relevant.
