### ISSUE TITLE
Refactor kube-prometheus to remove mutation of global state

### ISSUE THREAD

**Issue by brancz** [prometheus-operator/kube-prometheus#566]
kube-prometheus in its current form heavily mutates what is effectively global state, this makes working with it sometimes somewhat surprising and difficult to get into. We should refactor it to make more use of local configurations so we can iterate faster again and make working with it more joyful again.

Various components in themselves have already done this, but the "main" kube-prometheus entry-points still merge everything into one giant global state with a global configuration. These should be local configurations configured through a main configuration explicitly instead of implicitly by merging things together and magically using the same configuration values, which is very brittle.

**Comment by paulfantom** [comment]
Closing as I believe we are no longer mutating global state.
