### ISSUE TITLE
How to setup custom  metrics

### ISSUE THREAD

**Issue by yangvipguang** [prometheus-operator/kube-prometheus#571]
**What did you do?**
now, does custom metrics files been removed? i do not know how to config this .  Should I generate these files with jsonnet? because I find the custom.metrics with jsonnet format 。 
**Did you expect to see some different?**

**Environment**

* Prometheus Operator version:
    
    quay.io/coreos/prometheus-operator:v0.39.0
* Kubernetes version information:
1.16.x

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
Insert Prometheus Operator logs relevant to the issue here
```

* Prometheus Logs:

```
Insert Prometheus logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by johanneswuerbach** [comment]
Hey @yangvipguang,

yes you need to setup jsonnet https://github.com/coreos/kube-prometheus/blob/master/README.md#compiling

Once that is done you can uncomment https://github.com/coreos/kube-prometheus/blob/master/example.jsonnet#L9 this line and you get the extra manifests needed for custom metrics.

Cheers,
Johannes

**Comment by yangvipguang** [comment]
thanks a lot 。but I  have switched to  branch of release-0.4。 I found the cutom metrics in the experimental files 。 but I have some error with permissions。Could you give me a favor
![image](https://user-images.githubusercontent.com/11416887/84629968-c0190900-af1d-11ea-809b-9fa7b7e99c96.png)

I have to generate some other files like  ca etcs

**Comment by johanneswuerbach** [comment]
This sounds like you didn't follow https://github.com/coreos/kube-prometheus#prerequisites, did you?

**Comment by yangvipguang** [comment]
i have figured 。may be i changed incrrectly when config custom metrics。  i have deploy the custom yaml files I have found the api versions ：custom api versions  but i returned some errors 。
![image](https://user-images.githubusercontent.com/11416887/84632499-96fa7780-af21-11ea-85d3-df1bcb01d67e.png)

**Comment by metalmatze** [comment]
Maybe the video from last years FOSDEM might help too: https://www.youtube.com/watch?v=paO2kwHWOLw :)

**Comment by evgao** [comment]
Hi Guys, 

I am trying to build release-0.5 with custom-metrics, I uncomment the line in example.jsonnet and it looks like the following:


```shell
local kp =
  (import 'kube-prometheus/kube-prometheus.libsonnet') +
  (import 'kube-prometheus/kube-prometheus-custom-metrics.libsonnet') +
```


when I build with `./build.sh example.jsonnet` command, it failed with the follow error message:


```shell
RUNTIME ERROR: couldn't open import "kube-prometheus/kube-prometheus-custom-metrics.libsonnet": no match locally or in the Jsonnet library paths
```


When I build without custom-metrics, it works fine. Kindly advise how to fix it. Thanks a lot.

**Comment by yangvipguang** [comment]
@evgao   you should  run ： jb install  first  and then  ./build.sh

**Comment by evgao** [comment]
@yangvipguang Thanks Guang, It works now.

**Comment by rbtrun** [comment]
hi guys, 

Also want open customer metrics with this:
`  (import 'kube-prometheus/kube-prometheus-custom-metrics.libsonnet') `

But meet this error:
`RUNTIME ERROR: couldn't open import "kube-prometheus/kube-prometheus-custom-metrics.libsonnet": no match locally or in the Jsonnet library paths`

Indeed there is file
`kube-prometheus/kube-prometheus-custom-metrics.libsonnet`

How can I get this file or is there a sample file for this?
