### ISSUE TITLE
persistent volume monitor

### ISSUE THREAD

**Issue by CCrainys** [prometheus-operator/kube-prometheus#578]
Hi,

**What did you do?**
I use kube-prometheus to deploy prometheus to monitor my kubernetes cluster.  When I try to monitor persistent volume in my kubernetes clusters, I found no data was provided.

The picture is provied by grafana, and the type of persistent volume is local storage

<img width="1342" alt="Screen Shot 2020-06-21 at 5 15 32 PM" src="https://user-images.githubusercontent.com/18700694/85221154-27cec880-b3e4-11ea-9fff-937f6ca4cfd2.png">

What should I do to get data about persistent volume performance in prometheus?

**Environment**

* kube-prometheus  version:

  release-0.5

* Kubernetes version information:

    `kubectl version`
   v1.18.3

* Kubernetes cluster kind:

  create cluster through " kubeadm init" command 

Looking forward to your reply!

**Comment by CCrainys** [comment]
OK

**Comment by paulfantom** [comment]
This was fixed recently in kubernetes-mixin and should be already included on `main` branch of kube-prometheus. Please reopen if this is still an issue.
