### ISSUE TITLE
LDAP integration for grafana using jsonnet

### ISSUE THREAD

**Issue by rupadhya1** [prometheus-operator/kube-prometheus#632]
I  am trying to enable LDAP integration for grafana
This is my simplified custom jsonnet

local kp =
  (import 'kube-prometheus/kube-prometheus.libsonnet') +
{
    _config+:: {
      namespace: 'monitoring',

      grafana+:: {
        config: {
          sections: {
            metrics: { enabled: true },
            'auth.ldap': {
              enabled: true,
              config_file: '/etc/grafana/ldap.toml',
              allow_sign_up: true,
            },
          },
        },
        ldap: |||
          [[servers]]
          host = "127.0.0.1"
          port = 389
          use_ssl = false
          start_tls = false
          ssl_skip_verify = false

          bind_dn = "cn=admins,dc=example,dc=com"
          bind_password = 'grafana'

          search_filter = "(cn=%s)"
          search_base_dns = ["dc=example,dc=com"]
        |||,
    },
  },
};

I am getting an error "Text block not terminated with |||"
ldap.jsonnet:20:15 Text block not terminated with |||

        ldap: |||

I am unable to identify any syntax errors in the jsonnet file itself.  What else could be wrong?

**Comment by brancz** [comment]
hmm strange I tried this example https://github.com/brancz/kubernetes-grafana#config-customization and it works just fine

**Comment by brancz** [comment]
Actually this appears to work just fine for me:

```jsonnet
local kp = (import 'kube-prometheus/kube-prometheus.libsonnet') + {
  _config+:: {
    namespace: 'monitoring',

    grafana+:: {
      config: {
        sections: {
          metrics: { enabled: true },
          'auth.ldap': {
            enabled: true,
            config_file: '/etc/grafana/ldap.toml',
            allow_sign_up: true,
          },
        },
      },
      ldap: |||
        [[servers]]
        host = "127.0.0.1"
        port = 389
        use_ssl = false
        start_tls = false
        ssl_skip_verify = false

        bind_dn = "cn=admins,dc=example,dc=com"
        bind_password = 'grafana'

        search_filter = "(cn=%s)"
        search_base_dns = ["dc=example,dc=com"]
      |||,
    },
  },
};

// render
```

Maybe try updating your jsonnet version?

**Comment by rupadhya1** [comment]
Thank you Frederic @brancz I had already updated my jb, jsonnet etc.
The issue turned out to be CRLF line terminators in my jsonnet file. 

_file custom.jsonnet
custom.jsonnet: ASCII text, with CRLF line terminators_

I was able to resolve it by ensuring the file was ASCII text.

**Comment by brancz** [comment]
Happy you were able to figure it out! :) 

Closing here but as always if you feel there is another issue with kube-prometheus feel free to open a new issue!
