### ISSUE TITLE
kube-prometheus v0.60 how to create kube-controller-manager and kube-scheduler service

### ISSUE THREAD

**Issue by ktpktr0** [prometheus-operator/kube-prometheus#633]
This repository now has the new GitHub Discussions enabled: 
https://github.com/coreos/kube-prometheus/discussions

Please create a new discussion to ask for any kind of support, which is not a Bug or Feature Request.
k8s version: 1.17.3
docker version: 19.03
kube-prometheus version: 0.60
Thank you for being part of this community!

---

We are still happy to chat with you in the #prometheus-operator channel on Kubernetes Slack!

I installed kube-prometheus of the master branch, and the tags of kube-controller-manager and kube-scheduler in the prometheus backend were empty. I tried to add services to them and found that it did not work.

I check the servicemonitor of kube-controller-manager and kube-scheduler, they have changed from http to https.
 
sourceLabels:
      - __name__
    port: https-metrics
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: kube-controller-manager

So I changed the service to https-metrice. 

apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kube-controller-manager-prometheus-discovery
  labels:
    k8s-app: kube-controller-manager
spec:
  selector:
    component: kube-controller-manager
  type: ClusterIP
  clusterIP: None
  ports:
  - name: https-metrics
    port: 10252
    targetPort: 10252
    protocol: TCP

At this time, the taget already exists, but it still reports an error

![image](https://user-images.githubusercontent.com/41657218/89479619-d88efc80-d7c5-11ea-9c59-7f8d427f7c95.png)

Is the metrice port of https different from http？

**Comment by brancz** [comment]
As the error says, it appears that the port is not serving https, but http.

**Comment by Yangstatus** [comment]
This is because the Kube-scheduler component is bound on 127.0.0.1 by default, and we want to access it through node IP, so the access is denied. As long as the kube-scheduler binding address is modified to 0.0.0.0, the requirements can be met. The monitoring of kube-Controller-Manager is similar

**Comment by ktpktr0** [comment]
> This is because the Kube-scheduler component is bound on 127.0.0.1 by default, and we want to access it through node IP, so the access is denied. As long as the kube-scheduler binding address is modified to 0.0.0.0, the requirements can be met. The monitoring of kube-Controller-Manager is similar

I tried to change the listening address of Kube-scheduler and kube-Controller-Manager to 0.0.0.0, but the error persists

**Comment by brancz** [comment]
Change the scheme to `http`, your setup doesn't seem to be using HTTPS.

**Comment by ktpktr0** [comment]
> 将方案更改为`http`，您的设置似乎未使用HTTPS。

ok.  What should I do if I use https for setup

**Comment by brancz** [comment]
I'm not sure where you got the manifests you shared, but the ports seem to be incorrect looking at kops for example: https://github.com/prometheus-operator/kube-prometheus/blob/master/jsonnet/kube-prometheus/kube-prometheus-kops.libsonnet

**Comment by ktpktr0** [comment]
> 我不确定您在哪里共享清单，但是例如查看kops的端口似乎不正确：[https](https://github.com/prometheus-operator/kube-prometheus/blob/master/jsonnet/kube-prometheus/kube-prometheus-kops.libsonnet)：[//github.com/prometheus-operator/kube-prometheus/blob/master/jsonnet/kube-普罗米修斯/kube-prometheus-kops.libsonnet](https://github.com/prometheus-operator/kube-prometheus/blob/master/jsonnet/kube-prometheus/kube-prometheus-kops.libsonnet)

我尝试修改service为文件内的端口，但工作不正常。
KubeScheduler:
![image](https://user-images.githubusercontent.com/41657218/89633418-6823d080-d8d6-11ea-9c85-3c5b91a9725e.png)
KubeControllerManager:
![image](https://user-images.githubusercontent.com/41657218/89633451-740f9280-d8d6-11ea-95ef-0c538c389997.png)

**Comment by Yangstatus** [comment]
Check that the corresponding configuration item in ServiceMonitor matches the new HTTPS metrics.
for example :

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prometheus-operator-kube-controller-manager
    release: prometheus-operator-1582789252
  name: prometheus-operator-158278-kube-controller-manager
  namespace: default
spec:
  endpoints:
    port: http-metrics
  jobLabel: jobLabel
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app: prometheus-operator-kube-controller-manager
      release: prometheus-operator-1582789252

**Comment by ktpktr0** [comment]
> 检查ServiceMonitor中的相应配置项是否与新的HTTPS指标匹配。
> 例如 ：
> 
> apiVersion：Monitoring.coreos.com/v1
> 类型：ServiceMonitor
> 元数据：
> 标签：
> 应用：prometheus-operator-kube-controller-manager
> 版本：prometheus-operator-1582789252
> 名称：prometheus-operator-158278-kube-controller-manager
> 命名空间：默认
> 规格：
> 端点：
> 端口：http-metrics
> jobLabel：jobLabel
> namespaceSelector：
> matchNames：
> -kube系统
> 选择器：
> matchLabels：
> app：prometheus-operator-kube-controller-manager
> 版本：prometheus-operator-1582789252

The following is my newly changed configuration, the fault remains

servicemonitor:
![image](https://user-images.githubusercontent.com/41657218/89747697-8403be00-daf2-11ea-8087-5a5005e3c016.png)

service:
![image](https://user-images.githubusercontent.com/41657218/89747717-94b43400-daf2-11ea-9553-e3bf6104fc48.png)

**Comment by Yangstatus** [comment]
> > 检查ServiceMonitor中的相应配置项是否与新的HTTPS指标匹配。
> > 例如 ：
> > apiVersion：Monitoring.coreos.com/v1
> > 类型：ServiceMonitor
> > 元数据：
> > 标签：
> > 应用：prometheus-operator-kube-controller-manager
> > 版本：prometheus-operator-1582789252
> > 名称：prometheus-operator-158278-kube-controller-manager
> > 命名空间：默认
> > 规格：
> > 端点：
> > 端口：http-metrics
> > jobLabel：jobLabel
> > namespaceSelector：
> > matchNames：
> > -kube系统
> > 选择器：
> > matchLabels：
> > app：prometheus-operator-kube-controller-manager
> > 版本：prometheus-operator-1582789252
> 
> The following is my newly changed configuration, the fault remains
> 
> servicemonitor:
> ![image](https://user-images.githubusercontent.com/41657218/89747697-8403be00-daf2-11ea-8087-5a5005e3c016.png)
> 
> service:
> ![image](https://user-images.githubusercontent.com/41657218/89747717-94b43400-daf2-11ea-9553-e3bf6104fc48.png)


Controller Manager binds the unsafe port 10252 to 127.0.0.1 to ensure that KuebCTL GET CS returns correctly;Bind secure port 10257 to 0.0.0.0 to expose, provide service invocation;Since controller Manager is starting to connect to apiserver's 6443 authentication port, the -- use-service-account-Credentials option is required to let Controller Manager create a separate Service Account (default System: Kube-Controller-Manager users do not have such high credentials)

Edit the Kube-Controller-Manager core file：

###
# The following values are used to configure the kubernetes controller-manager

# defaults from config and apiserver should be adequate

# Add your own!
KUBE_CONTROLLER_MANAGER_ARGS="--address=127.0.0.1 \
                             --authentication-kubeconfig=/etc/kubernetes/config/kube-controller-manager.kubeconfig \
                             --authorization-kubeconfig=/etc/kubernetes/config/kube-controller-manager.kubeconfig \
                             --bind-address=0.0.0.0 \
                             --cluster-name=kubernetes \
                             --cluster-signing-cert-file=/etc/kubernetes/ssl/ca.pem \
                             --cluster-signing-key-file=/etc/kubernetes/ssl/ca-key.pem \
                             --client-ca-file=/etc/kubernetes/ssl/ca.pem \
                             --controllers=*,bootstrapsigner,tokencleaner \
                             --deployment-controller-sync-period=10s \
                             --experimental-cluster-signing-duration=87600h0m0s \
                             --enable-garbage-collector=true \
                             --kubeconfig=/etc/kubernetes/config/kube-controller-manager.kubeconfig \
                             --leader-elect=true \
                             --node-monitor-grace-period=20s \
                             --node-monitor-period=5s \
                             --port=10252 \
                             --pod-eviction-timeout=2m0s \
                             --requestheader-client-ca-file=/etc/kubernetes/ssl/ca.pem \
                             --terminated-pod-gc-threshold=50 \
                             --tls-cert-file=/etc/kubernetes/ssl/kube-controller-manager.pem \
                             --tls-private-key-file=/etc/kubernetes/ssl/kube-controller-manager-key.pem \
                             --root-ca-file=/etc/kubernetes/ssl/ca.pem \
                             --secure-port=10257 \
                             --service-cluster-ip-range=10.254.0.0/16 \
                             --service-account-private-key-file=/etc/kubernetes/ssl/ca-key.pem \
                             --use-service-account-credentials=true \
                             --v=2"

Make sure that secure port 10257 is bound to 0.0.0.0

**Comment by ktpktr0** [comment]
@Yangstatus 

According to your configuration, I modified kube-controller-manager.yaml
Doesn't seem to work

![image](https://user-images.githubusercontent.com/41657218/89749619-19a34b80-dafb-11ea-9976-2a78679c8593.png)

**Comment by Yangstatus** [comment]
> @Yangstatus
> 
> 根据您的配置，我修改了kube-controller-manager.yaml
> 似乎不起作用
> 
> ![图片](https://user-images.githubusercontent.com/41657218/89749619-19a34b80-dafb-11ea-9976-2a78679c8593.png)

Can you check the port service to which Kube-Controller-Manager is bound ? 

If it's AN HTTP request:

curl http://127.0.0.1:10252/metrics     can request to the data？

**Comment by ktpktr0** [comment]
@Yangstatus Before v0.60, it was http, and http was normal. Now I want to how to access metrice through https

**Comment by Yangstatus** [comment]
> @Yangstatus Before v0.60, it was http, and http was normal. Now I want to how to access metrice through https

HTTPS requires a certificate to communicate with apiserver, which means you need to configure the CA certificate to restart the Kube-Controller-Manager service

**Comment by Yangstatus** [comment]
This is a case of sharing that I found on the Internet：

https://my.oschina.net/u/4302974/blog/3799945

**Comment by ktpktr0** [comment]
My k8s is installed using kubeadm

**Comment by Yangstatus** [comment]
> My k8s is installed using kubeadm

You can manually modify the files in the KubeADM deployment directory and restart them after modification.
vim  /etc/kubernetes/manifests/kube-controller-manager.yaml

**Comment by ktpktr0** [comment]
The previous screenshot is the modified yaml file

**Comment by Yangstatus** [comment]
> The previous screenshot is the modified yaml file

Check whether the service is bound to the corresponding port：

netstat -anput | grep kube-controlle

**Comment by ktpktr0** [comment]
![image](https://user-images.githubusercontent.com/41657218/89758371-300ccf80-db1a-11ea-8e89-048213fda477.png)

**Comment by Yangstatus** [comment]
You can disable port 10252 by editing Kube-Controller-Manager.Yaml add --port=0 only keep -- bind-Address =0.0.0.0  

Then through the CA certificate to request to https://localhost:10257/metrics

**Comment by ktpktr0** [comment]
kube-controller-manager.yaml The file does not have this option by default

**Comment by Yangstatus** [comment]
> kube-controller-manager.yaml The file does not have this option by default

Kubeadm default installation of cluster can be in the/etc/kubernetes manifests directory to generate the corresponding yaml listing

**Comment by ktpktr0** [comment]
[root@k8s-master1 ]# cat /etc/kubernetes/manifests/kube-controller-manager.yaml | egrep "10252|port"
    - --secure-port=10257
        port: 10257

**Comment by ktpktr0** [comment]
[root@k8s-master1 ]# cat /etc/kubernetes/manifests/kube-controller-manager.yaml | egrep "10252|port"
    - --secure-port=10257
        port: 10257

**Comment by Yangstatus** [comment]
Can you provide full YAML content?

**Comment by ktpktr0** [comment]
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-controller-manager
    tier: control-plane
  name: kube-controller-manager
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-controller-manager
    - --allocate-node-cidrs=true
    - --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --bind-address=0.0.0.0
    - --secure-port=10257
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --cluster-cidr=10.244.0.0/16
    - --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt
    - --cluster-signing-key-file=/etc/kubernetes/pki/ca.key
    - --controllers=*,bootstrapsigner,tokencleaner
    - --kubeconfig=/etc/kubernetes/controller-manager.conf
    - --leader-elect=true
    - --node-cidr-mask-size=24
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --root-ca-file=/etc/kubernetes/pki/ca.crt
    - --service-account-private-key-file=/etc/kubernetes/pki/sa.key
    - --service-cluster-ip-range=10.96.0.0/12
    - --use-service-account-credentials=true
    image: registry.aliyuncs.com/google_containers/kube-controller-manager:v1.17.3
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10257
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-controller-manager
    tier: control-plane
  name: kube-controller-manager
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-controller-manager
    - --allocate-node-cidrs=true
    - --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --bind-address=0.0.0.0
    - --secure-port=10257
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --cluster-cidr=10.244.0.0/16
    - --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt
    - --cluster-signing-key-file=/etc/kubernetes/pki/ca.key
    - --controllers=*,bootstrapsigner,tokencleaner
    - --kubeconfig=/etc/kubernetes/controller-manager.conf
    - --leader-elect=true
    - --node-cidr-mask-size=24
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --root-ca-file=/etc/kubernetes/pki/ca.crt
    - --service-account-private-key-file=/etc/kubernetes/pki/sa.key
    - --service-cluster-ip-range=10.96.0.0/12
    - --use-service-account-credentials=true
    image: registry.aliyuncs.com/google_containers/kube-controller-manager:v1.17.3
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10257
        scheme: HTTPS
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-controller-manager
    resources:
      requests:
        cpu: 200m
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
    - mountPath: /etc/pki
      name: etc-pki
      readOnly: true
    - mountPath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
      name: flexvolume-dir
    - mountPath: /etc/kubernetes/pki
      name: k8s-certs
      readOnly: true
    - mountPath: /etc/kubernetes/controller-manager.conf
      name: kubeconfig
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /etc/pki
      type: DirectoryOrCreate
    name: etc-pki
  - hostPath:
      path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
      type: DirectoryOrCreate
    name: flexvolume-dir
  - hostPath:
      path: /etc/kubernetes/pki
      type: DirectoryOrCreate
    name: k8s-certs
  - hostPath:
      path: /etc/kubernetes/controller-manager.conf
      type: FileOrCreate
    name: kubeconfig
status: {}

**Comment by ktpktr0** [comment]
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-controller-manager
    tier: control-plane
  name: kube-controller-manager
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-controller-manager
    - --allocate-node-cidrs=true
    - --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --bind-address=0.0.0.0
    - --secure-port=10257
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --cluster-cidr=10.244.0.0/16
    - --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt
    - --cluster-signing-key-file=/etc/kubernetes/pki/ca.key
    - --controllers=*,bootstrapsigner,tokencleaner
    - --kubeconfig=/etc/kubernetes/controller-manager.conf
    - --leader-elect=true
    - --node-cidr-mask-size=24
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --root-ca-file=/etc/kubernetes/pki/ca.crt
    - --service-account-private-key-file=/etc/kubernetes/pki/sa.key
    - --service-cluster-ip-range=10.96.0.0/12
    - --use-service-account-credentials=true
    image: registry.aliyuncs.com/google_containers/kube-controller-manager:v1.17.3
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10257
        scheme: HTTPS
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-controller-manager
    resources:
      requests:
        cpu: 200m
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
    - mountPath: /etc/pki
      name: etc-pki
      readOnly: true
    - mountPath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
      name: flexvolume-dir
    - mountPath: /etc/kubernetes/pki
      name: k8s-certs
      readOnly: true
    - mountPath: /etc/kubernetes/controller-manager.conf
      name: kubeconfig
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /etc/pki
      type: DirectoryOrCreate
    name: etc-pki
  - hostPath:
      path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
      type: DirectoryOrCreate
    name: flexvolume-dir
  - hostPath:
      path: /etc/kubernetes/pki
      type: DirectoryOrCreate
    name: k8s-certs
  - hostPath:
      path: /etc/kubernetes/controller-manager.conf
      type: FileOrCreate
    name: kubeconfig
status: {}

**Comment by Yangstatus** [comment]
Execute these two commands to show the screenshots：

kubectl describe endpoints -n kube-system kube-controller-manager

kubectl describe svc -n kube-system kube-controller-manager

**Comment by ktpktr0** [comment]
[root@k8s-master1 ]# kubectl describe endpoints -n kube-system kube-controller-manager
Name:         kube-controller-manager
Namespace:    kube-system
Labels:       <none>
Annotations:  control-plane.alpha.kubernetes.io/leader:
                {"holderIdentity":"k8s-master1_22c5b6c9-3abd-436f-aa41-c853ed7c6266","leaseDurationSeconds":15,"acquireTime":"2020-08-10T02:54:13Z","renew...
Subsets:
Events:  <none>
[root@k8s-master1 ]# kubectl describe svc -n kube-system kube-controller-manager         
Name:              kube-controller-manager-prometheus-discovery
Namespace:         kube-system
Labels:            k8s-app=kube-controller-manager
Annotations:       Selector:  component=kube-controller-manager
Type:              ClusterIP
IP:                None
Port:              https-metrics  10257/TCP
TargetPort:        10257/TCP
Endpoints:         Intranet address:10257
Session Affinity:  None
Events:            <none>

**Comment by Yangstatus** [comment]
Please check whether the controller rules corresponding to Prometheus monitoring kube-Controller-Manager component are correct 

Service and Endpoints

**Comment by ktpktr0** [comment]
It should be immature to use https to monitor, it is more reasonable to use http

**Comment by Yangstatus** [comment]
> It should be immature to use https to monitor, it is more reasonable to use http

The Services rule is not matched to the pod instance in Endpoints !  Maybe this is not supported.

**Comment by ktpktr0** [comment]
thanks very much for help

**Comment by ktpktr0** [comment]
@Yangstatus Try to check other https ports, such as apiserver and kubelet have errors, either rbac or Unauthorized

curl -k -L --tlsv1 https://127.0.0.1:10250/metrics
Unauthorized
==================================================
curl -k -L --tlsv1 https://127.0.0.1:6443/metrics 
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/metrics\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
}

**Comment by ktpktr0** [comment]
@Yangstatus @brancz 

I reinstalled proemtheus and modified the service configuration to https-metrics
Then monitor kube-controller-manager and kube-scheduler to 0.0.0.0, and https runs successfully
After waiting for a while, it seems to be working fine

Thanks for your help
