### ISSUE TITLE
Update prometheus-operator to 0.41.0

### ISSUE THREAD

**Issue by enkov** [prometheus-operator/kube-prometheus#639]
Hello!
First of all, thank you for a great project!
I would like to know then do you plan to update prometheus-operator to 0.41.0?

**Comment by lilic** [comment]
Hey, there is an open PR, there is a fix that needs to be done in Prometheus operator before we can do that. You can watch that PR https://github.com/prometheus-operator/kube-prometheus/pull/628 as soon as it closes it will be to 0.41 :)

**Comment by enkov** [comment]
Thank you. I will close this issue.
