### ISSUE TITLE
Quickstart servicemonitors command may be incorrect

### ISSUE THREAD

**Issue by timhughes** [prometheus-operator/kube-prometheus#640]
**What happened?**
Following the quickstart instructions at https://github.com/prometheus-operator/kube-prometheus#quickstart
Ran the following line by line and the second line just returned immediately. 
```
kubectl create -f manifests/
until kubectl get servicemonitors --all-namespaces ; do date; sleep 1; echo ""; done
kubectl apply -f manifests/
```

When run by itself
```
thughes@silicon [0] $ kubectl get servicemonitors --all-namespaces
No resources found
thughes@silicon [0] $ echo $?
0
```
**Did you expect to see some different?**
I think i expected there to be `servicemonitors` in the output

maybe something more like the output from the following command. 
```
thughes@silicon [0] $ kubectl get crd servicemonitors.monitoring.coreos.com --all-namespaces
NAME                                    CREATED AT
servicemonitors.monitoring.coreos.com   2020-08-10T17:02:44Z
```

**How to reproduce it (as minimally and precisely as possible)**:
Follow the quickstart

**Environment**
* Prometheus Operator version:

    ```Name:                   prometheus-operator
    Namespace:              monitoring
    CreationTimestamp:      Mon, 10 Aug 2020 18:02:45 +0100
    Labels:                 app.kubernetes.io/component=controller
                            app.kubernetes.io/name=prometheus-operator
                            app.kubernetes.io/version=v0.40.0
    ```

* Kubernetes version information:

    `kubectl version`
    ```
    thughes@silicon [0] $ kubectl version
    Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
    ```

* Kubernetes cluster kind:

    kubeadmin

**Anything else we need to know?**:

**Comment by brancz** [comment]
hmm you're totally right, looks like we actually made it worse when we tried to improve it :slightly_smiling_face: 

any suggestions how to fix this?

**Comment by timhughes** [comment]
From what I can tell `kubectl get servicemonitors --all-namespaces` has an exit code of `0` regardless of whether there are any service manages in existence or not.  Also the servicemonitors don't get created until the command after this check. We need to check for the CRDs explicitly. Created PR #641 with what I use in my own docs.

**Comment by brancz** [comment]
But exit code 0 is positive no? Maybe I'm misunderstanding what's wrong.

**Comment by timhughes** [comment]
Yeah the docs are correct. Left a comment at https://github.com/prometheus-operator/kube-prometheus/pull/641#issuecomment-671839859 
Sorry for chewing up you time. On the upside I have learnt something. 

Cheers
Tim
