### ISSUE TITLE
Evaluating rule failed "NodeRAIDDegraded"

### ISSUE THREAD

**Issue by yogeek** [prometheus-operator/kube-prometheus#666]
**What happened?**

The alert `PrometheusRuleFailures` is regularly fired recently and we observed these errors in prometheus-k8s pods :

```
$ stern prometheus-k8s --tail 100 -n monitoring
[...]
prometheus-k8s-1 prometheus level=warn ts=2020-09-03T12:58:16.662Z caller=manager.go:513 component="rule manager" group=node-exporter msg="Evaluating rule failed" rule="alert: NodeRAIDDegraded\nexpr: '\"node_md_disks_required - ignoring (state) (node_md_disks{state=\\\"active\\\"})\n  > 0\"'\nfor: 15m\nlabels:\n  severity: critical\nannotations:\n  description: RAID array '{{ $labels.device }}' on {{ $labels.instance }} is in degraded\n    state due to one or more disks failures. Number of spare drives is insufficient\n    to fix issue automatically.\n  runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-noderaiddegraded\n  summary: RAID Array is degraded\n" err="unhandled expression of type: *promql.StringLiteral"
[...]
``` 

Apparently, the `NodeRAIDDegraded` failed to be evaluated.

**Environment**

kube-prometheus `release-0.4` (because of k8s version 1.17 compatibility)

* Prometheus Operator version:

    `v0.35.1`

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:08:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
`

* Kubernetes cluster kind:

   kubeadm on AWS EC2

* Prometheus Operator Logs:

```
level=info ts=2020-09-03T13:48:56.604663069Z caller=operator.go:457 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
level=warn ts=2020-09-03T13:48:56.604726142Z caller=operator.go:513 component=alertmanageroperator msg="alertmanager key=monitoring/main, field spec.baseImage is deprecated, 'spec.image' field should be used instead"
```

* Prometheus Logs:

```
prometheus-k8s-1 prometheus level=warn ts=2020-09-03T12:58:16.662Z caller=manager.go:513 component="rule manager" group=node-exporter msg="Evaluating rule failed" rule="alert: NodeRAIDDegraded\nexpr: '\"node_md_disks_required - ignoring (state) (node_md_disks{state=\\\"active\\\"})\n  > 0\"'\nfor: 15m\nlabels:\n  severity: critical\nannotations:\n  description: RAID array '{{ $labels.device }}' on {{ $labels.instance }} is in degraded\n    state due to one or more disks failures. Number of spare drives is insufficient\n    to fix issue automatically.\n  runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-noderaiddegraded\n  summary: RAID Array is degraded\n" err="unhandled expression of type: *promql.StringLiteral"
```

**Anything else we need to know?**:

The node-exporter version seems to be [pinned to v0.18.1 ](https://github.com/prometheus-operator/kube-prometheus/blob/release-0.4/jsonnet/kube-prometheus/node-exporter/node-exporter.libsonnet#L8) whereas the last version is [v1.0.1](https://github.com/prometheus/node_exporter/releases/tag/v1.0.1).
Is it normal ?

Can it be linked to https://github.com/prometheus/node_exporter/commit/7dd8adf7edb968669db50d78f311d72d949812cf ?

**Comment by paulfantom** [comment]
You need node_exporter v1.0.0 for those rules to work.

**Comment by yogeek** [comment]
@paulfantom thank you for your help. 
The problem is that I used the default installation of kube-prometheus release-0.4 and I do not understand why I have these rules if the v0.18.1 node-exporter version is pinned in kube-prometheus dependencies... 
Do you have an explanation ?

**Comment by paulfantom** [comment]
It looks like some jsonnet vendor cache issue on you machine. Try cleaning dependencies and pulling them again. 

Note: node_exporter image version is not the same as node_exporter mixin version. The latter is what is important for alerting rules.

**Comment by yogeek** [comment]
No cache because I deploy with the CI tool that uses a different docker container each time.
But I think I found the cause :

kube-prometheus jsonnet dependency for node-mixins is [set to `master`](https://github.com/prometheus-operator/kube-prometheus/blob/release-0.4/jsonnet/kube-prometheus/jsonnetfile.json#L64-L71) whereas node-exporter version is [set to 1.18.1](https://github.com/prometheus-operator/kube-prometheus/blob/release-0.4/jsonnet/kube-prometheus/node-exporter/node-exporter.libsonnet#L8)

So it can lead to some inconsistency when new alerts have been added in node-mixins but the corresponding metrics are missing in the 1.18.1 node-exporter release, can't it ?

**Comment by paulfantom** [comment]
> kube-prometheus jsonnet dependency for node-mixins is set to master whereas node-exporter version is set to 0.18.1

That's a version mismatch and can lead to unexpected issues like the one you experienced. For better experience, you should use at least the same major version of mixin and component, in this case `v1`. Ideally, the same version should be used for both.

**Comment by yogeek** [comment]
@paulfantom Don't you think it may be better to fix this in the default configuration of kube-prometheus to avoid every users using the default to have the same problem ?

**Comment by paulfantom** [comment]
Yes, it would be good to fix node_exporter default version to v1 in https://github.com/prometheus-operator/kube-prometheus/blob/master/jsonnet/kube-prometheus/node-exporter/node-exporter.libsonnet#L8. Could you create a PR?

**Comment by yogeek** [comment]
https://github.com/prometheus-operator/kube-prometheus/pull/670

**Comment by paulfantom** [comment]
> I don't know if I must open other PRs for the other branches

That depends if you use them or you want to port your fix to previous versions.

**Comment by SayakMukhopadhyay** [comment]
From what I've seen, this fix also needs to be applied to the release-0.5 and release-0.6 branches.

**Comment by paulfantom** [comment]
Closing as this appears to be already fixed. Please reopen if this is still an issue.

Feel free to open PRs if you need the fix to be backported.
