### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by lilic** [prometheus-operator/kube-prometheus#68]
Since the repo got moved it seems like some of the relative [links](https://github.com/coreos/kube-prometheus/blob/master/docs/kube-prometheus-on-kubeadm.md#getting-up-and-running-fast-with-kube-prometheus) referencing the previous docs repo and [references](https://github.com/coreos/kube-prometheus/search?l=Markdown&q=prometheus-operator) to the `prometheus-operator` were leftover.

Guess this would be a good first issue for users to tackle. :)

**Comment by LiliC** [comment]
We use https://github.com/crawford/marker to check for broken links in our CI, might be of help here.

**Comment by metalmatze** [comment]
Yes, that was exactly the plan. First move the repository and then start working on updating all the documentation. https://github.com/crawford/marker looks really amazing! :+1:

**Comment by PhilipGough** [comment]
Closed via #1453
