### ISSUE TITLE
Kube-Prometheus rules version not matching with K8S1.15

### ISSUE THREAD

**Issue by KR411-prog** [prometheus-operator/kube-prometheus#696]
I executed below command ..
`jb install github.com/prometheus-operator/kube-prometheus/jsonnet/kube-prometheus@release-0.3
`
This downloads all the Kube-prometheus related jsonnet files.
I created a new jsonnet file to update a rule by importing  'kube-prometheus/kube-prometheus.libsonnet' .
But I finally find that the Prometheus-rules.yaml created , has rules which is from rules folder and not from rules1.14 folder.

We have Kubernetes 1.15 .And We use Kube-prometheus-stack.And it uses rules1.14 folder. 

How to make jb install to download files that can generate rules1.14 ?

**Comment by KR411-prog** [comment]
I have found jb install github.com/prometheus-operator/kube-prometheus/jsonnet/kube-prometheus/@release-0.6 works for rules1.14.
I am not sure if this release 0.6 is fine with Kubernetes 1.15 version.Please confirm.

**Comment by olegmayko** [comment]
There is no tight dependency, but you should check https://github.com/prometheus-operator/kube-prometheus#compatibility

**Comment by KR411-prog** [comment]
That is what confuses me.
rules 1.14 is for Kubernetes version >= 1.14.
But Kube-prometheus release 0.3 which is compatible with Kubernetes1.15  downloads rules and not rules1.14.
Only Kube-Prometheus 0.6 downloads rules1.14.  Thatswhy I am not sure if we need to download 0.3 or 0.6.
Please advice

**Comment by paulfantom** [comment]
Closing as k8s 1.15 and 1.14 reached EOL
