### ISSUE TITLE
Issue with tls proxy and installing

### ISSUE THREAD

**Issue by gurdeepsira** [prometheus-operator/kube-prometheus#700]
Hi,
I am trying to install kube-prometheus-stack but get the error here:-

https://github.com/prometheus-operator/kube-prometheus/issues/new?labels=kind%2Fsupport&template=support.md

What is the exact hell commmand syntax with the set arguments? I have:

 microk8s helm3 install promop prometheus-community/kube-prometheus-stack -n prom-operator --no-hooks --set-string prometheusOperator.admissionWebhooks.enabled=false, 
 --set-string prometheusOperator.tlsProxy.enabled=false

**Comment by paulfantom** [comment]
It looks to me like an issue with helm chart. Since we are not maintaining this helm chart, please open the issue at https://github.com/prometheus-community/helm-charts repository where the helm chart comes from.

Please reopen if this is indeed an issue with kube-prometheus.
