### ISSUE TITLE
Grafana overwrite every dashboard on deploy

### ISSUE THREAD

**Issue by jalberto** [prometheus-operator/kube-prometheus#701]
I am trying to use grafana helm deployed by kube-prometheus with a DB to back grafana state. In each deploy every dashboard is overwritten.

I understand the intention of this grafana deploy is to have a stateless service with config and dahbaord pragmatically deployed but this can cause lost of data in particular with WIP dashboards or very complex ones.

My suggestion is: Create a "kube-prometheus" folder in grafana, and keep in it every kube-prometheus related dashboard, and in each deploy only overwrite this folder (or other defined folders)

**Comment by paulfantom** [comment]
Closing due to staleness. Please reopen if you think this is still relevant.
