### ISSUE TITLE
What changes need to be made to access Grafana behind with an Ingress Controller?

### ISSUE THREAD

**Issue by cnukwas** [prometheus-operator/kube-prometheus#715]
I have installed below kube-prometheus-stack and getting an error when trying to access Grafana dashboard using it's own Ingress URL. We're using TraefikEE and here is the Ingress definition.

Chart: kube-prometheus-stack-9.4.5
App Version: 0.38.1

When I navigate to https://myorg.grafanatest.com URL, I get redirected to https://myorg.grafanatest.com/login with following message. 

 If you're seeing this Grafana has failed to load its application files

1. This could be caused by your reverse proxy settings.

2. If you host grafana under subpath make sure your grafana.ini root_url setting includes subpath. If not using a reverse proxy make sure to set serve_from_sub_path to true.

3. If you have a local dev build make sure you build frontend using: yarn start, yarn start:hot, or yarn build

4. Sometimes restarting grafana-server can help

I came across below post but not clear on how and where to make this change since I see few mounts in the pods, unless this can be configured in Helm Chart and/or YAML configuration and re-deploy entire kube-prometheus-stack or Grafana alone.

https://grafana.com/tutorials/run-grafana-behind-a-proxy/#1

I saw some posts about jsonnet but couldn't find any instructions on how and where to make those changes. Any help would be appreciated.

TraefikEE IngressRoute YAML:

kind: IngressRoute
metadata:
  name: grafana-test
  namespace: prometheus
spec:
  tls: {}
  entryPoints:
    - websecure
  routes:
    - match: Host(`myorg.grafanatest.com`)
      kind: Rule
      services:
        - name: prometheus-grafana
          namespace: prometheus
          port: 80

Thanks

**Comment by brancz** [comment]
The helm charts are neither used nor maintained by the prometheus-operator maintainers. Therefore we don't know the setup, so we're unlikely to be able to help you. I recommend creating an issue on the upstream helm charts repo where these helm charts are maintained.
