### ISSUE TITLE
jsonnet-bundler fais to install kube-prometheus

### ISSUE THREAD

**Issue by pslobo** [prometheus-operator/kube-prometheus#720]
**What happened?**
When attempting to install kube-prometheus, install fails due to issue with jsonnet-bundle, similar to what was reported in #420. 

As reported in #420, I've tried to installed with jb 0.2, jb 0.3 and also with @master always with the same error

**Did you expect to see some different?**
kube-prometheus and dependencies installed.

**How to reproduce it (as minimally and precisely as possible)**:
As per instructions:

```
mkdir my-kube-prometheus && cd my-kube-prometheus
jb init
jb install github.com/prometheus-operator/kube-prometheus/jsonnet/kube-prometheus@release-0.4
```

Error:
```
jb install github.com/prometheus-operator/kube-prometheus/jsonnet/kube-prometheus@release-0.4
GET https://github.com/prometheus-operator/kube-prometheus/archive/4e7440f742df31cd6da188f52ddc4e4037b81599.tar.gz 200
GET https://github.com/ksonnet/ksonnet-lib/archive/0d2f82676817bbf9e4acf6495b2090205f323b9f.tar.gz 200
GET https://github.com/kubernetes-monitoring/kubernetes-mixin/archive/f0a5099c8214241842b827a08eba6d7b515550ea.tar.gz 200
GET https://github.com/brancz/kubernetes-grafana/archive/d7c1a53462ecd533593c60e5277b92fbf7ea7623.tar.gz 200
GET https://github.com/coreos/prometheus-operator/archive/8b9d024467383d84b55d7e5e0d4f7a33eb5007b3.tar.gz 200
GET https://github.com/coreos/etcd/archive/00e49d0c10bb931f596d801d7368b5e0ae539fbd.tar.gz 200
GET https://github.com/prometheus/prometheus/archive/3240cf83f08e448e0b96a4a1f96c0e8b2d51cf61.tar.gz 200
GET https://github.com/prometheus/node_exporter/archive/f81747e608ea85ae44e76454eb63f9cb6484fb9e.tar.gz 200
jb: error: failed to install packages: downloading: failed to create tmp dir: stat vendor/.tmp: no such file or directory
```
It seems to fail randomly and not for any specific library.

**Environment**
* Prometheus Operator version:v0.35.1
* Kubernetes version information: 1.16.13
* Kubernetes cluster kind: GKE

**Comment by pslobo** [comment]
Minor update which I hadn't previously tested. Cloning the desired release and then doing `jb install` locally worked. So why is this failing when doing it the documented way?

**Comment by brancz** [comment]
Could you try the lastest release of jb? Not master and not 0.3, but 0.4?

**Comment by pslobo** [comment]
Initially I was using 0.4 (due to the version of k8s we're running). Then in desperation I tried the others and same issue. Now I've retried with 0.4 and seems to be working.

**Comment by brancz** [comment]
Happy that it at least works now! :) 

Can we close this issue then?

**Comment by pslobo** [comment]
Yeah sure. Forgot to close when I commented. Sorry about that.
