### ISSUE TITLE
All `runbook_url` alert annotations point to kubernetes-mixins

### ISSUE THREAD

**Issue by paulfantom** [prometheus-operator/kube-prometheus#731]
**What happened?**

All alerting rules have `runbook_url` annotation which points to https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md

**Did you expect to see some different?**

`runbook_url` shouldn't point to non-existent runbooks. It either should be removed or unset.

**How to reproduce it (as minimally and precisely as possible)**:

Look at https://github.com/prometheus-operator/kube-prometheus/blob/414d15c8957c04e27c8dce3e09ab56d314f1f5d3/manifests/prometheus-rules.yaml#L1016

**Environment**

**Comment by brancz** [comment]
I'm torn on this. The intention behind adding these anyways, with a placeholder, was to encourage people to write them. My feeling, however, is that doing PRs may be too high of a bar for this. How would you feel about changing these (maybe for a start) to be wiki entries in the kube-prometheus repo? The bar to change/add/fix something is super low. I would be willing to try this, and might even enable myself to contribute these when I run into an alert firing.

**Comment by paulfantom** [comment]
wiki sounds like a good idea :+1:
