### ISSUE TITLE
Ability to deploy blackbox_exporter as part of kube-prometheus

### ISSUE THREAD

**Issue by RiRa12621** [prometheus-operator/kube-prometheus#735]
**What is missing?**
 A blackbox_exporter deployment
**Why do we need it?**
With the recent addition of synthetic probes, it is possible to easily create blackbox exporter probes, however this still requires a blackbox exporter deployment to exist on cluster in order to work.

**Anything else we need to know?**:
This is a follow up to https://github.com/prometheus-operator/prometheus-operator/issues/3514

**Comment by lilic** [comment]
cc @prometheus-operator/kube-prometheus-reviewers ^

**Comment by paulfantom** [comment]
xref: https://github.com/prometheus-operator/prometheus-operator/issues/3514

**Comment by paulfantom** [comment]
SGTM to include this as a jsonnet patch. Similar to how we handle ksm-autoscaler: https://github.com/prometheus-operator/kube-prometheus/blob/master/jsonnet/kube-prometheus/ksm-autoscaler/ksm-autoscaler.libsonnet

**Comment by paulfantom** [comment]
@RiRa12621 if you want to pick this up, I uploaded my patch I was working on some time ago. It is available as a gist at https://gist.github.com/paulfantom/e27e79e294ca025748b05e5028b16346

**Comment by RiRa12621** [comment]
Thanks @paulfantom 
I'll give it a shot next week

**Comment by tpalfalvi** [comment]
@RiRa12621 did you manage to make progress? If not, I have something that seems to work for me, I can try to make a PR from that.

**Comment by RiRa12621** [comment]
Was in COVID isolation apparently that didn't help getting things done.
Happy to see a PR from you, if you have it ready already @tpalfalvi

**Comment by yeya24** [comment]
Is this issue still valid? Blackbox exporter is already part of the kube-prometheus stack and we already deployed it.
