### ISSUE TITLE
kube-state-metrics provides wrong memory metrics for pods

### ISSUE THREAD

**Issue by rsoika** [prometheus-operator/kube-prometheus#748]
**What happened?**
I installed latest version of kube-prometheus. with kube-state-metrics 1.9.7 on my self managed kubernetes cluster

**Did you expect to see some different?**

I expected that the metric service will provide metrics about pod memory consumption.

I verified the metrics with:

`$ kubectl top pod my-app`

and on the corresponding worker node with:

`$ docker stats`

It shows that the metric data concerning memory usage of a pod shows the double size as it should be.

**How to reproduce it (as minimally and precisely as possible)**:

You can compare the metric data with `kubectl top` and `docker stats`

After I uninstalled kube-prometheus stack and installed instead the [metric-server](https://github.com/kubernetes-sigs/metrics-server) all memory is displayed correctly and kubernetes scheduling was again as expected

Does anybody know how this can happen and what I can do about this issue?

See also discussions here:

https://stackoverflow.com/questions/64582065/why-is-openjdk-docker-container-ignoring-memory-limits-in-kubernetes
https://stackoverflow.com/questions/64440319/why-java-container-in-kubernetes-takes-more-memory-as-limits

**Environment**

Debian Buster

Kubernetes 1.19.3

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

* Manifests:

kube-state-metrics 1.9.7

**Comment by brancz** [comment]
You are most likely scraping both the `/metrics/cadvisor` as well as the `/metrics/resource` endpoints, which causes this. At least we've had many reports of this on slack lately. How did you install kube-prometheus and with what configuration?

**Comment by rsoika** [comment]
I cloned the kube-prometheus repo from github and than I did:

    $ kubectl create -f manifests/setup
    $ until kubectl get servicemonitors --all-namespaces ; do date; sleep 1; echo ""; done
    $ kubectl create -f manifests/

I did use kustomize only to add an ingress setup and add some Grafana environment variables to support SMTP. 
So I think from the core installation of kube-prometheus I did follow the given instructions. 

The thing which I did not understand is that  `kubectl top pod ... ` returned wrong metrics. After I uninstalled kube-prometheus and I installed the 'metrics-server' `kubectl top` shows the correct data. And than also my kubernetes cluster behaves as expected. The strange thing was, that when I looked into the memory consumption of my pods (I am running only java services) the numbers were double in the size. But I did not realize that these numbers where wrong. I also used k9s to monitor my cluster.

So the most of my time I invested to optimize my java containers. After uninstalling kube-prometheus and installing the metrics-server I can see now that everything is fine with my pods and also with my cluster.

**Comment by brancz** [comment]
Sorry for taking so long to reply, but could you elaborate in what way they seem "wrong"? Also which version of kube-prometheus are you installing?

**Comment by rsoika** [comment]
I checked out the master branch from github. This was a month ago. 
The result was that memory usage was measured  in double, so that I had to high volumes leading to a wrong behaviour. I uninstalled everything and installed the metrics-server to get the correct data.

**Comment by brancz** [comment]
Would you be open to trying again and sharing some data with us so we could debug the situation?

**Comment by rsoika** [comment]
I'm sorry, I can't test this again at the moment because my environment can't be changed now.

**Comment by rsoika** [comment]
I fear that we must close this issue because I can not provide more information or do a new testing. Do you have any suspicions about what might have been the root of my problem?

**Comment by brancz** [comment]
No problem! Please feel free to open a new issue should you encounter anything in the future! :)

**Comment by rdxmb** [comment]
I am having this issue with the double size of the memory with 
```

kube-prometheus-stack
appVersion: 0.49.0
version: 17.2.2
```

I can reproduce this with a container running a single process with about 7GB memory:

```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                          
     **17 root      20   0 7720256   7.4g   1740 S   6.2   5.9   0:32.41 tail**                             
      1 root      20   0    4260    592    528 S   0.0   0.0   0:00.05 sleep                            
      6 root      20   0    5992   3980   3392 S   0.0   0.0   0:00.02 bash                             
     15 root      20   0    5732   3508   3256 S   0.0   0.0   0:00.00 bash                             
     18 root      20   0    5992   3960   3372 S   0.0   0.0   0:00.02 bash                             
     27 root      20   0    7860   3616   3052 R   0.0   0.0   0:00.00 top  
```

The grafana dashboard shows me that there are about 14 GB memory used.

![Screenshot_20210825_125104](https://user-images.githubusercontent.com/30314040/130778151-b5b0d151-5590-43cc-93f5-05080293dfd0.png)

When I use TICK stack with the docker input plutin, the usage of about 7GB can be seen. Also have a look at the host memory, which increased for 7 GB only.

![Screenshot_20210825_125336](https://user-images.githubusercontent.com/30314040/130778746-838614bf-facc-4e97-b361-b6a757f2a81e.png)

In prometheus/kube-state-metrics, you can also reproduce this by having a process that uses more than the half of the memory allowed by kubernetes limit:

For example: 

- k8 memory limit is on 27 GB
- script in container uses 15 GB

result:

via TICK stack:

![Screenshot_20210825_130424](https://user-images.githubusercontent.com/30314040/130779891-c92edb51-315c-4869-affc-65f5567e5fee.png)

via kube-prometheus-stack:

![Screenshot_20210825_130113](https://user-images.githubusercontent.com/30314040/130779487-4fcc609b-6ad4-437c-bd56-70f460acd771.png)

This is impossible...

Information about the kubernetes Node which is running this:

`zwei     Ready                      <none>                 216d   v1.19.7    10.139.0.92   <none>        Ubuntu 20.04.1 LTS   5.4.0-62-generic   docker://19.3.14
`

**Comment by BalzGuenat** [comment]
Ran into the same issue. I believe this is because one tool measures the total memory usage while another only measures the working set.

**Comment by abhinov93** [comment]
I'm facing same issue.

Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2

If anyone has resolved it, kindly let me know .

**Comment by vanzoel7** [comment]
facing same issue
already changes `container_memory_working_set_bytes` with c`otnainer_memory_usage_bytes` in kube-prometheus-stack/templates/grafana/dashboard-1.14/k8s-resources-pod.yaml

but in grafana still show twice the true values of pod resoources from kubectl top pod or from kubernetes dashboard

**Comment by islastenikov** [comment]
I have the same issue. 
Kubernete 1.31.3

![Image](https://github.com/user-attachments/assets/c0673d68-7349-4bd5-875d-bbe74a0e0407)

Have a fresh cluster. Run a simple application and install prometheus operator using the 
```
kubectl apply --server-side -f manifests/setup
kubectl apply -f manifests/
```
Grafana with gefault dashboard get me imposible valuse, and i found the folowing:

![Image](https://github.com/user-attachments/assets/e384ccdc-c16f-44f8-bded-3f824f78d366)

When I use the same query in prometheus, it returns four values ​​from one container.
And they add up in graphan and as I understand it in kubectl top pod... becouse kubectl return the same value as grafana
They are the same except for service
```
service="prometheus-operator-kube-p-kubelet"
service="kubelet"
service="kube-prometheus-kubelet"
service="prometheus-stack-kube-prom-kubelet"
```

![Image](https://github.com/user-attachments/assets/8c89728a-3e9e-4793-8bb9-d16c5a1dd178)

Also noticed that a lot of targets are found in
```
serviceMonitor/monitoring/kubelet/0
serviceMonitor/monitoring/kubelet/1
serviceMonitor/monitoring/kubelet/2
serviceMonitor/monitoring/kubelet/3
```

![Image](https://github.com/user-attachments/assets/a4f1b6d2-f837-431d-9b3c-3a7b3f9e5c70)

And they all contain 4 times more Endpints than I have, let me remind you that I have 9 nods

![Image](https://github.com/user-attachments/assets/11e9d64b-eaa7-436d-9285-bfdfc2fecc0e)

**Comment by islastenikov** [comment]
I fix it with memory.
Added drop rule to `kubernetesControlPlane-serviceMonitorKubelet.yaml`

```
    - action: drop
      sourceLabels:
      - __name__
      - service
      regex: container_memory_working_set_bytes;(prometheus-operator-kube-p-kubelet|kube-prometheus-kubelet|prometheus-stack-kube-prom-kubelet)
```
Now I have normal values in all Grafana Dashboards as for RAM

![Image](https://github.com/user-attachments/assets/c14f095b-1ea0-4716-873c-2fd9b26748cb)
