### ISSUE TITLE
Whether the project can run on arm64 platform?

### ISSUE THREAD

**Issue by huangtianhua** [prometheus-operator/kube-prometheus#750]
I have a k8s cluster with several arm64 nodes, the container kube-state-metrics is always CrashLoopBackOff after I created the monitoring stack using the config in the manifests, I change to use the docker image k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.0.0-alpha.2, then the container works.
So does this project support arm64? could we change to use all the docker images which support arm64?

**Comment by lilic** [comment]
@huangtianhua this project is just a collection of projects, the image referenced in this project from https://github.com/kubernetes/kube-state-metrics for 1.9.7 does not support arm64 as per the docs https://github.com/kubernetes/kube-state-metrics#container-image we started building those images from 2.0 release onwards like you find, but that does not mean that 1.9.7 kube-state-metrics or any other cannot run on arm64 you just need to build your own image and it will work correctly.

cc @paulfantom as he runs on that arch IIRC.

**Comment by paulfantom** [comment]
@huangtianhua we have more info about arm/arm64 architecture support in https://github.com/prometheus-operator/kube-prometheus/issues/545.

Indeed v1.9.7 version of kube-state-metrics isn't a direct drop-in replacement for arm64, you can use https://hub.docker.com/r/carlosedp/kube-state-metrics image for it or switch to v2.0.0.

**Comment by huangtianhua** [comment]
Thanks all. 
But I am not sure why don't to use v2.0.0 of  kube-state-metrics in project default to support multi-arch?

**Comment by huangtianhua** [comment]
As we did for other docker images which mentioned in %545?

**Comment by lilic** [comment]
@huangtianhua 2.0.0 release is not out yet, its only a pre-release currently https://github.com/kubernetes/kube-state-metrics/releases. Nothing wrong with testing it, but it's not fully stable yet. It also differs from 1.9.7 as it was a breaking release. We are working on getting a stable release so testing helps! :)

**Comment by huangtianhua** [comment]
OK, thanks :)

**Comment by lilic** [comment]
@huangtianhua no problem, are you okay with us closing this or do you feel like you can add some docs to our README regarding support for arm?
