### ISSUE TITLE
[OCP4.5] PrometheusRules discovery in user-created namespaces

### ISSUE THREAD

**Issue by dariodsa** [prometheus-operator/kube-prometheus#752]
**What happened?**
If the PrometheusRule is created in user-created namespace, Prometheus operator doesn't see it. 
Created rule didn't appear in prometheus-k8s-rulefiles-0 configmap, but if the rule is created in some openshift-* namespace, Prometheus operator discovers it with no problem. 

**Did you expect to see some different?**

Created rule should appear in prometheus-k8s-rulefiles-0 configmap.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create PrometheusRule in user-created namespace (for example project)
2. Wait some time for operator or restart it. 
3. Rule should appear in prometheus-k8s-rulefiles-0 config map with other rules, but it doesn't. 
**Environment**

``OCP 4.5.11``

* Prometheus Operator version:

```
quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:1c24c01e807700d30430ce4ff2f77b54d55910cfbf9ee0cbe5c1c64979547463
```

* Kubernetes version information:

    `kubectl version`
    Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2-0-g52c56ce", GitCommit:"d7f3ccf9a5bdc96ba92e31526cf014b3de4c46aa", GitTreeState:"clean", BuildDate:"2020-09-11T23:16:13Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:

    OCP

**Comment by simonpasquier** [comment]
The prometheus-k8s instances are dedicated for the monitoring of the platform. You should enable the [monitoring your own services](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.5/html/monitoring/monitoring-your-own-services) capability to achieve this.
