### ISSUE TITLE
Master failing on AKS RBAC cluster v1.18.8 Adapter and Operator CrashLoopBackOff 

### ISSUE THREAD

**Issue by yaja0612** [prometheus-operator/kube-prometheus#755]
Applied the manifests from master with all pre requisites on AKS v1.8.8. 

Operator error : "Unhandled error received. Exiting..." err="communicating with server failed: an error on the server (\"\") has prevented the request from succeeding"

Adapter error : unable to install resource metrics API: unable to construct dynamic discovery mapper: unable to populate initial set of REST mappings: an error on the server ("") has prevented the request from succeeding

In master, the head is mentioned as not usable for v1.18.8 but in release 0.6 it is. 

Edit : metrics-server running in kube-system is working as expected. Reinstalled the cluster now to make sure there were no misconfigurations.

Any help much appreciated, thanks

**Comment by ajay1206** [comment]
Got it working by adding  KUBERNETES_SERVICE_HOST env variable to the deployment.

But have an issue with prometheus-k8's pod logs,

level=error ts=2020-11-06T10:27:32.692Z caller=klog.go:96 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:426: Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: an error on the server (\"\") has prevented the request from succeeding (get endpoints)"
level=error ts=2020-11-06T10:27:37.749Z caller=klog.go:96 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:428: Failed to watch *v1.Pod: failed to list *v1.Pod: an error on the server (\"\") has prevented the request from succeeding (get pods)"
level=error ts=2020-11-06T10:27:39.821Z caller=klog.go:96 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:426: Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: an error on the server (\"\") has prevented the request from succeeding (get endpoints)"

Adapter logs : 

E1106 09:28:35.658330       1 provider.go:187] unable to fetch CPU metrics for pod stratus/mcp-helm-chart-kured-csjmn, skipping
E1106 09:28:35.658335       1 provider.go:187] unable to fetch CPU metrics for pod stratus/mcp-helm-chart-kured-g96vz, skipping
E1106 09:28:35.658340       1 provider.go:187] unable to fetch CPU metrics for pod stratus/mcp-helm-chart-kured-tj2q9, skipping
E1106 09:28:35.658346       1 provider.go:187] unable to fetch CPU metrics for pod stratus/nginx-ingress-controller-69f65f76b6-hpp4w, skipping
E1106 09:28:35.658351       1 provider.go:187] unable to fetch CPU metrics for pod stratus/nginx-ingress-default-backend-7c868597f4-xjwsv, skipping
E1106 09:28:35.658356       1 provider.go:187] unable to fetch CPU metrics for pod stratus/vault-injector-agent-injector-64f44c97fb-ttgld, skipping

Happening for all the pods.

kubectl get apiservices
v1beta1.custom.metrics.k8s.io          monitoring/prometheus-adapter   False (FailedDiscoveryCheck)   10h
v1beta1.metrics.k8s.io                 kube-system/metrics-server      True                           15h


the prometheus-adapter api service has name: v1beta1.metrics.k8s.io and group: metrics.k8s.io, which when applied, overwrites the metrics-server apiservice, which gets recreated as its managed by Azure.

How and do I need to add the env variables to prometheus k8 pods?
