### ISSUE TITLE
Kube state metrics pods restarting continuosly after upgrade 

### ISSUE THREAD

**Issue by infa-svijayak** [prometheus-operator/kube-prometheus#772]
Hello Team,

The kube-state-metrics container is continuosly restarting after upgrading to the latest version
Image : tag: v1.9.7 

Trace[443632888]: [15.007406853s] [15.007406853s] Objects listed
Trace[443632888]: [19.347061718s] [4.339539637s] SyncWith done
E1109 13:18:24.465091       1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to list *v1.MutatingWebhookConfiguration: the server could not find the requested resource
E1109 13:18:24.466749       1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to list *v1.ValidatingWebhookConfiguration: the server could not find the requested resource
E1109 13:18:27.627646       1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to list *v1.MutatingWebhookConfiguration: the server could not find the requested resource
E1109 13:18:28.123469       1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to list *v1.ValidatingWebhookConfiguration: the server could not find the requested resource
E1109 13:18:29.335506       1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to list *v1.MutatingWebhookConfiguration: the server could not find the requested resource
E1109 13:18:29.731342       1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to list *v1.ValidatingWebhookConfiguration: the server could not find the requested resource

But we can see the clusterrole has permission to list and watch these resources.

- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - list
  - watch

- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - list
  - watch

Any help on this is appreciated. I see this is a duplicate of the issue https://github.com/kubernetes/kube-state-metrics/issues/1093 but I dont think that issue is fixed as well. Any help on this is appreciated

**Comment by brancz** [comment]
What version is your kubernetes cluster?

cc @lilic

**Comment by lilic** [comment]
Hey! Like Frederic mentioned can you detail your cluster version and the manifest you are using to deploy kube-state-metrics and the RBAC files.

**Comment by rpherrera** [comment]
https://github.com/kubernetes/kube-state-metrics/issues/1090#issuecomment-728698307

Repeating myself:

I was having this issue with a cluster on `v1.15.12-gke.20` version.

The most recent version of kube-state-metrics that worked for me without flooding the logs with these errors was: `v1.9.4`

**Comment by lilic** [comment]
@rpherrera yes you are using a too new version of kube-state-metrics, see compatibility matrix here https://github.com/prometheus-operator/kube-prometheus#kubernetes-compatibility-matrix or the one in kube-state-metrics https://github.com/kubernetes/kube-state-metrics/#compatibility-matrix neither claim to support 1.15 version of Kubernetes, so might be easier to roll back to 1.9.4 or earlier supported versions. We fixed a bug in that version of kubernetes to add support for newer versions, so that is what you are seeing.

**Comment by paulfantom** [comment]
Closing as this appears to be answered. Please reopen if you think this is still relevant.
