### ISSUE TITLE
How can  I find the log about alertmanager

### ISSUE THREAD

**Issue by HelenaZheng** [prometheus-operator/kube-prometheus#774]
We use the webhook in  altermanager  in the configfile: /etc/alertmanager/config/alertmanager.yaml.  But I can not receive the alters. 
I want to find the log about alters sent out. The file "/etc/alertmanger/config" can not be read directly.

How can I find the or get the log about altermanager?

**Comment by simonpasquier** [comment]
Run `kubectl logs <pod> -c alertmanager` where you replace `<pod>` by the name of the Alertmanager pod.

**Comment by HelenaZheng** [comment]
This method can not see weather the alter has been sent or not. I want to get the info messages. 发自我的华为手机-------- 原始邮件 --------发件人： Simon Pasquier <notifications@github.com>日期： 2020年11月10日周二 傍晚6:26收件人： prometheus-operator/kube-prometheus <kube-prometheus@noreply.github.com>抄送： Helena <haiyan_zhe@163.com>, Author <author@noreply.github.com>主    题： Re: [prometheus-operator/kube-prometheus] How can  I find the log about alertmanager (#774)
Run kubectl logs <pod> -c alertmanager where you replace <pod> by the name of the Alertmanager pod.

**Comment by simonpasquier** [comment]
if you need more details, you can always enable the debug log level. I'm also not sure whether you want to check if Alertmanager receives alerts from Prometheus or if Alertmanager sends notifications to the webhook.

**Comment by HelenaZheng** [comment]
All logs including receives from prometheus and sends notification the webhook. How can I enable the debug log level? 发自我的华为手机-------- 原始邮件 --------发件人： Simon Pasquier <notifications@github.com>日期： 2020年11月10日周二 傍晚6:55收件人： prometheus-operator/kube-prometheus <kube-prometheus@noreply.github.com>抄送： Helena <haiyan_zhe@163.com>, Author <author@noreply.github.com>主    题： Re: [prometheus-operator/kube-prometheus] How can  I find the log about alertmanager (#774)
if you need more details, you can always enable the debug log level. I'm also not sure whether you want to check if Alertmanager receives alerts from Prometheus or if Alertmanager sends notifications to the webhook.

**Comment by simonpasquier** [comment]
Debug level can be enabled by setting the `logLevel` field to the value `debug` in the [Alertmanager spec](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#alertmanagerspec).

**Comment by HelenaZheng** [comment]
> Debug level can be enabled by setting the `logLevel` field to the value `debug` in the [Alertmanager spec](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#alertmanagerspec).

 I cannot find the detail method to config the logLevel in the url [Alertmanager spec](https://github.com/prometheus-operator/prometheusoperator/blob/master/Documentation/api.md#alertmanagerspec). Could you give me the method?

**Comment by simonpasquier** [comment]
You can defined it like this:

```
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: example
spec:
  replicas: 3
  logLevel: debug
```

**Comment by HelenaZheng** [comment]
This can be useful.,  and I can see more information with " kubectl logs " .

**Comment by paulfantom** [comment]
Closing as this appears to be answered. Please reopen if you think this is still relevant.
