### ISSUE TITLE
How to use external storage to save prometheus metrics data

### ISSUE THREAD

**Issue by adminSxs** [prometheus-operator/kube-prometheus#779]
example: use influxdb save metrics data,how to update config?

**Comment by brancz** [comment]
You can configure Prometheus to remoteWrite to an influxdb database. The Prometheus object has the remoteWrite configuration exposed for this.

**Comment by adminSxs** [comment]
> You can configure Prometheus to remoteWrite to an influxdb database. The Prometheus object has the remoteWrite configuration exposed for this.

whether have reference documentation
