### ISSUE TITLE
Increase throttling alarm threshold 

### ISSUE THREAD

**Issue by dioguerra** [prometheus-operator/kube-prometheus#789]
Throttling on pods is set to trigger alarm when it is above 25%
This should be much much higher because if the applications are well set up they would consumer efficiently the resources.

I would say this Throttling should be only triggered for CPU usage above 95% to 90%.

It's normal for my clusters to always trigger an alarm for my prometheus-node-exporter pods as they always have a a CPU consumption that is around the 90% requested CPU

**Comment by paulfantom** [comment]
CPUThrottling alert threshold is customizable. Threshold value is adjusted with `cpuThrottlingPercent` variable, which comes from kubernetes-mixin.

Source: https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/alerts/resource_alerts.libsonnet

**Comment by MrD2** [comment]
Yes, but the grafana dashboards are pre-generated no?

Unless we find a way to pass the jsonnet code into the helm values config and generate the dashboards in sidecar/init container when instantiating grafana

**Comment by paulfantom** [comment]
> Yes, but the grafana dashboards are pre-generated no?

No, they are part of https://github.com/kubernetes-monitoring/kubernetes-mixin and changing `cpuThrottlingPercent` affects them too.

> I recon that this is the helms repo

No, helm repository lives in https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack and this project doesn't use helm.

**Comment by paulfantom** [comment]
Closing as this appears to be answered. Please reopen if you think this is still relevant.
