### ISSUE TITLE
chdir to cwd (\"/home/nonroot\") set in config.json failed: permission denied

### ISSUE THREAD

**Issue by system51** [prometheus-operator/kube-prometheus#791]
**What happened?**
When I use kube-prometheus, some nodes prompt errors, not all nodes will fail

![image](https://user-images.githubusercontent.com/26198108/99365884-d07d4780-28f2-11eb-9ea6-e0e1ed81d33d.png)

![image](https://user-images.githubusercontent.com/26198108/99366538-b7c16180-28f3-11eb-8219-79aaecd5ac5a.png)

**Did you expect to see some different?**

Run pod normally

**How to reproduce it (as minimally and precisely as possible)**:
Use files in the manifests directory in kube-prometheus

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
 

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
Insert Prometheus Operator logs relevant to the issue here
```

* Prometheus Logs:

```
Insert Prometheus logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by alexboor** [comment]
got the same issue with the default manifest folder
bare-metal cluster in centos/8
