### ISSUE TITLE
Bump Grafana version to the latest minor (at least)

### ISSUE THREAD

**Issue by mikekamornikov** [prometheus-operator/kube-prometheus#795]
**What is missing?**
Currently Grafana deployment uses `7.1.0` tag. While the latest `7.1.x` is `7.1.5` and the latest stable is `7.3.3`.

**Why do we need it?**
Besides other things patch versions bring browser specific fixes. For example my dashboards are broken (partly not rendered) in Safari in Grafana `7.1.0`.

**Environment**

* kube-prometheus version:

    `v0.6.0` or `master` (e667d85de83d3ff065bb58c9e109cc83b0c158d6)

**Anything else we need to know?**:
No

**Comment by lilic** [comment]
That sounds good to me, do you want to do the changes and open a PR for this?

**Comment by mikekamornikov** [comment]
Is it enough to update this line? https://github.com/prometheus-operator/kube-prometheus/blob/2cc09fb2a66ce975d0c9f495d713d7a42f13a467/manifests/grafana-deployment.yaml#L22

**Comment by paulfantom** [comment]
@mikekamornikov everything in `manifests/` directory is generated. To update grafana version you need to update this line: 
https://github.com/prometheus-operator/kube-prometheus/blob/0534d14813fbdf7d10d973589029c3aac5921f08/jsonnet/kube-prometheus/kube-prometheus.libsonnet#L117
and run `make generate`.

**Comment by mikekamornikov** [comment]
Corresponding PR - #808
