### ISSUE TITLE
align release branches with kubernetes versions?

### ISSUE THREAD

**Issue by s-urbaniak** [prometheus-operator/kube-prometheus#809]
Hello! :-)

Currently, we are keeping Kubernetes versions and release branches of kubernetes-mixin in sync. Does it make sense to also align the branch naming scheme?

The suggestion would be to name the next release branch `release-1.20`.

cross-linking the same request submitted in https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/519.

**Comment by s-urbaniak** [comment]
cc @prometheus-operator/kube-prometheus-reviewers

**Comment by paulfantom** [comment]
Let's discuss it in https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/519 to not duplicate ourselves :)

**Comment by brancz** [comment]
Should we maybe even close this here? If there is no consensus in https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/519, then it would make it only more confusing if it was inconsistent here.

**Comment by s-urbaniak** [comment]
yes, sounds good, let me close this one in favor of kubernetes-mixin!
