### ISSUE TITLE
Remote Write Config issue

### ISSUE THREAD

**Issue by arkachat** [prometheus-operator/kube-prometheus#820]
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Prometheus.spec.remoteWrite[0].basicAuth.username): invalid type for com.coreos.monitoring.v1.Prometheus.spec.remoteWrite.basicAuth.username: got "string", expected "map"

# The remote_write spec configuration for Prometheus.
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#remotewritespec
    remoteWrite:
    - url: https://prometheus-us-central1.grafana.net/api/prom/push
      basicAuth:
        username: "Grafana Cloud Username"
        password: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" (base64 encoded)

**Comment by arkachat** [comment]
For now I was able to make it work using the following:

   remoteWrite:
    - url: https://prometheus-us-central1.grafana.net/api/prom/push
      basicAuth:
        username:
          key: username
          name: grafana-cloud
        password: 
          key: password
          name: grafana-cloud


apiVersion: v1
kind: Secret
metadata:
  name: grafana-cloud
type: kubernetes.io/basic-auth
stringData:
  username: <base64 encoded user>
  password: <base64 encoded pass>

**Comment by shinebayar-g** [comment]
Where did you put the config?
