### ISSUE TITLE
Onde é definido que o alertmanager deve ser um statefulset?

### ISSUE THREAD

**Issue by matheusolivv** [prometheus-operator/kube-prometheus#834]
Onde é definido que o alertmanager deve ser um statefulset?

Where is it defined that the alertmanager should be a statefulset?

**Comment by paulfantom** [comment]
Alertmanager statefulset is created by prometheus-operator from Alertmanager Custom Resource. The fact that it is a StatefulSet is defined in prometheus-operator code.
