### ISSUE TITLE
If the host name is displayed in the alarm message

### ISSUE THREAD

**Issue by ktpktr0** [prometheus-operator/kube-prometheus#836]
I observed that the instance in the alarm message is an IP. When there are many hosts, it is difficult for me to quickly distinguish which host is the fault. At the same time, grafana shows IP addresses, which are not intuitive.

Now I want to get the host name on the basis of instance at the same time. I checked the data and found that there are the following methods that can be implemented, but this method makes the rule very long, and it is not flexible enough.

Add * on (instance) group after the original promql_ left(nodename) (node_ uname_ info)

Use in annotations{{$ labels.nodename }}To get the host name; alert host on mail template: {{ Labels.nodename }}To get the host name

I want to know what simple way to get the host name, including the host name of k8s cluster environment and the host name of non container environment.

**Comment by paulfantom** [comment]
Related https://github.com/prometheus-operator/prometheus-operator/issues/3652

**Comment by ktpktr0** [comment]
After research, I understand that there are four ways to get the hostname，Four methods to obtain the host name in the alarm information

Method one (each rule needs to be added, not recommended), and the host name (nodeName) is in the indicator node_ uname_ Info, and node_ uname_ The value of info happens to be 1, so we can use node in promql_ uname_ Info extraction, only need to add after the original promql
* on(instance) group_ left(nodename) (node_ uname_ info)

Frequently tested, I found that some expressions add * on (instance) group_ left(nodename) (node_ uname_ You can also get the host name after adding. Some expressions will prompt: no data


Method 2: use hosts to change instance to hostname:port Format.

Method 3: define label directly

Method 4. Apply k8s environment and use relabel directly_ configs

**Comment by paulfantom** [comment]
Closing as this appears to be self-answered. Please reopen if you think this is still relevant.
