### ISSUE TITLE
node-exporter doesn't need both /host/proc and hostPID=true

### ISSUE THREAD

**Issue by bboreham** [prometheus-operator/kube-prometheus#842]
Referring here:
https://github.com/prometheus-operator/kube-prometheus/blob/09ca49fce0353a90b63e172ce76435d2f85eccbb/manifests/node-exporter-daemonset.yaml#L84
and this option, which refers to a volume mount of `/proc`:
https://github.com/prometheus-operator/kube-prometheus/blob/09ca49fce0353a90b63e172ce76435d2f85eccbb/manifests/node-exporter-daemonset.yaml#L28

You don't need both, since `hostPID: true` makes `/proc` inside the container the same as the host.

**Comment by lilic** [comment]
Thanks for the issue! Sounds reasonable to me, do you want to open a PR to adjust this?

**Comment by paulfantom** [comment]
I was in the middle of some cleanup and didn't see @lilic comment above, so here is a PR: #844.

**Comment by bboreham** [comment]
I did not know enough about node-exporter to say which was better to remove.
