### ISSUE TITLE
How do I customize alertmanager.yaml

### ISSUE THREAD

**Issue by jiangxianliang007** [prometheus-operator/kube-prometheus#849]
I use kubectl patch secret update alertmanager.yaml, but it does not work.
```kubectl patch secret alertmanager-main-generated -n monitoring  -p='{"data":{"alertmanager.yaml": "Imdsb2JhbCI6CiAgInJlc29sdmVfdGltZW91dCI6ICI1bSIKICAic210cF9zbWFydGhvc3QiOiAnc210cC4xNjMuY29tOjQ2NScKICAic210"}}'```
---
![image](https://user-images.githubusercontent.com/24754263/103221007-9628b080-495c-11eb-8de4-8b9f2540fa63.png)

I deleted alertmanager-main-generated first, then created it, but it already exists because alertmanager-alertmanager.yaml automatically creates the default alertmanager-main-generated secret
```
kubectl delete secret alertmanager-main-generated -n monitoring
kubectl create secret generic alertmanager-main-generated --from-file=alertmanager.yaml -n monitoring
secret "alertmanager-main-generated" deleted
Error from server (AlreadyExists): secrets "alertmanager-main-generated" already exists

```

How do I customize alertmanager.yaml？

**Comment by olegmayko** [comment]
if you use jsonnet to generate manifests you may have a look at this [example](https://github.com/prometheus-operator/kube-prometheus/blob/master/examples/alertmanager-config-external.jsonnet)

**Comment by jiangxianliang007** [comment]
> jsonnet
If you don't use jsonnet, is there any other way to remove the default alertmanager-main-generated?

**Comment by shinebayar-g** [comment]
I also can't find any reference of what is using `alertmanager-main` secret. AFAIK there is no reference in `manifests`.

**Comment by okhuz** [comment]
I am also confused about that I am creating the manifest and in the CRD configSecret states that it defaults to alertmanater-{name} but it still is trying to mount the -generated one? What am I missing there?

**Comment by paulfantom** [comment]
`alertmanager-{name}` secret is picked up by prometheus-operator which then creates `alertmanager-{name}-generated` secret that is mounted in alertmanager pods.

**Comment by okhuz** [comment]
It was not generating from the secret that I have created actually. I needed to edit the statefulset in order to get configuration from ```alertmanager-{name}```. Now everything is working as expected. If that is the way config maps intended to work, I haven't been able to configure it that way.
