### ISSUE TITLE
How to Realize the Label of Custom Job in Prometheus.yml

### ISSUE THREAD

**Issue by huisebug** [prometheus-operator/kube-prometheus#85]
Previously, in prometheus. yml, the additional label: instance: slave1 for MySQL job was defined as follows
    - job_name: "mysql"
      static_configs:
      - targets: ["192.168.100.233:8104"]
        labels:
          instance: slave1

How to define it in service monitor? I need a template. Thank you.

**Comment by metalmatze** [comment]
You can find a ServiceMonitor example in the Prometheus Operator docs: https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md#related-resources

**Comment by huisebug** [comment]
I'm sorry, but I didn't find the job I wanted to monitor Prometheus with a custom label.  @metalmatze
