### ISSUE TITLE
Use kubelet's app.kubernetes.io/name label

### ISSUE THREAD

**Issue by brancz** [prometheus-operator/kube-prometheus#860]
**What is missing?**

We reverted this in: https://github.com/prometheus-operator/kube-prometheus/pull/858

Once a Prometheus Operator version with https://github.com/prometheus-operator/prometheus-operator/pull/3768 is released we can revert https://github.com/prometheus-operator/kube-prometheus/pull/858 again.

**Why do we need it?**

To be consistent with everything else.

**Anything else we need to know?**:

Related to https://github.com/prometheus-operator/prometheus-operator/pull/3768

**Comment by levi-pl** [comment]
I hope it is related to this change. prometheus operator is deployed from prometheus-community/kube-prometheus-stack-16.1.1.tgz . I did not modify any label related values.
``
kubectl -n kube-system get service prom-kube-prometheus-stack-kubelet -o jsonpath='{.metadata.labels}' 
``
{**"app.kubernetes.io/name":"kubelet"**,"k8s-app":"kubelet"}

``
k get -n monitoring servicemonitor prom-kube-prometheus-stack-kubelet -o jsonpath='{.spec.selector.matchLabels}' 
``
{**"app.kubernetes.io/managed-by":"prometheus-operator"**,"k8s-app":"kubelet"}

Label selection does not match between service and servicemonitor. Looks like a problem with chart. Should I open issue ?

**Comment by paulfantom** [comment]
@levi-pl This looks like an issue in [kube-prometheus-stack helm chart](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) and not in kube-prometheus project. We are using the following selector: https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/kubernetes-serviceMonitorKubelet.yaml#L88-L90

**Comment by levi-pl** [comment]
@paulfantom It looks like helm-chart was not updated to reflect this change. I dropped question here because I was not sure whether helm or operator is responsible for this service/serviceMonitor pair. If change in prometheus project was reflected in service name ...
Thanks. I will follow up with them.
