### ISSUE TITLE
What is the limit on the number of conditional expressions that can be registered in the object of one manifest file, kind: prometheus rules?

### ISSUE THREAD

**Issue by vdi-kakui** [prometheus-operator/kube-prometheus#891]
It's a question, not a bug.
What is the limit on the number of conditional expressions that can be registered in the object of one manifest file, kind: prometheus rules?

I registered about 100 conditional expressions, but they didn't appear on the GUI.
If it is a conditional expression of about 1 to 3, it will be displayed.

**Comment by simonpasquier** [comment]
it sounds more a question about Prometheus. Can you check the rule files in the Prometheus pod or using the Prometheus [API](https://prometheus.io/docs/prometheus/latest/querying/api/#rules)?

**Comment by vdi-kakui** [comment]
I checked the API and solved it.
