### ISSUE TITLE
examples/grafana-additional-rendered-dashboard-example-2.jsonnet is not working

### ISSUE THREAD

**Issue by wjentner** [prometheus-operator/kube-prometheus#897]
**What happened?**

The example https://github.com/prometheus-operator/kube-prometheus/blob/master/examples/grafana-additional-rendered-dashboard-example-2.jsonnet seems to be wrong.

First of all, I'd argue that the namespace should be defined as follows (?):

```jsonnet
values:++ {
  common:++ {
    namespace: 'monitoring'
  }
}
```

But the rest of the example is not working either as, when, commenting the line in the rawDashboards block out, nothing changes in the output yaml manifests.

Also, the grafana libsonnet which is used as a depencendcy (I think?) uses `_config:` instead of `values:` https://github.com/brancz/kubernetes-grafana/blob/master/grafana/grafana.libsonnet

I tried to fiddle a little bit around, wrapping it in `_config` or doing other several things, but I could not get it working.

Before the refactoring step in this repository, we had it working with:

```jsonnet
  (import 'kube-prometheus/main.libsonnet') +
  {
    _config+:: {
    
     grafana+:: {
        rawDashboards+:: {
          'my-dashboard.json': (importstr 'example-grafana-dashboard.json'),
        },
      },
  }
 }
```

**Did you expect to see some different?**

Dashboard is not added to the yaml manifests.

**How to reproduce it (as minimally and precisely as possible)**:

Use the example.

**Environment**

Latest master: https://github.com/prometheus-operator/kube-prometheus/commit/6081b306c2f552f00e4884d73553583c5f5928b7

**Comment by paulfantom** [comment]
Thank you for the report. I am currently trying to figure out main pain points for the migration before `release-0.7` (pre refactor) and the current `master`. The upstream grafana libsonnet is also going to be refactored soon to better integrate with kube-prometheus and for now.

Right now I would think adding option to pass any arbitrary `_config` into https://github.com/prometheus-operator/kube-prometheus/blob/master/jsonnet/kube-prometheus/components/grafana.libsonnet#L1-L25 should solve the issue. Similar way [we did it for any monitoring mixin](https://github.com/prometheus-operator/kube-prometheus/blob/master/jsonnet/kube-prometheus/components/prometheus.libsonnet#L30-L39). After that config should be as follows:

```
(import 'kube-prometheus/main.libsonnet') +
{
  values::+ {
    grafana+: {
      _config+: {
        rawDashboards+:: {
          'my-dashboard.json': (importstr 'example-grafana-dashboard.json'),
        },
      },
    },
  }
}
```

---

> First of all, I'd argue that the namespace should be defined as follows 

Yeah, `values` and `common` should be hidden objects. Can you create a PR?

**Comment by robbycuenot** [comment]
Experienced this issue as well, manifests were not updated when compiling on 0.6 branch.

Attempted both examples of importing pre-rendered Grafana dashboards from here:
https://github.com/prometheus-operator/kube-prometheus/blob/release-0.6/docs/developing-prometheus-rules-and-grafana-dashboards.md

Thought it could be a path issue, but errors are not thrown. Just no update in the manifests.

Compiled using jsonnet-ci docker image
