### ISSUE TITLE
build.sh fails with RUNTIME ERROR: couldn't open import "kube-prometheus/main.libsonnet"

### ISSUE THREAD

**Issue by jedimt** [prometheus-operator/kube-prometheus#901]
**What happened?**

Using the v0.7.0 release I'm not longer able to use the build.sh script. Attempting to build against any jsonnet file results in the following error:
```
root@prod-k8s-master-01:/opt/kube-prometheus/ingress# ../build.sh ingress.jsonnet
+ set -o pipefail
++ pwd
+ PATH=/opt/kube-prometheus/ingress/tmp/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/root/go/bin
+ rm -rf manifests
+ mkdir -p manifests/setup
+ jsonnet -J vendor -m manifests ingress.jsonnet
+ xargs '-I{}' sh -c 'cat {} | gojsontoyaml > {}.yaml' -- '{}'
RUNTIME ERROR: couldn't open import "kube-prometheus/main.libsonnet": no match locally or in the Jsonnet library paths
        ingress.jsonnet:17:4-43 thunk <kp> from <$>
        ingress.jsonnet:118:70-72
        <std>:1383:24-25        thunk from <function <anonymous>>
        <std>:1383:5-33 function <anonymous>
        ingress.jsonnet:118:53-81       $
        ingress.jsonnet:118:1-83
        ingress.jsonnet:118:1-83
        During evaluation
```

**How to reproduce it?**
Seems that any attempt to build manifests is failing at this point. 

**Environment**
Kubernetes 1.19.5
kube-prometheus v0.7.0 (due to refactor work warning)

**Comment by paulfantom** [comment]
Seems like you are still trying to use `master` instead of `release-0.7`. Maybe some dependency is pinned to `master`?

**Comment by paulfantom** [comment]
Closing as I believe this is the same issue as #902 (downloaded master version either directly or via some dependency). If you think this issue is different please reopen.
