### ISSUE TITLE
RUNTIME ERROR: couldn't open import "kube-prometheus/main.libsonnet": no match locally or in the Jsonnet library paths.

### ISSUE THREAD

**Issue by m6f13** [prometheus-operator/kube-prometheus#902]
**What happened?**
when using v6 of build, it returns "RUNTIME ERROR: couldn't open import "kube-prometheus/main.libsonnet": no match locally or in the Jsonnet library paths."

**Environment**
version 6 with: jb install github.com/prometheus-operator/kube-prometheus/jsonnet/kube-prometheus@release-0.6

** complete build log:
❯ ./build_v6.sh prometheus-grafana-minikube.jsonnet
```
+ set -o pipefail
++ pwd
+ PATH=/Users/martin/git/Monitoring-SWMP/manifests/manifests_prom_minikube/tmp/bin:/Users/martin/progs/anaconda3/bin:/Users/martin/progs/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
+ rm -rf manifests
+ mkdir -p manifests/setup
+ jsonnet -J vendor -m manifests prometheus-grafana-minikube.jsonnet
+ xargs '-I{}' sh -c 'cat {} | gojsontoyaml > {}.yaml' -- '{}'
RUNTIME ERROR: couldn't open import "kube-prometheus/main.libsonnet": no match locally or in the Jsonnet library paths.
	prometheus-grafana-minikube.jsonnet:1:13-52	thunk <kp>
	prometheus-grafana-minikube.jsonnet:15:81-83	thunk <o>
	std.jsonnet:1293:24
	std.jsonnet:1293:5-33	function <anonymous>
	prometheus-grafana-minikube.jsonnet:15:64-99	thunk <a>
	prometheus-grafana-minikube.jsonnet:15:1-101	function <anonymous>
	prometheus-grafana-minikube.jsonnet:15:1-101
```

** complete prometheus-grafana-minikube.jsonnet
```
local kp = (import 'kube-prometheus/main.libsonnet') + {
  _config+:: {
    namespace: 'monitoring-dev',
  },
  grafanaDashboards+:: {  //  monitoring-mixin compatibility
    'my-dashboard.json': (import 'example-grafana-dashboard.json'),
  },
  grafana+:: {
    dashboards+:: {  // use this method to import your dashboards to Grafana
      'my-dashboard.json': (import 'example-grafana-dashboard.json'),
    },
  },
};

{ ['00namespace-' + name]: kp.kubePrometheus[name] for name in std.objectFields(kp.kubePrometheus) } +
{ ['0prometheus-operator-' + name]: kp.prometheusOperator[name] for name in std.objectFields(kp.prometheusOperator) } +
{ ['node-exporter-' + name]: kp.nodeExporter[name] for name in std.objectFields(kp.nodeExporter) } +
{ ['kube-state-metrics-' + name]: kp.kubeStateMetrics[name] for name in std.objectFields(kp.kubeStateMetrics) } +
{ ['alertmanager-' + name]: kp.alertmanager[name] for name in std.objectFields(kp.alertmanager) } +
{ ['prometheus-' + name]: kp.prometheus[name] for name in std.objectFields(kp.prometheus) } +
{ ['grafana-' + name]: kp.grafana[name] for name in std.objectFields(kp.grafana) }
```

** complete build_v6.sh
```
#!/usr/bin/env bash

# This script uses arg $1 (name of *.jsonnet file to use) to generate the manifests/*.yaml files.

set -e
set -x
# only exit with zero if all commands of the pipeline exit successfully
set -o pipefail

# Make sure to use project tooling
PATH="$(pwd)/tmp/bin:${PATH}"

# Make sure to start with a clean 'manifests' dir
rm -rf manifests
mkdir -p manifests/setup

# Calling gojsontoyaml is optional, but we would like to generate yaml, not json
jsonnet -J vendor -m manifests "${1-example.jsonnet}" | xargs -I{} sh -c 'cat {} | gojsontoyaml > {}.yaml' -- {}

# Make sure to remove json files
find manifests -type f ! -name '*.yaml' -delete
rm -f kustomization
```

**Comment by olegmayko** [comment]
Have you been installed the dependencies as described  [here](https://github.com/prometheus-operator/kube-prometheus#installing)?

**Comment by aisbaa** [comment]
I think he did, because the error comes from `jsonnet` binary. I get the same by following https://github.com/prometheus-operator/kube-prometheus#installing instructions.
```
RUNTIME ERROR: couldn't open import "kube-prometheus/main.libsonnet": no match locally or in the Jsonnet library paths.
```

steps to repro:
- go to https://github.com/prometheus-operator/kube-prometheus#installing
- execute install instructions:
```
$ mkdir my-kube-prometheus; cd my-kube-prometheus
$ jb init  # Creates the initial/empty `jsonnetfile.json`
# Install the kube-prometheus dependency
$ jb install github.com/prometheus-operator/kube-prometheus/jsonnet/kube-prometheus@release-0.4 # Creates `vendor/` & `jsonnetfile.lock.json`, and fills in `jsonnetfile.json`
```
- execute `jb update`
- copy `build.sh` and `example.jsonnet` to `my-kube-prometheus`
- execute `./build.sh example.jsonnet` and get an error
- there is a note to install `gojsontoyaml`: "before compiling, install gojsontoyaml tool with go get github.com/brancz/gojsontoyaml"
- install `gojsontoyaml`
- execute `./build.sh example.jsonnet` and get the same error

Turns out there is no `kube-prometheus/main.libsonnet` not sure what it should be though.

**Comment by m6f13** [comment]
> Have you been installed the dependencies as described [here](https://github.com/prometheus-operator/kube-prometheus#installing)?

i have installed the dep as described and already used the build multiple times before... just today I want to generate a new manifest and get this runtime error.

**Comment by aisbaa** [comment]
@m6f13 copy [example.json](https://github.com/prometheus-operator/kube-prometheus/blob/release-0.4/example.jsonnet) from release-0.4 branch.

**Comment by m6f13** [comment]
> @m6f13 copy [example.json](https://github.com/prometheus-operator/kube-prometheus/blob/release-0.4/example.jsonnet) from release-0.4 branch.

i made such workaround already be replacing the import "kube-prometheus/main.libsonnet" with import "kube-prometheus/kube-prometheus.libsonnet"
it works for my case of Grafana-dashboard build:
`
//local kp = (import 'kube-prometheus/main.libsonnet') + {
local kp = (import 'kube-prometheus/kube-prometheus.libsonnet') + {
  _config+:: {
    namespace: 'monitoring-dev',
  },
  grafanaDashboards+:: {  //  monitoring-mixin compatibility
    'NEAR-QA-Artifactory.json': (import 'custom/NEAR-QA-Artifactory-dashboard.json'),
  },
  grafana+:: {
    dashboards+:: {  // use this method to import your dashboards to Grafana
      'NEAR-QA-Artifactory.json': (import 'custom/NEAR-QA-Artifactory-dashboard.json'),
    },
  },
};

{ ['00namespace-' + name]: kp.kubePrometheus[name] for name in std.objectFields(kp.kubePrometheus) } +
{ ['0prometheus-operator-' + name]: kp.prometheusOperator[name] for name in std.objectFields(kp.prometheusOperator) } +
{ ['node-exporter-' + name]: kp.nodeExporter[name] for name in std.objectFields(kp.nodeExporter) } +
{ ['kube-state-metrics-' + name]: kp.kubeStateMetrics[name] for name in std.objectFields(kp.kubeStateMetrics) } +
{ ['alertmanager-' + name]: kp.alertmanager[name] for name in std.objectFields(kp.alertmanager) } +
{ ['prometheus-' + name]: kp.prometheus[name] for name in std.objectFields(kp.prometheus) } +
{ ['grafana-' + name]: kp.grafana[name] for name in std.objectFields(kp.grafana) }
`

**Comment by paulfantom** [comment]
It seems like you downloaded `master` version. `release-0.4` (and any other `release-` branch) doesn't have any mentions of `main.jsonnet`.

For future deployments, we are preparing a migration guide. [Right now it is advised to use `release-0.7` branch.](https://github.com/prometheus-operator/kube-prometheus/tree/master#warning)
