### ISSUE TITLE
Persistent Storage for Prometheus

### ISSUE THREAD

**Issue by hans-fischer** [prometheus-operator/kube-prometheus#915]
**What is missing?**
Using a PV to store metrics in Prometheus even when deployment is upgraded or deleted for a moment.

**Why do we need it?**
I would like to keep the metrics for a certain rather than til the next deployment. 

**Environment**
Any Kubernetes cluster.

* kube-prometheus version:

    `84f24095d6a057a969bae3b6f40762d2a0dbb8b4` (release-0.7)

**Anything else we need to know?**:
I think you got the point.
I don't know, why nobody speaks a word about storage for metrics. Maybe it is a bad idea for any reason?

**Comment by paulfantom** [comment]
This is already possible, we have [this example](https://github.com/prometheus-operator/kube-prometheus/blob/release-0.7/examples/prometheus-pvc.jsonnet) which allows attaching PVC for long-term storage.

**Comment by hans-fischer** [comment]
Ohh thanks, that all I need to know.
