### ISSUE TITLE
Move objects related to control-plane out of prometheus object

### ISSUE THREAD

**Issue by paulfantom** [prometheus-operator/kube-prometheus#921]
Currently, all ServiceMonitors for control-plane components are located inside `prometheus` object. This unnecessarily overcrowds already large object while not giving any benefits.

It might be better to create a new top-level object like "controlPlane" or just "kubernetes" and add those ServiceMonitors and Services from addons as well as kubernetes-mixin there.

**Comment by brancz** [comment]
I like this.

**Comment by paulfantom** [comment]
Done in https://github.com/prometheus-operator/kube-prometheus/pull/960
