### ISSUE TITLE
Make topology configurable in anti-affinity.libsonnet

### ISSUE THREAD

**Issue by yogeek** [prometheus-operator/kube-prometheus#927]
Slack dicussion : https://kubernetes.slack.com/archives/CAX9GU941/p1612883283008900

**What is missing?**

Today, it is possible to add pod anti-affinity by using this lib :
```
 (import 'kube-prometheus/kube-prometheus-anti-affinity.libsonnet') +
```
but the [topology value is hard-coded](https://github.com/prometheus-operator/kube-prometheus/blob/master/jsonnet/kube-prometheus/addons/anti-affinity.libsonnet#L10) to `hostname`

It would be useeful to allow users to choose the topology constraint, to choose to schedule the pods in different zones or region for example.

**Why do we need it?**

With only a `hostname` anti-affinity, Prometheus and AlertManager replicas can be scheduled in the same AZ today, and as they are linked to PVCs, they are bound to stay in this AZ and when the number of workers is not high in one AZ, it can lead to potential issues.

**Environment**

k8s 1.18.2

* kube-prometheus version:

    `release-0.6`

**Anything else we need to know?**:

For now, the solution proposed by @paulfantom in Slack is working :

```
(import 'kube-prometheus/kube-prometheus.libsonnet') +
(import 'kube-prometheus/kube-prometheus-anti-affinity.libsonnet') + {
  prometheus+:: {
    prometheus+: {
      spec+: {
        affinity+: {
          podAntiAffinity+: {
            preferredDuringSchedulingIgnoredDuringExecution: std.map(
              function(e) e {
                podAffinityTerm+: {
                  topologyKey: 'kubernetes.io/zone',
                },
              },
              super.preferredDuringSchedulingIgnoredDuringExecution,
            )
          },
        },
      }
    },
  },
}
```

but make the topology configurable would be nicer.

**Comment by paulfantom** [comment]
Done in https://github.com/prometheus-operator/kube-prometheus/pull/961.
