### ISSUE TITLE
Will this work with Prometheus v2.9.2?

### ISSUE THREAD

**Issue by huangqun** [prometheus-operator/kube-prometheus#93]
I see that in the latest master, we are using prometheus v2.7.2, I wonder if it would work with the latest (i.e. v2.9.2) instead?

Thanks!

**Comment by metalmatze** [comment]
Yes. Totally. We just don't always bump the version. You can simply do this in your copied example.jsonnet for generated YAML files.

**Comment by brancz** [comment]
Feel free to create a PR to bump it though :)

**Comment by huangqun** [comment]
It seems simply bumping the version won't work because since v2.8.0 new config parameters were introduced which are not supported by the operator yet?

```
--storage.tsdb.retention.time: This determines when to remove old data. Defaults to 15d. Overrides storage.tsdb.retention if this flag is set to anything other than default.
--storage.tsdb.retention.size: [EXPERIMENTAL] This determines the maximum number of bytes that storage blocks can use (note that this does not include the WAL size, which can be substantial). The oldest data will be removed first. Defaults to 0 or disabled. This flag is experimental and can be changed in future releases. Units supported: KB, MB, GB, PB. Ex: "512MB"
--storage.tsdb.retention: This flag has been deprecated in favour of storage.tsdb.retention.time.```

**Comment by brancz** [comment]
It still works completely even if using deprecated flags, also we just released v0.30.0 of the operator so the flags are used appropriately.

**Comment by huangqun** [comment]
Hi @brancz, I'm going through the code of latest version of the operator, but I don't see `storage.tsdb.retention.size` being supported in it?

**Comment by brancz** [comment]
I would need to double check but I think you’re right that we don’t support this yet.

**Comment by paulfantom** [comment]
Closing due to staleness. Please reopen if you think this is still relevant.
