### ISSUE TITLE
jb install failed - etcd-mixin: no such file or directory

### ISSUE THREAD

**Issue by rohitdurvasula** [prometheus-operator/kube-prometheus#931]
**What happened?**
When attempting to install kube-prometheus, install fails due to issue with jsonnet-bundle

**Did you expect to see some different?**
kube-prometheus and dependencies installed.

**How to reproduce it (as minimally and precisely as possible)**:

jb init
jb install github.com/prometheus-operator/kube-prometheus/jsonnet/kube-prometheus@v0.7.0
GET https://github.com/prometheus-operator/kube-prometheus/archive/84f24095d6a057a969bae3b6f40762d2a0dbb8b4.tar.gz 200
GET https://github.com/kubernetes/kube-state-metrics/archive/89aaf6c524ee891140c4c8f2a05b1b16f5847309.tar.gz 200
GET https://github.com/brancz/kubernetes-grafana/archive/014301fd5f71d8305a395b2fb437089a7b1a3999.tar.gz 200
GET https://github.com/prometheus-operator/prometheus-operator/archive/d8b7d3766225908d0239fd0d78258892cd0fc384.tar.gz 200
GET https://github.com/prometheus-operator/prometheus-operator/archive/d8b7d3766225908d0239fd0d78258892cd0fc384.tar.gz 200
GET https://github.com/kubernetes-monitoring/kubernetes-mixin/archive/1941868d86a7c37e5505a14e3d567bda90e80357.tar.gz 200
GET https://github.com/prometheus/alertmanager/archive/023937679f1a913dce8aa29c7b5756e77a28f9c0.tar.gz 200
GET https://github.com/thanos-io/thanos/archive/37e6ef61566c7c70793ba6d128f00c4c66cb2402.tar.gz 200
GET https://github.com/etcd-io/etcd/archive/d33a1c91f0cf1a5edd40ddc8df3ef6a679c747e3.tar.gz 200
panic: rename /root/build_artifacts/monitoring/vendor/.tmp/jsonnetpkg-github.com-etcd-io-etcd-Documentation-etcd-mixin-**master512625198/Documentation/etcd-mixin /root/build_artifacts/monitoring/vendor/github.com/etcd-io/etcd/Documentation/etcd-mixin: no such file or directory**

goroutine 1 [running]:
github.com/jsonnet-bundler/jsonnet-bundler/pkg.(*GitPackage).Install(0xc000010260, 0x898ce0, 0xc00001c088, 0xc0000169f0, 0x30, 0xc000016540, 0x27, 0xc00036c6b0, 0x6, 0x0, ...)
/root/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.4.0/pkg/git.go:220 +0x1d9d
github.com/jsonnet-bundler/jsonnet-bundler/pkg.download(0xc00012c410, 0x0, 0xc00036c6b0, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000016540, ...)
/root/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.4.0/pkg/packages.go:289 +0x1b6
github.com/jsonnet-bundler/jsonnet-bundler/pkg.ensure(0xc000474720, 0xc000016540, 0x27, 0xc000013f20, 0x0, 0x0, 0x0)
/root/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.4.0/pkg/packages.go:233 +0x6d7
github.com/jsonnet-bundler/jsonnet-bundler/pkg.ensure(0xc000013ec0, 0xc000016540, 0x27, 0xc000013f20, 0x27, 0x0, 0x1)
/root/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.4.0/pkg/packages.go:259 +0xf0f
github.com/jsonnet-bundler/jsonnet-bundler/pkg.Ensure(0xc000013ec0, 0x1, 0xc000016540, 0x27, 0xc000013f20, 0x0, 0x0, 0x0)
/root/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.4.0/pkg/packages.go:55 +0x67
main.installCommand(0xc000016214, 0x20, 0x81d249, 0x6, 0xc000020f00, 0x1, 0x1, 0x0, 0x0)
/root/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.4.0/cmd/jb/install.go:76 +0x765
main.Main(0xc00001e0b8)
/root/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.4.0/cmd/jb/main.go:82 +0xb17
main.main()
/root/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.4.0/cmd/jb/main.go:37 +0x25

**Environment**
Kubernetes version information: 1.19.3
Kubernetes cluster kind: kubeadm

**Anything else we need to know?**:
 I did notice this recent change in etcd repo - https://github.com/etcd-io/etcd/commit/2afa5ff45ff4cc7f7a77218f0d7e52b377733dc0
 
 Wonder if its related ?

**Comment by rohitdurvasula** [comment]
Sry I wanted to open a blank issue. This by no means is a bug. Not sure how to change it.

**Comment by rohitdurvasula** [comment]
Looks like the new location for the etcd-mixin directory is https://github.com/etcd-io/website/tree/master/content/docs/current/etcd-mixin

**Comment by underrun** [comment]
seems like a bug to me?

could pin the commit sha from which kube-prometheus pulls the etcd-mixin - they didn't rewrite history so it would still be there in a previous commit. might be a good idea to pin all versions of dependencies to commits?

**Comment by underrun** [comment]
oh hmm ... seems the version is pinned but `jb` expects the path to exist in master as well as in the pinned revision? or something else is depending on the version in master that's not there? either way this is preventing not just 0.7.0 but all releases of kube-thanos to fail install.

**Comment by rohitdurvasula** [comment]
Issue fixed in etcd repo. Things seem to work now.
