### ISSUE TITLE
etcd mix-in has been moved in upstream repo, breaks install and update.

### ISSUE THREAD

**Issue by dewe** [prometheus-operator/kube-prometheus#933]
Running jb update or install with kube-prometheus results in panic. 

https://github.com/etcd-io/etcd/pull/12687 results in a broken reference.

Reproduce:

```
# jb version 0.42
jb install github.com/prometheus-operator/kube-prometheus/jsonnet/kube-prometheus@release-0.6
```

Looks like it effects any release of kube-prometheus, except for master branch.

**Comment by dewe** [comment]
Perhaps it would be better to pin the version of the etcd mix-in here: https://github.com/prometheus-operator/kube-prometheus/blob/f69ff3d63de17f3f52b955c3b7e0d7aff0372873/jsonnet/kube-prometheus/jsonnetfile.json#L20

**Comment by underrun** [comment]
this is an issue in all release branches - there are PRs open for 0.6 and 0.4: 

https://github.com/prometheus-operator/kube-prometheus/pull/935
https://github.com/prometheus-operator/kube-prometheus/pull/934

and as of now, etcd have moved the repo back again until this gets sorted out: https://github.com/etcd-io/etcd/pull/12688

**Comment by underrun** [comment]
to be clear, while things are unblocked it's only because etcd is waiting for a downstream fix in this repo

**Comment by paulfantom** [comment]
`master`, `release-0.6`, and `release-0.4` are fixed. Help is wanted for PRs for other release branches.

**Comment by paulfantom** [comment]
Just to note: if you pin etcd-mixin to a different version than the one specified in kube-prometheus, `jb` will install that version.

**Comment by paulfantom** [comment]
I am closing this as all release branches after 0.4 are fixed.
