### ISSUE TITLE
which branch  is stable?

### ISSUE THREAD

**Issue by hillbun** [prometheus-operator/kube-prometheus#958]
master of release-0.7?

**Comment by brancz** [comment]
cc @paulfantom

**Comment by paulfantom** [comment]
I recommend using `release-0.7` for now. We will remove [the notification from README.md](https://github.com/prometheus-operator/kube-prometheus#warning) and at that point, `master` is stable again.

**Comment by paulfantom** [comment]
We are opening `main` branch with #978
