### ISSUE TITLE
Missing metrics on new install of 13.13.0 helm chart- but all seems to be running fine

### ISSUE THREAD

**Issue by KlavsKlavsen** [prometheus-operator/kube-prometheus#998]
**What happened?**
I installed default 13.13.0 of prometheus-kube-stack helm chart.
I see graphs in prometheus dashboard and API dashboard.. almost everything else is empty.

 a lot of the metrics are missing.. f.ex. node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate

kube-state-metrics is running and under prometheus I see no scrape errors

if I run: kube_pod_info{namespace="monitoring", pod="kube-prometheus-stack-kube-state-metrics-7877f4cc7c-fstcr"} - I get:
kube_pod_info{container="kube-state-metrics", created_by_kind="ReplicaSet", created_by_name="kube-prometheus-stack-kube-state-metrics-7877f4cc7c", endpoint="http", host_ip="10.2.35.237", instance="100.124.0.2:8080", job="kube-state-metrics", namespace="monitoring", node="ip-10-2-35-237.eu-west-1.compute.internal", pod="kube-prometheus-stack-kube-state-metrics-7877f4cc7c-fstcr", pod_ip="100.124.0.2", service="kube-prometheus-stack-kube-state-metrics", uid="16982511-7313-40b7-9798-2da4fd7eaf16"}

**Environment**

* Prometheus Operator version: quay.io/prometheus-operator/prometheus-operator:v0.45.0

* Kubernetes version information: v1.18.15
* Kubernetes cluster kind: kops cluster.

* Manifests:
all generated by helm chart kube-prometheus-stack.

I see no errors in logs and no pod failures.

**Comment by paulfantom** [comment]
Looks like a helm issue. Since we are not maintaining those charts, you might have faster feedback by filing a ticket in https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack

**Comment by KlavsKlavsen** [comment]
closing
